// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtx_rx_tb.h for the primary calling header

#ifndef VERILATED_VTX_RX_TB___024ROOT_H_
#define VERILATED_VTX_RX_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
class Vtx_rx_tb_generic_register__Rz1;


class Vtx_rx_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtx_rx_tb___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_thr;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_dll;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_ier;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_dlh;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_mcr;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_dlf;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_mode;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_clk;
    Vtx_rx_tb_generic_register__Rz1* __PVT__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_txthr;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(rx,0,0);
        VL_OUT8(tx,0,0);
        VL_IN8(s_awvalid,0,0);
        VL_OUT8(s_awready,0,0);
        VL_IN8(s_wvalid,0,0);
        VL_OUT8(s_wready,0,0);
        VL_IN8(s_wstrb,3,0);
        VL_OUT8(s_bvalid,0,0);
        VL_IN8(s_bready,0,0);
        VL_IN8(s_arvalid,0,0);
        VL_OUT8(s_arready,0,0);
        VL_OUT8(s_rvalid,0,0);
        VL_IN8(s_rready,0,0);
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__clk;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__rst;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__rx;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__tx;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_awvalid;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_awready;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_wvalid;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_wready;
        CData/*3:0*/ tx_rx_tb__DOT____Vtogcov__s_wstrb;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_bvalid;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_bready;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_arvalid;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_arready;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_rvalid;
        CData/*0:0*/ tx_rx_tb__DOT____Vtogcov__s_rready;
        CData/*1:0*/ tx_rx_tb__DOT__dut__DOT__s_bresp;
        CData/*1:0*/ tx_rx_tb__DOT__dut__DOT__s_rresp;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__regfile_wr_en;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT__regfile_wr_addr;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT__regfile_rd_addr;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__oversample_tick;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT__oversample_factor;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__tx_start_pulse;
        CData/*1:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__s_bresp;
        CData/*1:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__s_rresp;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__regfile_wr_en;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__regfile_wr_addr;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__regfile_rd_addr;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__oversample_tick;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__oversample_factor;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__tx_start_pulse;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_addr_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_data_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT____Vtogcov__wr_addr_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT____Vtogcov__wr_data_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__thr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__dll_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__ier_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__dlh_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__fcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__lcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__mcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__dlf_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__mode_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__clk_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__rxthr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__txthr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__timeout_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__thr_wr_en;
    };
    struct {
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__dll_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__ier_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__dlh_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__fcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__lcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__mcr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__dlf_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__mode_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__clk_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__rxthr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__txthr_wr_en;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__timeout_wr_en;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__frac_accum;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__frac_carry;
        CData/*4:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT____Vtogcov__frac_accum;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT____Vtogcov__frac_carry;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__tx_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__tx_busy;
        CData/*2:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__state;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__bit_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__os_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__stop_count;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__stop_ticks;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__parity_enabled;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__tx_done;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__tx_busy;
        CData/*2:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__state;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__bit_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__os_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__stop_count;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__stop_ticks;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__parity_enabled;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__parity_bit;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__u_parity__DOT__ones_count;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__u_parity__DOT____Vtogcov__ones_count;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_valid;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_busy;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__frame_error;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__parity_error;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__break_detect;
        CData/*2:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__state;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__bit_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__os_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__stop_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__zero_count;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_ff1;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_ff2;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_prev;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__falling_edge;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__stop_ticks;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__parity_enabled;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__expected_parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__received_parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_valid;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_busy;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__frame_error;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__parity_error;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__break_detect;
        CData/*2:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__state;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__bit_count;
    };
    struct {
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__os_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__stop_count;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__zero_count;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_ff1;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_ff2;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_prev;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__falling_edge;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__stop_ticks;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__parity_enabled;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__expected_parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__received_parity_bit;
        CData/*5:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__midpoint;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__u_parity__DOT__ones_count;
        CData/*3:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__u_parity__DOT____Vtogcov__ones_count;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_start_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_data_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_par_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_stop_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_idle_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_start_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_data_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_par_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_stop_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__pc_idle_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_lcr_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_fcr_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_rxthr_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_timeout_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_fcr_sc_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_dlab_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_rsv_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_lcr_rst_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_fcr_rst_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_fcr_sc_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_dlab_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__rc_rsv_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_aw_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_w_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_ar_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_br_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_rr_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_rx_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_aw_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_w_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_ar_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_br_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_rr_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__ac_rx_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__any_fail;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__any_pass;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__all_pass;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_start_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_data_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_par_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_stop_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_idle_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_start_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_data_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_par_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_stop_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__pc_idle_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_lcr_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_fcr_rst_ok;
    };
    struct {
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_rxthr_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_timeout_rst_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_fcr_sc_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_dlab_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_rsv_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_lcr_rst_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_fcr_rst_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_fcr_sc_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_dlab_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__rc_rsv_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_aw_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_w_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_ar_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_br_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_rr_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_rx_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_aw_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_w_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_ar_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_br_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_rr_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__ac_rx_FAIL;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__any_fail;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__any_pass;
        CData/*2:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__state;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__os_count;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__bit_count;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__stop_count;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__prev_pin;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__exp_data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__exp_stop_ticks;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__ones_count;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__exp_parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__pin_ff1;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__pin_ff2;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__pin_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__pin_fall;
        CData/*2:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__state;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__os_count;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__bit_count;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__stop_count;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__prev_pin;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__exp_data_bits;
        CData/*5:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__exp_stop_ticks;
        CData/*3:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__ones_count;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__exp_parity_bit;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__parity_enabled;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__falling_edge;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__midpoint;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__pin_ff1;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__pin_ff2;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__pin_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__pin_fall;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vlvbound_h48595257__0;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__spec_dlab_ier_access_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__rst_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__fcr_written_with_reset_bits;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__dlab_was_set;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__spec_dlab_ier_access_ok;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__rst_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__fcr_written_with_reset_bits;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__dlab_was_set;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT___Vpast_0_0;
        CData/*4:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT___Vpast_1_0;
    };
    struct {
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__awvalid_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__wvalid_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__arvalid_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT____Vtogcov__awvalid_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT____Vtogcov__wvalid_prev;
        CData/*0:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT____Vtogcov__arvalid_prev;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_addr_done;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_data_done;
        CData/*0:0*/ __Vdly__s_bvalid;
        CData/*0:0*/ __Vdly__s_arready;
        CData/*0:0*/ __Vdly__s_rvalid;
        CData/*2:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_tx__DOT__state;
        CData/*3:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_tx__DOT__bit_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_tx__DOT__os_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_tx__DOT__stop_count;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_ff2;
        CData/*2:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__state;
        CData/*3:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__bit_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__os_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__stop_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__zero_count;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__pin_ff2;
        CData/*2:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__state;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__os_count;
        CData/*3:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__bit_count;
        CData/*5:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__stop_count;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__fcr_written_with_reset_bits;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__dlab_was_set;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__awvalid_prev;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__wvalid_prev;
        CData/*0:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__u_axi_chk__DOT__arvalid_prev;
        CData/*4:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__frac_accum;
        CData/*0:0*/ __Vsampled_TOP__tx_rx_tb__DOT__dut__DOT__regfile_wr_en;
        CData/*4:0*/ __Vsampled_TOP__tx_rx_tb__DOT__dut__DOT__regfile_wr_addr;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__regfile_wr_data;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__regfile_rd_data;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__lcr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__regfile_wr_data;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__regfile_rd_data;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__clk_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__thr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__dll_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__dlh_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__dlf_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__lcr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_data_latch;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT____Vtogcov__wr_data_latch;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__fcr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__rxthr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__timeout_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__ier_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__fcr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__mcr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__mode_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__rxthr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__txthr_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT____Vtogcov__timeout_val;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__u_fcr__DOT____Vtogcov__wr_data;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__divider_int;
    };
    struct {
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__count;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__effective_divider;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT____Vtogcov__divider_int;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT____Vtogcov__count;
        SData/*15:0*/ tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT____Vtogcov__effective_divider;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__parity_data_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT____Vtogcov__parity_data_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__u_parity__DOT__masked_data;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_tx__DOT__u_parity__DOT____Vtogcov__masked_data;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__rx_data;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__aligned_shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__rx_data;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT____Vtogcov__aligned_shift_reg;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__u_parity__DOT__masked_data;
        SData/*8:0*/ tx_rx_tb__DOT__dut__DOT__u_rx__DOT__u_parity__DOT____Vtogcov__masked_data;
        SData/*8:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT__captured_data;
        SData/*8:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_proto_chk__DOT____Vtogcov__captured_data;
        SData/*15:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__fcr_prev;
        SData/*15:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT__dll_before;
        SData/*15:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__fcr_prev;
        SData/*15:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT____Vtogcov__dll_before;
        SData/*15:0*/ tx_rx_tb__DOT__spec_suite__DOT__u_reg_chk__DOT___Vpast_2_0;
        SData/*15:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__fcr_val;
        SData/*15:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__lcr_val;
        SData/*15:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__rxthr_val;
        SData/*15:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_regfile__DOT__timeout_val;
        SData/*8:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_tx__DOT__shift_reg;
        SData/*8:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_rx__DOT__shift_reg;
        SData/*15:0*/ __Vdly__tx_rx_tb__DOT__dut__DOT__u_baud_gen__DOT__count;
        SData/*15:0*/ __Vsampled_TOP__tx_rx_tb__DOT__dut__DOT__regfile_wr_data;
        VL_IN(s_awaddr,31,0);
        VL_IN(s_wdata,31,0);
        VL_IN(s_araddr,31,0);
        VL_OUT(s_rdata,31,0);
        IData/*31:0*/ tx_rx_tb__DOT____Vtogcov__s_awaddr;
        IData/*31:0*/ tx_rx_tb__DOT____Vtogcov__s_wdata;
        IData/*31:0*/ tx_rx_tb__DOT____Vtogcov__s_araddr;
        IData/*31:0*/ tx_rx_tb__DOT____Vtogcov__s_rdata;
        IData/*20:0*/ tx_rx_tb__DOT__dut__DOT__fc_feature_manifest;
        IData/*20:0*/ tx_rx_tb__DOT__dut__DOT____Vtogcov__fc_feature_manifest;
        IData/*31:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT__wr_addr_latch;
        IData/*31:0*/ tx_rx_tb__DOT__dut__DOT__u_axi_slave__DOT____Vtogcov__wr_addr_latch;
        IData/*31:0*/ tx_rx_tb__DOT__spec_suite__DOT__total_pass_count;
        IData/*31:0*/ tx_rx_tb__DOT__spec_suite__DOT__total_fail_count;
        IData/*31:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__total_pass_count;
        IData/*31:0*/ tx_rx_tb__DOT__spec_suite__DOT____Vtogcov__total_fail_count;
        IData/*31:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__total_pass_count;
        IData/*31:0*/ __Vdly__tx_rx_tb__DOT__spec_suite__DOT__total_fail_count;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 6> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtx_rx_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtx_rx_tb___024root(Vtx_rx_tb__Syms* symsp, const char* v__name);
    ~Vtx_rx_tb___024root();
    VL_UNCOPYABLE(Vtx_rx_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
