//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// result                         O    32
// RDY_result                     O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// result_op                      I     4
// result_a                       I    32
// result_b                       I    32
//
// Combinational paths from inputs to outputs:
//   (result_op, result_a, result_b) -> result
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkALU(CLK,
	     RST_N,

	     result_op,
	     result_a,
	     result_b,
	     result,
	     RDY_result);
  input  CLK;
  input  RST_N;

  // value method result
  input  [3 : 0] result_op;
  input  [31 : 0] result_a;
  input  [31 : 0] result_b;
  output [31 : 0] result;
  output RDY_result;

  // signals for module outputs
  wire [31 : 0] result;
  wire RDY_result;

  // value method result
  module_alu instance_alu_0(.alu_op(result_op),
			    .alu_a(result_a),
			    .alu_b(result_b),
			    .alu(result));
  assign RDY_result = 1'd1 ;
endmodule  // mkALU

