//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// RDY_slave_aw_put               O     1 reg
// RDY_slave_w_put                O     1 reg
// slave_b_get                    O     2 reg
// RDY_slave_b_get                O     1 reg
// RDY_slave_ar_put               O     1 reg
// slave_r_get                    O    34 reg
// RDY_slave_r_get                O     1 reg
// RDY_initWord                   O     1 const
// peekWord                       O    32
// RDY_peekWord                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// slave_aw_put                   I    35 reg
// slave_w_put                    I    36 reg
// slave_ar_put                   I    35 reg
// initWord_wordIdx               I    32
// initWord_v                     I    32
// peekWord_wordIdx               I    32
// EN_slave_aw_put                I     1
// EN_slave_w_put                 I     1
// EN_slave_ar_put                I     1
// EN_initWord                    I     1
// EN_slave_b_get                 I     1
// EN_slave_r_get                 I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBramMem(CLK,
		 RST_N,

		 slave_aw_put,
		 EN_slave_aw_put,
		 RDY_slave_aw_put,

		 slave_w_put,
		 EN_slave_w_put,
		 RDY_slave_w_put,

		 EN_slave_b_get,
		 slave_b_get,
		 RDY_slave_b_get,

		 slave_ar_put,
		 EN_slave_ar_put,
		 RDY_slave_ar_put,

		 EN_slave_r_get,
		 slave_r_get,
		 RDY_slave_r_get,

		 initWord_wordIdx,
		 initWord_v,
		 EN_initWord,
		 RDY_initWord,

		 peekWord_wordIdx,
		 peekWord,
		 RDY_peekWord);
  input  CLK;
  input  RST_N;

  // action method slave_aw_put
  input  [34 : 0] slave_aw_put;
  input  EN_slave_aw_put;
  output RDY_slave_aw_put;

  // action method slave_w_put
  input  [35 : 0] slave_w_put;
  input  EN_slave_w_put;
  output RDY_slave_w_put;

  // actionvalue method slave_b_get
  input  EN_slave_b_get;
  output [1 : 0] slave_b_get;
  output RDY_slave_b_get;

  // action method slave_ar_put
  input  [34 : 0] slave_ar_put;
  input  EN_slave_ar_put;
  output RDY_slave_ar_put;

  // actionvalue method slave_r_get
  input  EN_slave_r_get;
  output [33 : 0] slave_r_get;
  output RDY_slave_r_get;

  // action method initWord
  input  [31 : 0] initWord_wordIdx;
  input  [31 : 0] initWord_v;
  input  EN_initWord;
  output RDY_initWord;

  // value method peekWord
  input  [31 : 0] peekWord_wordIdx;
  output [31 : 0] peekWord;
  output RDY_peekWord;

  // signals for module outputs
  wire [33 : 0] slave_r_get;
  wire [31 : 0] peekWord;
  wire [1 : 0] slave_b_get;
  wire RDY_initWord,
       RDY_peekWord,
       RDY_slave_ar_put,
       RDY_slave_aw_put,
       RDY_slave_b_get,
       RDY_slave_r_get,
       RDY_slave_w_put;

  // ports of submodule arf
  wire [34 : 0] arf$D_IN, arf$D_OUT;
  wire arf$CLR, arf$DEQ, arf$EMPTY_N, arf$ENQ, arf$FULL_N;

  // ports of submodule awf
  wire [34 : 0] awf$D_IN, awf$D_OUT;
  wire awf$CLR, awf$DEQ, awf$EMPTY_N, awf$ENQ, awf$FULL_N;

  // ports of submodule bf
  wire [1 : 0] bf$D_IN, bf$D_OUT;
  wire bf$CLR, bf$DEQ, bf$EMPTY_N, bf$ENQ, bf$FULL_N;

  // ports of submodule mem
  wire [31 : 0] mem$D_IN, mem$D_OUT_1, mem$D_OUT_2, mem$D_OUT_3;
  wire [13 : 0] mem$ADDR_1,
		mem$ADDR_2,
		mem$ADDR_3,
		mem$ADDR_4,
		mem$ADDR_5,
		mem$ADDR_IN;
  wire mem$WE;

  // ports of submodule rf
  wire [33 : 0] rf$D_IN, rf$D_OUT;
  wire rf$CLR, rf$DEQ, rf$EMPTY_N, rf$ENQ, rf$FULL_N;

  // ports of submodule wf
  wire [35 : 0] wf$D_IN, wf$D_OUT;
  wire wf$CLR, wf$DEQ, wf$EMPTY_N, wf$ENQ, wf$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_do_read,
       CAN_FIRE_RL_do_write,
       CAN_FIRE_initWord,
       CAN_FIRE_slave_ar_put,
       CAN_FIRE_slave_aw_put,
       CAN_FIRE_slave_b_get,
       CAN_FIRE_slave_r_get,
       CAN_FIRE_slave_w_put,
       WILL_FIRE_RL_do_read,
       WILL_FIRE_RL_do_write,
       WILL_FIRE_initWord,
       WILL_FIRE_slave_ar_put,
       WILL_FIRE_slave_aw_put,
       WILL_FIRE_slave_b_get,
       WILL_FIRE_slave_r_get,
       WILL_FIRE_slave_w_put;

  // inputs to muxes for submodule ports
  wire [31 : 0] MUX_mem$upd_2__VAL_1;

  // action method slave_aw_put
  assign RDY_slave_aw_put = awf$FULL_N ;
  assign CAN_FIRE_slave_aw_put = awf$FULL_N ;
  assign WILL_FIRE_slave_aw_put = EN_slave_aw_put ;

  // action method slave_w_put
  assign RDY_slave_w_put = wf$FULL_N ;
  assign CAN_FIRE_slave_w_put = wf$FULL_N ;
  assign WILL_FIRE_slave_w_put = EN_slave_w_put ;

  // actionvalue method slave_b_get
  assign slave_b_get = bf$D_OUT ;
  assign RDY_slave_b_get = bf$EMPTY_N ;
  assign CAN_FIRE_slave_b_get = bf$EMPTY_N ;
  assign WILL_FIRE_slave_b_get = EN_slave_b_get ;

  // action method slave_ar_put
  assign RDY_slave_ar_put = arf$FULL_N ;
  assign CAN_FIRE_slave_ar_put = arf$FULL_N ;
  assign WILL_FIRE_slave_ar_put = EN_slave_ar_put ;

  // actionvalue method slave_r_get
  assign slave_r_get = rf$D_OUT ;
  assign RDY_slave_r_get = rf$EMPTY_N ;
  assign CAN_FIRE_slave_r_get = rf$EMPTY_N ;
  assign WILL_FIRE_slave_r_get = EN_slave_r_get ;

  // action method initWord
  assign RDY_initWord = 1'd1 ;
  assign CAN_FIRE_initWord = 1'd1 ;
  assign WILL_FIRE_initWord = EN_initWord ;

  // value method peekWord
  assign peekWord = mem$D_OUT_1 ;
  assign RDY_peekWord = 1'd1 ;

  // submodule arf
  FIFO2 #(.width(32'd35), .guarded(1'd1)) arf(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(arf$D_IN),
					      .ENQ(arf$ENQ),
					      .DEQ(arf$DEQ),
					      .CLR(arf$CLR),
					      .D_OUT(arf$D_OUT),
					      .FULL_N(arf$FULL_N),
					      .EMPTY_N(arf$EMPTY_N));

  // submodule awf
  FIFO2 #(.width(32'd35), .guarded(1'd1)) awf(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(awf$D_IN),
					      .ENQ(awf$ENQ),
					      .DEQ(awf$DEQ),
					      .CLR(awf$CLR),
					      .D_OUT(awf$D_OUT),
					      .FULL_N(awf$FULL_N),
					      .EMPTY_N(awf$EMPTY_N));

  // submodule bf
  FIFO2 #(.width(32'd2), .guarded(1'd1)) bf(.RST(RST_N),
					    .CLK(CLK),
					    .D_IN(bf$D_IN),
					    .ENQ(bf$ENQ),
					    .DEQ(bf$DEQ),
					    .CLR(bf$CLR),
					    .D_OUT(bf$D_OUT),
					    .FULL_N(bf$FULL_N),
					    .EMPTY_N(bf$EMPTY_N));

  // submodule mem
  RegFile #(.addr_width(32'd14),
	    .data_width(32'd32),
	    .lo(14'h0),
	    .hi(14'd16383)) mem(.CLK(CLK),
				.ADDR_1(mem$ADDR_1),
				.ADDR_2(mem$ADDR_2),
				.ADDR_3(mem$ADDR_3),
				.ADDR_4(mem$ADDR_4),
				.ADDR_5(mem$ADDR_5),
				.ADDR_IN(mem$ADDR_IN),
				.D_IN(mem$D_IN),
				.WE(mem$WE),
				.D_OUT_1(mem$D_OUT_1),
				.D_OUT_2(mem$D_OUT_2),
				.D_OUT_3(mem$D_OUT_3),
				.D_OUT_4(),
				.D_OUT_5());

  // submodule rf
  FIFO2 #(.width(32'd34), .guarded(1'd1)) rf(.RST(RST_N),
					     .CLK(CLK),
					     .D_IN(rf$D_IN),
					     .ENQ(rf$ENQ),
					     .DEQ(rf$DEQ),
					     .CLR(rf$CLR),
					     .D_OUT(rf$D_OUT),
					     .FULL_N(rf$FULL_N),
					     .EMPTY_N(rf$EMPTY_N));

  // submodule wf
  FIFO2 #(.width(32'd36), .guarded(1'd1)) wf(.RST(RST_N),
					     .CLK(CLK),
					     .D_IN(wf$D_IN),
					     .ENQ(wf$ENQ),
					     .DEQ(wf$DEQ),
					     .CLR(wf$CLR),
					     .D_OUT(wf$D_OUT),
					     .FULL_N(wf$FULL_N),
					     .EMPTY_N(wf$EMPTY_N));

  // rule RL_do_read
  assign CAN_FIRE_RL_do_read = arf$EMPTY_N && rf$FULL_N ;
  assign WILL_FIRE_RL_do_read = CAN_FIRE_RL_do_read ;

  // rule RL_do_write
  assign CAN_FIRE_RL_do_write = awf$EMPTY_N && wf$EMPTY_N && bf$FULL_N ;
  assign WILL_FIRE_RL_do_write = CAN_FIRE_RL_do_write && !EN_initWord ;

  // inputs to muxes for submodule ports
  assign MUX_mem$upd_2__VAL_1 =
	     { wf$D_OUT[3] ? wf$D_OUT[35:28] : mem$D_OUT_3[31:24],
	       wf$D_OUT[2] ? wf$D_OUT[27:20] : mem$D_OUT_3[23:16],
	       wf$D_OUT[1] ? wf$D_OUT[19:12] : mem$D_OUT_3[15:8],
	       wf$D_OUT[0] ? wf$D_OUT[11:4] : mem$D_OUT_3[7:0] } ;

  // submodule arf
  assign arf$D_IN = slave_ar_put ;
  assign arf$ENQ = EN_slave_ar_put ;
  assign arf$DEQ = CAN_FIRE_RL_do_read ;
  assign arf$CLR = 1'b0 ;

  // submodule awf
  assign awf$D_IN = slave_aw_put ;
  assign awf$ENQ = EN_slave_aw_put ;
  assign awf$DEQ = WILL_FIRE_RL_do_write ;
  assign awf$CLR = 1'b0 ;

  // submodule bf
  assign bf$D_IN = 2'b0 ;
  assign bf$ENQ = WILL_FIRE_RL_do_write ;
  assign bf$DEQ = EN_slave_b_get ;
  assign bf$CLR = 1'b0 ;

  // submodule mem
  assign mem$ADDR_1 = peekWord_wordIdx[13:0] ;
  assign mem$ADDR_2 = arf$D_OUT[18:5] ;
  assign mem$ADDR_3 = awf$D_OUT[18:5] ;
  assign mem$ADDR_4 = 14'h0 ;
  assign mem$ADDR_5 = 14'h0 ;
  assign mem$ADDR_IN =
	     WILL_FIRE_RL_do_write ?
	       awf$D_OUT[18:5] :
	       initWord_wordIdx[13:0] ;
  assign mem$D_IN =
	     WILL_FIRE_RL_do_write ? MUX_mem$upd_2__VAL_1 : initWord_v ;
  assign mem$WE = WILL_FIRE_RL_do_write || EN_initWord ;

  // submodule rf
  assign rf$D_IN = { mem$D_OUT_2, 2'b0 } ;
  assign rf$ENQ = CAN_FIRE_RL_do_read ;
  assign rf$DEQ = EN_slave_r_get ;
  assign rf$CLR = 1'b0 ;

  // submodule wf
  assign wf$D_IN = slave_w_put ;
  assign wf$ENQ = EN_slave_w_put ;
  assign wf$DEQ = WILL_FIRE_RL_do_write ;
  assign wf$CLR = 1'b0 ;
endmodule  // mkBramMem

