//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
//
//
// Ports:
// Name                         I/O  size props
// imem_aw_get                    O    35 reg
// RDY_imem_aw_get                O     1 reg
// imem_w_get                     O    36 reg
// RDY_imem_w_get                 O     1 reg
// RDY_imem_b_put                 O     1 reg
// imem_ar_get                    O    35 reg
// RDY_imem_ar_get                O     1 reg
// RDY_imem_r_put                 O     1 reg
// dmem_aw_get                    O    35 reg
// RDY_dmem_aw_get                O     1 reg
// dmem_w_get                     O    36 reg
// RDY_dmem_w_get                 O     1 reg
// RDY_dmem_b_put                 O     1 reg
// dmem_ar_get                    O    35 reg
// RDY_dmem_ar_get                O     1 reg
// RDY_dmem_r_put                 O     1 reg
// RDY_reqHalt                    O     1 const
// RDY_reqStep                    O     1 const
// isHalted                       O     1 reg
// RDY_isHalted                   O     1 const
// dbgGprRead                     O    32
// RDY_dbgGprRead                 O     1 const
// RDY_dbgGprWrite                O     1 const
// dbgPc                          O    32 reg
// RDY_dbgPc                      O     1 const
// RDY_dbgSetPc                   O     1 const
// retired                        O     1 reg
// RDY_retired                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// imem_b_put                     I     2 reg
// imem_r_put                     I    34 reg
// dmem_b_put                     I     2 reg
// dmem_r_put                     I    34 reg
// reqHalt_h                      I     1
// dbgGprRead_r                   I     5
// dbgGprWrite_r                  I     5
// dbgGprWrite_v                  I    32
// dbgSetPc_a                     I    32
// EN_imem_b_put                  I     1
// EN_imem_r_put                  I     1
// EN_dmem_b_put                  I     1
// EN_dmem_r_put                  I     1
// EN_reqHalt                     I     1
// EN_reqStep                     I     1
// EN_dbgGprWrite                 I     1
// EN_dbgSetPc                    I     1
// EN_imem_aw_get                 I     1
// EN_imem_w_get                  I     1
// EN_imem_ar_get                 I     1
// EN_dmem_aw_get                 I     1
// EN_dmem_w_get                  I     1
// EN_dmem_ar_get                 I     1
//
// Combinational paths from inputs to outputs:
//   dbgGprRead_r -> dbgGprRead
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCore(CLK,
	      RST_N,

	      EN_imem_aw_get,
	      imem_aw_get,
	      RDY_imem_aw_get,

	      EN_imem_w_get,
	      imem_w_get,
	      RDY_imem_w_get,

	      imem_b_put,
	      EN_imem_b_put,
	      RDY_imem_b_put,

	      EN_imem_ar_get,
	      imem_ar_get,
	      RDY_imem_ar_get,

	      imem_r_put,
	      EN_imem_r_put,
	      RDY_imem_r_put,

	      EN_dmem_aw_get,
	      dmem_aw_get,
	      RDY_dmem_aw_get,

	      EN_dmem_w_get,
	      dmem_w_get,
	      RDY_dmem_w_get,

	      dmem_b_put,
	      EN_dmem_b_put,
	      RDY_dmem_b_put,

	      EN_dmem_ar_get,
	      dmem_ar_get,
	      RDY_dmem_ar_get,

	      dmem_r_put,
	      EN_dmem_r_put,
	      RDY_dmem_r_put,

	      reqHalt_h,
	      EN_reqHalt,
	      RDY_reqHalt,

	      EN_reqStep,
	      RDY_reqStep,

	      isHalted,
	      RDY_isHalted,

	      dbgGprRead_r,
	      dbgGprRead,
	      RDY_dbgGprRead,

	      dbgGprWrite_r,
	      dbgGprWrite_v,
	      EN_dbgGprWrite,
	      RDY_dbgGprWrite,

	      dbgPc,
	      RDY_dbgPc,

	      dbgSetPc_a,
	      EN_dbgSetPc,
	      RDY_dbgSetPc,

	      retired,
	      RDY_retired);
  input  CLK;
  input  RST_N;

  // actionvalue method imem_aw_get
  input  EN_imem_aw_get;
  output [34 : 0] imem_aw_get;
  output RDY_imem_aw_get;

  // actionvalue method imem_w_get
  input  EN_imem_w_get;
  output [35 : 0] imem_w_get;
  output RDY_imem_w_get;

  // action method imem_b_put
  input  [1 : 0] imem_b_put;
  input  EN_imem_b_put;
  output RDY_imem_b_put;

  // actionvalue method imem_ar_get
  input  EN_imem_ar_get;
  output [34 : 0] imem_ar_get;
  output RDY_imem_ar_get;

  // action method imem_r_put
  input  [33 : 0] imem_r_put;
  input  EN_imem_r_put;
  output RDY_imem_r_put;

  // actionvalue method dmem_aw_get
  input  EN_dmem_aw_get;
  output [34 : 0] dmem_aw_get;
  output RDY_dmem_aw_get;

  // actionvalue method dmem_w_get
  input  EN_dmem_w_get;
  output [35 : 0] dmem_w_get;
  output RDY_dmem_w_get;

  // action method dmem_b_put
  input  [1 : 0] dmem_b_put;
  input  EN_dmem_b_put;
  output RDY_dmem_b_put;

  // actionvalue method dmem_ar_get
  input  EN_dmem_ar_get;
  output [34 : 0] dmem_ar_get;
  output RDY_dmem_ar_get;

  // action method dmem_r_put
  input  [33 : 0] dmem_r_put;
  input  EN_dmem_r_put;
  output RDY_dmem_r_put;

  // action method reqHalt
  input  reqHalt_h;
  input  EN_reqHalt;
  output RDY_reqHalt;

  // action method reqStep
  input  EN_reqStep;
  output RDY_reqStep;

  // value method isHalted
  output isHalted;
  output RDY_isHalted;

  // value method dbgGprRead
  input  [4 : 0] dbgGprRead_r;
  output [31 : 0] dbgGprRead;
  output RDY_dbgGprRead;

  // action method dbgGprWrite
  input  [4 : 0] dbgGprWrite_r;
  input  [31 : 0] dbgGprWrite_v;
  input  EN_dbgGprWrite;
  output RDY_dbgGprWrite;

  // value method dbgPc
  output [31 : 0] dbgPc;
  output RDY_dbgPc;

  // action method dbgSetPc
  input  [31 : 0] dbgSetPc_a;
  input  EN_dbgSetPc;
  output RDY_dbgSetPc;

  // value method retired
  output retired;
  output RDY_retired;

  // signals for module outputs
  wire [35 : 0] dmem_w_get, imem_w_get;
  wire [34 : 0] dmem_ar_get, dmem_aw_get, imem_ar_get, imem_aw_get;
  wire [31 : 0] dbgGprRead, dbgPc;
  wire RDY_dbgGprRead,
       RDY_dbgGprWrite,
       RDY_dbgPc,
       RDY_dbgSetPc,
       RDY_dmem_ar_get,
       RDY_dmem_aw_get,
       RDY_dmem_b_put,
       RDY_dmem_r_put,
       RDY_dmem_w_get,
       RDY_imem_ar_get,
       RDY_imem_aw_get,
       RDY_imem_b_put,
       RDY_imem_r_put,
       RDY_imem_w_get,
       RDY_isHalted,
       RDY_reqHalt,
       RDY_reqStep,
       RDY_retired,
       isHalted,
       retired;

  // inlined wires
  wire [271 : 0] idex_w_1$wget;
  wire [232 : 0] exmem_w_0$wget;
  wire [132 : 0] ifid_w_1$wget;
  wire exmem_w_1$whas,
       exmem_w_2$whas,
       haltedE_w_0$whas,
       haltedE_w_2$whas,
       idex_w_0$whas,
       ifid_w_0$whas,
       ifid_w_1$whas,
       redirectEx$whas,
       retireW$wget,
       stepReqE_w_1$whas,
       wbDoneE_w_0$whas,
       wbDoneE_w_1$whas;

  // register exmem_r
  reg [232 : 0] exmem_r;
  wire [232 : 0] exmem_r$D_IN;
  wire exmem_r$EN;

  // register fetchDrop
  reg fetchDrop;
  wire fetchDrop$D_IN, fetchDrop$EN;

  // register fetchPc
  reg [31 : 0] fetchPc;
  wire [31 : 0] fetchPc$D_IN;
  wire fetchPc$EN;

  // register fetchPending
  reg fetchPending;
  wire fetchPending$D_IN, fetchPending$EN;

  // register haltReqE_r
  reg haltReqE_r;
  wire haltReqE_r$D_IN, haltReqE_r$EN;

  // register haltedE_r
  reg haltedE_r;
  wire haltedE_r$D_IN, haltedE_r$EN;

  // register idex_r
  reg [271 : 0] idex_r;
  wire [271 : 0] idex_r$D_IN;
  wire idex_r$EN;

  // register ifid_r
  reg [132 : 0] ifid_r;
  wire [132 : 0] ifid_r$D_IN;
  wire ifid_r$EN;

  // register mdInFlight
  reg mdInFlight;
  wire mdInFlight$D_IN, mdInFlight$EN;

  // register memCur
  reg [232 : 0] memCur;
  wire [232 : 0] memCur$D_IN;
  wire memCur$EN;

  // register memPending
  reg memPending;
  wire memPending$D_IN, memPending$EN;

  // register memwb
  reg [168 : 0] memwb;
  wire [168 : 0] memwb$D_IN;
  wire memwb$EN;

  // register retiredReg
  reg retiredReg;
  wire retiredReg$D_IN, retiredReg$EN;

  // register stepArmedE_r
  reg stepArmedE_r;
  wire stepArmedE_r$D_IN, stepArmedE_r$EN;

  // register stepReqE_r
  reg stepReqE_r;
  wire stepReqE_r$D_IN, stepReqE_r$EN;

  // register wbDoneE_r
  reg wbDoneE_r;
  wire wbDoneE_r$D_IN, wbDoneE_r$EN;

  // ports of submodule csr
  reg [31 : 0] csr$csrWrite_v;
  wire [31 : 0] csr$csrRead, csr$mret, csr$trap, csr$trap_epc, csr$trap_tval;
  wire [11 : 0] csr$csrLegal_addr,
		csr$csrRead_addr,
		csr$csrWrite_addr,
		csr$dbgRead_addr;
  wire [2 : 0] csr$trap_cause;
  wire csr$EN_csrWrite,
       csr$EN_mret,
       csr$EN_tick,
       csr$EN_trap,
       csr$csrLegal,
       csr$tick_retired;

  // ports of submodule dmemP
  wire [68 : 0] dmemP$req_r;
  wire [35 : 0] dmemP$axi_w_get;
  wire [34 : 0] dmemP$axi_ar_get, dmemP$axi_aw_get;
  wire [33 : 0] dmemP$axi_r_put;
  wire [31 : 0] dmemP$resp;
  wire [1 : 0] dmemP$axi_b_put;
  wire dmemP$EN_axi_ar_get,
       dmemP$EN_axi_aw_get,
       dmemP$EN_axi_b_put,
       dmemP$EN_axi_r_put,
       dmemP$EN_axi_w_get,
       dmemP$EN_req,
       dmemP$EN_resp,
       dmemP$RDY_axi_ar_get,
       dmemP$RDY_axi_aw_get,
       dmemP$RDY_axi_b_put,
       dmemP$RDY_axi_r_put,
       dmemP$RDY_axi_w_get,
       dmemP$RDY_req,
       dmemP$RDY_resp,
       dmemP$canReq;

  // ports of submodule imemP
  wire [35 : 0] imemP$axi_w_get;
  wire [34 : 0] imemP$axi_ar_get, imemP$axi_aw_get;
  wire [33 : 0] imemP$axi_r_put;
  wire [31 : 0] imemP$fetch_pc, imemP$instr;
  wire [1 : 0] imemP$axi_b_put;
  wire imemP$EN_axi_ar_get,
       imemP$EN_axi_aw_get,
       imemP$EN_axi_b_put,
       imemP$EN_axi_r_put,
       imemP$EN_axi_w_get,
       imemP$EN_fetch,
       imemP$EN_instr,
       imemP$RDY_axi_ar_get,
       imemP$RDY_axi_aw_get,
       imemP$RDY_axi_b_put,
       imemP$RDY_axi_r_put,
       imemP$RDY_axi_w_get,
       imemP$RDY_fetch,
       imemP$RDY_instr,
       imemP$canFetch,
       imemP$instrReady;

  // ports of submodule md
  wire [31 : 0] md$result, md$start_a, md$start_b;
  wire [2 : 0] md$start_op;
  wire md$EN_start, md$RDY_start, md$done;

  // ports of submodule pcu
  wire [31 : 0] pcu$advance_nxt, pcu$dbgSet_v, pcu$pc, pcu$redirect_tgt;
  wire pcu$EN_advance, pcu$EN_dbgSet, pcu$EN_redirect;

  // ports of submodule rf
  wire [31 : 0] rf$dbgRead, rf$dbgWrite_d, rf$read1, rf$read2, rf$write_d;
  wire [4 : 0] rf$dbgRead_a,
	       rf$dbgWrite_a,
	       rf$read1_a,
	       rf$read2_a,
	       rf$write_a;
  wire rf$EN_dbgWrite, rf$EN_write;

  // rule scheduling signals
  wire CAN_FIRE_RL_do_ex,
       CAN_FIRE_RL_do_id,
       CAN_FIRE_RL_do_if,
       CAN_FIRE_RL_do_mem,
       CAN_FIRE_RL_do_wb,
       CAN_FIRE_RL_exmem_canonicalize,
       CAN_FIRE_RL_haltReqE_canonicalize,
       CAN_FIRE_RL_haltedE_canonicalize,
       CAN_FIRE_RL_idex_canonicalize,
       CAN_FIRE_RL_ifid_canonicalize,
       CAN_FIRE_RL_latchRetire,
       CAN_FIRE_RL_manageHalt,
       CAN_FIRE_RL_stepArmedE_canonicalize,
       CAN_FIRE_RL_stepReqE_canonicalize,
       CAN_FIRE_RL_tickCounters,
       CAN_FIRE_RL_wbDoneE_canonicalize,
       CAN_FIRE_dbgGprWrite,
       CAN_FIRE_dbgSetPc,
       CAN_FIRE_dmem_ar_get,
       CAN_FIRE_dmem_aw_get,
       CAN_FIRE_dmem_b_put,
       CAN_FIRE_dmem_r_put,
       CAN_FIRE_dmem_w_get,
       CAN_FIRE_imem_ar_get,
       CAN_FIRE_imem_aw_get,
       CAN_FIRE_imem_b_put,
       CAN_FIRE_imem_r_put,
       CAN_FIRE_imem_w_get,
       CAN_FIRE_reqHalt,
       CAN_FIRE_reqStep,
       WILL_FIRE_RL_do_ex,
       WILL_FIRE_RL_do_id,
       WILL_FIRE_RL_do_if,
       WILL_FIRE_RL_do_mem,
       WILL_FIRE_RL_do_wb,
       WILL_FIRE_RL_exmem_canonicalize,
       WILL_FIRE_RL_haltReqE_canonicalize,
       WILL_FIRE_RL_haltedE_canonicalize,
       WILL_FIRE_RL_idex_canonicalize,
       WILL_FIRE_RL_ifid_canonicalize,
       WILL_FIRE_RL_latchRetire,
       WILL_FIRE_RL_manageHalt,
       WILL_FIRE_RL_stepArmedE_canonicalize,
       WILL_FIRE_RL_stepReqE_canonicalize,
       WILL_FIRE_RL_tickCounters,
       WILL_FIRE_RL_wbDoneE_canonicalize,
       WILL_FIRE_dbgGprWrite,
       WILL_FIRE_dbgSetPc,
       WILL_FIRE_dmem_ar_get,
       WILL_FIRE_dmem_aw_get,
       WILL_FIRE_dmem_b_put,
       WILL_FIRE_dmem_r_put,
       WILL_FIRE_dmem_w_get,
       WILL_FIRE_imem_ar_get,
       WILL_FIRE_imem_aw_get,
       WILL_FIRE_imem_b_put,
       WILL_FIRE_imem_r_put,
       WILL_FIRE_imem_w_get,
       WILL_FIRE_reqHalt,
       WILL_FIRE_reqStep;

  // remaining internal signals
  reg [35 : 0] IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d291;
  reg [31 : 0] CASE_control_68_BITS_2_TO_1_1_0_2_ifid_r_BITS__ETC__q2,
	       IF_memCur_86_BITS_181_TO_180_89_EQ_0_90_THEN_I_ETC___d218,
	       a__h13943,
	       b__h13944,
	       opA__h13946,
	       x__h14637;
  reg [7 : 0] b__h13205;
  reg [2 : 0] CASE_control_68_BITS_2_TO_1_1_5_2_2_ifid_r_BIT_ETC__q1;
  wire [232 : 0] IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_EL_ETC___d23;
  wire [167 : 0] IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d258,
		 IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d257,
		 IF_memPending_9_THEN_memCur_86_BITS_231_TO_169_ETC___d259;
  wire [131 : 0] rf_read1_decode_67_BITS_63_TO_59_69_70_CONCAT__ETC___d497;
  wire [75 : 0] decode___d467;
  wire [67 : 0] IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d421,
		IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d422;
  wire [63 : 0] IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d243;
  wire [32 : 0] branchJump___d449;
  wire [31 : 0] IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d403,
		IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d405,
		IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d404,
		IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d406,
		_read_di_imm__h2558,
		_read_instr__h1014,
		_read_pc__h1985,
		aluR__h13948,
		csrSrc__h13950,
		d__h12549,
		d__h12569,
		opB__h13947,
		v_aluOut__h4813,
		v_aluOut__h5022,
		v_pc__h4811,
		v_pc__h5020,
		v_rs2v__h4814,
		v_rs2v__h5023,
		x__h13194,
		x_wget__h9822,
		y__h14404;
  wire [30 : 0] IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d232,
		control___d468;
  wire [15 : 0] h__h13349;
  wire [4 : 0] _read_di_rs1__h2553,
	       _read_di_rs2__h2554,
	       _read_rd__h10243,
	       _read_rd__h4607,
	       v_rd__h4816,
	       v_rd__h5025,
	       x__h12590,
	       x__h12632;
  wire [3 : 0] forward___d382, s__h12550, s__h12570;
  wire [1 : 0] IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141,
	       x__h12696;
  wire IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d154,
       IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d265,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d111,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d119,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d127,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d135,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d160,
       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d177,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d134,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d166,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d168,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d170,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d183,
       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d271,
       IF_flushFront_whas__54_AND_flushFront_wget__55_ETC___d515,
       IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d47,
       IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d573,
       IF_haltedE_w_0_whas__6_THEN_haltedE_w_0_wget___ETC___d39,
       IF_memPending_9_THEN_IF_wbDoneE_w_0_whas__7_TH_ETC___d161,
       IF_stepArmedE_w_0_whas__8_THEN_stepArmedE_w_0__ETC___d61,
       IF_stepReqE_w_0_whas__1_THEN_stepReqE_w_0_wget_ETC___d54,
       IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101,
       IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30,
       NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359,
       NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d539,
       NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d543,
       NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d555,
       NOT_idex_r_2_BIT_271_95_96_OR_NOT_idex_r_2_BIT_ETC___d326,
       NOT_memPending_9_64_AND_IF_exmem_w_1_whas__7_T_ETC___d267,
       NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337,
       _dfoo1,
       exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d307,
       exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d309,
       fetchPending_01_AND_flushFront_whas__54_AND_fl_ETC___d545,
       flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d464,
       flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d523,
       idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d433,
       idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d452,
       idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d342,
       idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d428,
       imemP_instrReady__07_AND_IF_ifid_w_0_whas_THEN_ETC___d536,
       memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d317,
       memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d318;

  // actionvalue method imem_aw_get
  assign imem_aw_get = imemP$axi_aw_get ;
  assign RDY_imem_aw_get = imemP$RDY_axi_aw_get ;
  assign CAN_FIRE_imem_aw_get = imemP$RDY_axi_aw_get ;
  assign WILL_FIRE_imem_aw_get = EN_imem_aw_get ;

  // actionvalue method imem_w_get
  assign imem_w_get = imemP$axi_w_get ;
  assign RDY_imem_w_get = imemP$RDY_axi_w_get ;
  assign CAN_FIRE_imem_w_get = imemP$RDY_axi_w_get ;
  assign WILL_FIRE_imem_w_get = EN_imem_w_get ;

  // action method imem_b_put
  assign RDY_imem_b_put = imemP$RDY_axi_b_put ;
  assign CAN_FIRE_imem_b_put = imemP$RDY_axi_b_put ;
  assign WILL_FIRE_imem_b_put = EN_imem_b_put ;

  // actionvalue method imem_ar_get
  assign imem_ar_get = imemP$axi_ar_get ;
  assign RDY_imem_ar_get = imemP$RDY_axi_ar_get ;
  assign CAN_FIRE_imem_ar_get = imemP$RDY_axi_ar_get ;
  assign WILL_FIRE_imem_ar_get = EN_imem_ar_get ;

  // action method imem_r_put
  assign RDY_imem_r_put = imemP$RDY_axi_r_put ;
  assign CAN_FIRE_imem_r_put = imemP$RDY_axi_r_put ;
  assign WILL_FIRE_imem_r_put = EN_imem_r_put ;

  // actionvalue method dmem_aw_get
  assign dmem_aw_get = dmemP$axi_aw_get ;
  assign RDY_dmem_aw_get = dmemP$RDY_axi_aw_get ;
  assign CAN_FIRE_dmem_aw_get = dmemP$RDY_axi_aw_get ;
  assign WILL_FIRE_dmem_aw_get = EN_dmem_aw_get ;

  // actionvalue method dmem_w_get
  assign dmem_w_get = dmemP$axi_w_get ;
  assign RDY_dmem_w_get = dmemP$RDY_axi_w_get ;
  assign CAN_FIRE_dmem_w_get = dmemP$RDY_axi_w_get ;
  assign WILL_FIRE_dmem_w_get = EN_dmem_w_get ;

  // action method dmem_b_put
  assign RDY_dmem_b_put = dmemP$RDY_axi_b_put ;
  assign CAN_FIRE_dmem_b_put = dmemP$RDY_axi_b_put ;
  assign WILL_FIRE_dmem_b_put = EN_dmem_b_put ;

  // actionvalue method dmem_ar_get
  assign dmem_ar_get = dmemP$axi_ar_get ;
  assign RDY_dmem_ar_get = dmemP$RDY_axi_ar_get ;
  assign CAN_FIRE_dmem_ar_get = dmemP$RDY_axi_ar_get ;
  assign WILL_FIRE_dmem_ar_get = EN_dmem_ar_get ;

  // action method dmem_r_put
  assign RDY_dmem_r_put = dmemP$RDY_axi_r_put ;
  assign CAN_FIRE_dmem_r_put = dmemP$RDY_axi_r_put ;
  assign WILL_FIRE_dmem_r_put = EN_dmem_r_put ;

  // action method reqHalt
  assign RDY_reqHalt = 1'd1 ;
  assign CAN_FIRE_reqHalt = 1'd1 ;
  assign WILL_FIRE_reqHalt = EN_reqHalt ;

  // action method reqStep
  assign RDY_reqStep = 1'd1 ;
  assign CAN_FIRE_reqStep = 1'd1 ;
  assign WILL_FIRE_reqStep = EN_reqStep ;

  // value method isHalted
  assign isHalted = haltedE_r ;
  assign RDY_isHalted = 1'd1 ;

  // value method dbgGprRead
  assign dbgGprRead = rf$dbgRead ;
  assign RDY_dbgGprRead = 1'd1 ;

  // action method dbgGprWrite
  assign RDY_dbgGprWrite = 1'd1 ;
  assign CAN_FIRE_dbgGprWrite = 1'd1 ;
  assign WILL_FIRE_dbgGprWrite = EN_dbgGprWrite ;

  // value method dbgPc
  assign dbgPc = pcu$pc ;
  assign RDY_dbgPc = 1'd1 ;

  // action method dbgSetPc
  assign RDY_dbgSetPc = 1'd1 ;
  assign CAN_FIRE_dbgSetPc = 1'd1 ;
  assign WILL_FIRE_dbgSetPc = EN_dbgSetPc ;

  // value method retired
  assign retired = retiredReg ;
  assign RDY_retired = 1'd1 ;

  // submodule csr
  mkCSRFile csr(.CLK(CLK),
		.RST_N(RST_N),
		.csrLegal_addr(csr$csrLegal_addr),
		.csrRead_addr(csr$csrRead_addr),
		.csrWrite_addr(csr$csrWrite_addr),
		.csrWrite_v(csr$csrWrite_v),
		.dbgRead_addr(csr$dbgRead_addr),
		.tick_retired(csr$tick_retired),
		.trap_cause(csr$trap_cause),
		.trap_epc(csr$trap_epc),
		.trap_tval(csr$trap_tval),
		.EN_csrWrite(csr$EN_csrWrite),
		.EN_trap(csr$EN_trap),
		.EN_mret(csr$EN_mret),
		.EN_tick(csr$EN_tick),
		.csrRead(csr$csrRead),
		.RDY_csrRead(),
		.csrLegal(csr$csrLegal),
		.RDY_csrLegal(),
		.RDY_csrWrite(),
		.trap(csr$trap),
		.RDY_trap(),
		.mret(csr$mret),
		.RDY_mret(),
		.RDY_tick(),
		.dbgRead(),
		.RDY_dbgRead());

  // submodule dmemP
  mkMemPort dmemP(.CLK(CLK),
		  .RST_N(RST_N),
		  .axi_b_put(dmemP$axi_b_put),
		  .axi_r_put(dmemP$axi_r_put),
		  .req_r(dmemP$req_r),
		  .EN_req(dmemP$EN_req),
		  .EN_resp(dmemP$EN_resp),
		  .EN_axi_aw_get(dmemP$EN_axi_aw_get),
		  .EN_axi_w_get(dmemP$EN_axi_w_get),
		  .EN_axi_b_put(dmemP$EN_axi_b_put),
		  .EN_axi_ar_get(dmemP$EN_axi_ar_get),
		  .EN_axi_r_put(dmemP$EN_axi_r_put),
		  .RDY_req(dmemP$RDY_req),
		  .resp(dmemP$resp),
		  .RDY_resp(dmemP$RDY_resp),
		  .canReq(dmemP$canReq),
		  .RDY_canReq(),
		  .respReady(),
		  .RDY_respReady(),
		  .axi_aw_get(dmemP$axi_aw_get),
		  .RDY_axi_aw_get(dmemP$RDY_axi_aw_get),
		  .axi_w_get(dmemP$axi_w_get),
		  .RDY_axi_w_get(dmemP$RDY_axi_w_get),
		  .RDY_axi_b_put(dmemP$RDY_axi_b_put),
		  .axi_ar_get(dmemP$axi_ar_get),
		  .RDY_axi_ar_get(dmemP$RDY_axi_ar_get),
		  .RDY_axi_r_put(dmemP$RDY_axi_r_put));

  // submodule imemP
  mkInstMem imemP(.CLK(CLK),
		  .RST_N(RST_N),
		  .axi_b_put(imemP$axi_b_put),
		  .axi_r_put(imemP$axi_r_put),
		  .fetch_pc(imemP$fetch_pc),
		  .EN_fetch(imemP$EN_fetch),
		  .EN_instr(imemP$EN_instr),
		  .EN_axi_aw_get(imemP$EN_axi_aw_get),
		  .EN_axi_w_get(imemP$EN_axi_w_get),
		  .EN_axi_b_put(imemP$EN_axi_b_put),
		  .EN_axi_ar_get(imemP$EN_axi_ar_get),
		  .EN_axi_r_put(imemP$EN_axi_r_put),
		  .RDY_fetch(imemP$RDY_fetch),
		  .instr(imemP$instr),
		  .RDY_instr(imemP$RDY_instr),
		  .canFetch(imemP$canFetch),
		  .RDY_canFetch(),
		  .instrReady(imemP$instrReady),
		  .RDY_instrReady(),
		  .axi_aw_get(imemP$axi_aw_get),
		  .RDY_axi_aw_get(imemP$RDY_axi_aw_get),
		  .axi_w_get(imemP$axi_w_get),
		  .RDY_axi_w_get(imemP$RDY_axi_w_get),
		  .RDY_axi_b_put(imemP$RDY_axi_b_put),
		  .axi_ar_get(imemP$axi_ar_get),
		  .RDY_axi_ar_get(imemP$RDY_axi_ar_get),
		  .RDY_axi_r_put(imemP$RDY_axi_r_put));

  // submodule md
  mkMulDiv md(.CLK(CLK),
	      .RST_N(RST_N),
	      .start_a(md$start_a),
	      .start_b(md$start_b),
	      .start_op(md$start_op),
	      .EN_start(md$EN_start),
	      .RDY_start(md$RDY_start),
	      .busy(),
	      .RDY_busy(),
	      .done(md$done),
	      .RDY_done(),
	      .result(md$result),
	      .RDY_result());

  // submodule pcu
  mkProgramCounter pcu(.CLK(CLK),
		       .RST_N(RST_N),
		       .advance_nxt(pcu$advance_nxt),
		       .dbgSet_v(pcu$dbgSet_v),
		       .redirect_tgt(pcu$redirect_tgt),
		       .EN_advance(pcu$EN_advance),
		       .EN_redirect(pcu$EN_redirect),
		       .EN_dbgSet(pcu$EN_dbgSet),
		       .pc(pcu$pc),
		       .RDY_pc(),
		       .RDY_advance(),
		       .RDY_redirect(),
		       .RDY_dbgSet());

  // submodule rf
  mkRegFile rf(.CLK(CLK),
	       .RST_N(RST_N),
	       .dbgRead_a(rf$dbgRead_a),
	       .dbgWrite_a(rf$dbgWrite_a),
	       .dbgWrite_d(rf$dbgWrite_d),
	       .read1_a(rf$read1_a),
	       .read2_a(rf$read2_a),
	       .write_a(rf$write_a),
	       .write_d(rf$write_d),
	       .EN_write(rf$EN_write),
	       .EN_dbgWrite(rf$EN_dbgWrite),
	       .read1(rf$read1),
	       .RDY_read1(),
	       .read2(rf$read2),
	       .RDY_read2(),
	       .RDY_write(),
	       .dbgRead(rf$dbgRead),
	       .RDY_dbgRead(),
	       .RDY_dbgWrite());

  // rule RL_tickCounters
  assign CAN_FIRE_RL_tickCounters = !haltedE_r || stepArmedE_r || retiredReg ;
  assign WILL_FIRE_RL_tickCounters = CAN_FIRE_RL_tickCounters ;

  // rule RL_manageHalt
  assign CAN_FIRE_RL_manageHalt = 1'd1 ;
  assign WILL_FIRE_RL_manageHalt = 1'd1 ;

  // rule RL_do_ex
  assign CAN_FIRE_RL_do_ex =
	     NOT_idex_r_2_BIT_271_95_96_OR_NOT_idex_r_2_BIT_ETC___d326 &&
	     (!haltedE_r || stepArmedE_r) ;
  assign WILL_FIRE_RL_do_ex = CAN_FIRE_RL_do_ex ;

  // rule RL_do_wb
  assign CAN_FIRE_RL_do_wb = !haltedE_r || stepArmedE_r ;
  assign WILL_FIRE_RL_do_wb = CAN_FIRE_RL_do_wb ;

  // rule RL_latchRetire
  assign CAN_FIRE_RL_latchRetire = 1'd1 ;
  assign WILL_FIRE_RL_latchRetire = 1'd1 ;

  // rule RL_do_mem
  assign CAN_FIRE_RL_do_mem =
	     IF_memPending_9_THEN_IF_wbDoneE_w_0_whas__7_TH_ETC___d161 &&
	     (!haltedE_r || stepArmedE_r) ;
  assign WILL_FIRE_RL_do_mem = CAN_FIRE_RL_do_mem ;

  // rule RL_do_id
  assign CAN_FIRE_RL_do_id = CAN_FIRE_RL_do_wb ;
  assign WILL_FIRE_RL_do_id = CAN_FIRE_RL_do_wb ;

  // rule RL_do_if
  assign CAN_FIRE_RL_do_if =
	     (fetchPending ?
		IF_flushFront_whas__54_AND_flushFront_wget__55_ETC___d515 :
		redirectEx$whas || exmem_w_1$whas || redirectEx$whas ||
		!imemP$canFetch ||
		imemP$RDY_fetch) &&
	     (!haltedE_r || stepArmedE_r) ;
  assign WILL_FIRE_RL_do_if = CAN_FIRE_RL_do_if ;

  // rule RL_ifid_canonicalize
  assign CAN_FIRE_RL_ifid_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_ifid_canonicalize = 1'd1 ;

  // rule RL_idex_canonicalize
  assign CAN_FIRE_RL_idex_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_idex_canonicalize = 1'd1 ;

  // rule RL_exmem_canonicalize
  assign CAN_FIRE_RL_exmem_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_exmem_canonicalize = 1'd1 ;

  // rule RL_wbDoneE_canonicalize
  assign CAN_FIRE_RL_wbDoneE_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_wbDoneE_canonicalize = 1'd1 ;

  // rule RL_haltedE_canonicalize
  assign CAN_FIRE_RL_haltedE_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_haltedE_canonicalize = 1'd1 ;

  // rule RL_haltReqE_canonicalize
  assign CAN_FIRE_RL_haltReqE_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_haltReqE_canonicalize = 1'd1 ;

  // rule RL_stepReqE_canonicalize
  assign CAN_FIRE_RL_stepReqE_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_stepReqE_canonicalize = 1'd1 ;

  // rule RL_stepArmedE_canonicalize
  assign CAN_FIRE_RL_stepArmedE_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_stepArmedE_canonicalize = 1'd1 ;

  // inlined wires
  assign ifid_w_0$whas =
	     WILL_FIRE_RL_do_id &&
	     flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d464 ;
  assign ifid_w_1$wget =
	     { 1'd1,
	       fetchPc,
	       imemP$instr,
	       fetchPc[1:0] != 2'd0,
	       (fetchPc[1:0] == 2'd0) ?
		 67'h10000000000000000 :
		 { 3'd0, fetchPc, fetchPc } } ;
  assign ifid_w_1$whas =
	     WILL_FIRE_RL_do_if && fetchPending &&
	     NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d555 ;
  assign idex_w_0$whas =
	     WILL_FIRE_RL_do_ex &&
	     (idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d342 ||
	      idex_r[271] &&
	      (!idex_r[150] && !exmem_r[232] &&
	       NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 ||
	       idex_r[150] && idex_r[67] && !exmem_r[232])) ;
  assign idex_w_1$wget =
	     (redirectEx$whas || exmem_w_1$whas) ?
	       272'h00000000000000000000000000000001000000000000000000010000000000000000 :
	       { 1'd1,
		 ifid_r[131:100],
		 decode___d467,
		 control___d468,
		 rf_read1_decode_67_BITS_63_TO_59_69_70_CONCAT__ETC___d497 } ;
  assign exmem_w_0$wget =
	     { 1'd1,
	       idex_r[270:239],
	       idex_r[162:132],
	       IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d404,
	       b__h13944,
	       IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d406,
	       idex_r[231:227],
	       IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d422 } ;
  assign exmem_w_1$whas =
	     WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r &&
	     (memwb[67] || memwb[107:106] == 2'd3) ;
  assign exmem_w_2$whas =
	     WILL_FIRE_RL_do_mem && !memPending &&
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d271 ;
  assign wbDoneE_w_0$whas = WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r ;
  assign wbDoneE_w_1$whas =
	     WILL_FIRE_RL_do_mem &&
	     (memPending &&
	      IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ||
	      !memPending &&
	      IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d183) ;
  assign haltedE_w_0$whas = EN_reqHalt && !reqHalt_h ;
  assign haltedE_w_2$whas =
	     WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r && !memwb[67] &&
	     IF_stepArmedE_w_0_whas__8_THEN_stepArmedE_w_0__ETC___d61 ;
  assign stepReqE_w_1$whas =
	     IF_stepReqE_w_0_whas__1_THEN_stepReqE_w_0_wget_ETC___d54 &&
	     IF_haltedE_w_0_whas__6_THEN_haltedE_w_0_wget___ETC___d39 ;
  assign redirectEx$whas =
	     WILL_FIRE_RL_do_ex &&
	     idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d452 ;
  assign retireW$wget = memwb[168] && !wbDoneE_r && !memwb[67] ;

  // register exmem_r
  assign exmem_r$D_IN =
	     exmem_w_2$whas ?
	       233'h00000000000002000000000000000000000000000010000000000000000 :
	       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_EL_ETC___d23 ;
  assign exmem_r$EN = 1'd1 ;

  // register fetchDrop
  assign fetchDrop$D_IN =
	     redirectEx$whas || exmem_w_1$whas || redirectEx$whas ;
  assign fetchDrop$EN =
	     WILL_FIRE_RL_do_if && fetchPending &&
	     ((redirectEx$whas || exmem_w_1$whas || redirectEx$whas) &&
	      !imemP$instrReady ||
	      !redirectEx$whas && !exmem_w_1$whas && !redirectEx$whas &&
	      fetchDrop &&
	      imemP$instrReady) ;

  // register fetchPc
  assign fetchPc$D_IN = pcu$pc ;
  assign fetchPc$EN =
	     WILL_FIRE_RL_do_if && !fetchPending &&
	     NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d543 ;

  // register fetchPending
  assign fetchPending$D_IN = !fetchPending ;
  assign fetchPending$EN =
	     WILL_FIRE_RL_do_if &&
	     fetchPending_01_AND_flushFront_whas__54_AND_fl_ETC___d545 ;

  // register haltReqE_r
  assign haltReqE_r$D_IN =
	     IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d47 ;
  assign haltReqE_r$EN = 1'd1 ;

  // register haltedE_r
  assign haltedE_r$D_IN =
	     haltedE_w_2$whas ||
	     (_dfoo1 ?
		IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d573 :
		IF_haltedE_w_0_whas__6_THEN_haltedE_w_0_wget___ETC___d39) ;
  assign haltedE_r$EN = 1'd1 ;

  // register idex_r
  assign idex_r$D_IN =
	     ifid_w_0$whas ?
	       idex_w_1$wget :
	       (idex_w_0$whas ?
		  272'h00000000000000000000000000000001000000000000000000010000000000000000 :
		  idex_r) ;
  assign idex_r$EN = 1'd1 ;

  // register ifid_r
  assign ifid_r$D_IN =
	     ifid_w_1$whas ?
	       ifid_w_1$wget :
	       (ifid_w_0$whas ?
		  133'h0000000000000000010000000000000000 :
		  ifid_r) ;
  assign ifid_r$EN = 1'd1 ;

  // register mdInFlight
  assign mdInFlight$D_IN = !mdInFlight ;
  assign mdInFlight$EN =
	     WILL_FIRE_RL_do_ex &&
	     idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d428 ;

  // register memCur
  assign memCur$D_IN =
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_EL_ETC___d23 ;
  assign memCur$EN =
	     WILL_FIRE_RL_do_mem &&
	     NOT_memPending_9_64_AND_IF_exmem_w_1_whas__7_T_ETC___d267 ;

  // register memPending
  assign memPending$D_IN = !memPending ;
  assign memPending$EN =
	     WILL_FIRE_RL_do_mem &&
	     (memPending &&
	      IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ||
	      NOT_memPending_9_64_AND_IF_exmem_w_1_whas__7_T_ETC___d267) ;

  // register memwb
  assign memwb$D_IN =
	     { 1'd1,
	       IF_memPending_9_THEN_memCur_86_BITS_231_TO_169_ETC___d259 } ;
  assign memwb$EN = wbDoneE_w_1$whas ;

  // register retiredReg
  assign retiredReg$D_IN = CAN_FIRE_RL_do_wb && retireW$wget ;
  assign retiredReg$EN = 1'd1 ;

  // register stepArmedE_r
  assign stepArmedE_r$D_IN =
	     !haltedE_w_2$whas &&
	     IF_stepArmedE_w_0_whas__8_THEN_stepArmedE_w_0__ETC___d61 ;
  assign stepArmedE_r$EN = 1'd1 ;

  // register stepReqE_r
  assign stepReqE_r$D_IN =
	     !stepReqE_w_1$whas &&
	     IF_stepReqE_w_0_whas__1_THEN_stepReqE_w_0_wget_ETC___d54 ;
  assign stepReqE_r$EN = 1'd1 ;

  // register wbDoneE_r
  assign wbDoneE_r$D_IN =
	     !wbDoneE_w_1$whas &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ;
  assign wbDoneE_r$EN = 1'd1 ;

  // submodule csr
  assign csr$csrLegal_addr = idex_r[206:195] ;
  assign csr$csrRead_addr = idex_r[206:195] ;
  assign csr$csrWrite_addr = idex_r[206:195] ;
  always@(idex_r or csr$csrRead or csrSrc__h13950 or y__h14404)
  begin
    case (idex_r[137:136])
      2'd0: csr$csrWrite_v = csr$csrRead;
      2'd1: csr$csrWrite_v = csrSrc__h13950;
      2'd2: csr$csrWrite_v = csr$csrRead | csrSrc__h13950;
      2'd3: csr$csrWrite_v = csr$csrRead & y__h14404;
    endcase
  end
  assign csr$dbgRead_addr = 12'h0 ;
  assign csr$tick_retired = retiredReg ;
  assign csr$trap_cause = memwb[66:64] ;
  assign csr$trap_epc = memwb[63:32] ;
  assign csr$trap_tval = memwb[31:0] ;
  assign csr$EN_csrWrite =
	     WILL_FIRE_RL_do_ex &&
	     idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d433 ;
  assign csr$EN_trap =
	     WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r && memwb[67] ;
  assign csr$EN_mret =
	     WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r && !memwb[67] &&
	     memwb[107:106] == 2'd3 ;
  assign csr$EN_tick = CAN_FIRE_RL_tickCounters ;

  // submodule dmemP
  assign dmemP$axi_b_put = dmem_b_put ;
  assign dmemP$axi_r_put = dmem_r_put ;
  assign dmemP$req_r =
	     { v_aluOut__h5022,
	       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d170 ?
		 { 1'd1,
		   IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d291 } :
		 37'd0 } ;
  assign dmemP$EN_req =
	     WILL_FIRE_RL_do_mem &&
	     NOT_memPending_9_64_AND_IF_exmem_w_1_whas__7_T_ETC___d267 ;
  assign dmemP$EN_resp =
	     WILL_FIRE_RL_do_mem && memPending &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ;
  assign dmemP$EN_axi_aw_get = EN_dmem_aw_get ;
  assign dmemP$EN_axi_w_get = EN_dmem_w_get ;
  assign dmemP$EN_axi_b_put = EN_dmem_b_put ;
  assign dmemP$EN_axi_ar_get = EN_dmem_ar_get ;
  assign dmemP$EN_axi_r_put = EN_dmem_r_put ;

  // submodule imemP
  assign imemP$axi_b_put = imem_b_put ;
  assign imemP$axi_r_put = imem_r_put ;
  assign imemP$fetch_pc = pcu$pc ;
  assign imemP$EN_fetch =
	     WILL_FIRE_RL_do_if && !fetchPending &&
	     NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d543 ;
  assign imemP$EN_instr =
	     WILL_FIRE_RL_do_if && fetchPending &&
	     (flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d523 ||
	      NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d539) ;
  assign imemP$EN_axi_aw_get = EN_imem_aw_get ;
  assign imemP$EN_axi_w_get = EN_imem_w_get ;
  assign imemP$EN_axi_b_put = EN_imem_b_put ;
  assign imemP$EN_axi_ar_get = EN_imem_ar_get ;
  assign imemP$EN_axi_r_put = EN_imem_r_put ;

  // submodule md
  assign md$start_a = a__h13943 ;
  assign md$start_b = b__h13944 ;
  assign md$start_op = idex_r[149:147] ;
  assign md$EN_start =
	     WILL_FIRE_RL_do_ex && idex_r[271] && idex_r[150] &&
	     !idex_r[67] &&
	     NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 &&
	     NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 &&
	     !mdInFlight ;

  // submodule pcu
  assign pcu$advance_nxt = fetchPc + 32'd4 ;
  assign pcu$dbgSet_v = dbgSetPc_a ;
  assign pcu$redirect_tgt =
	     exmem_w_1$whas ? x_wget__h9822 : branchJump___d449[31:0] ;
  assign pcu$EN_advance =
	     WILL_FIRE_RL_do_if && fetchPending &&
	     NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d555 ;
  assign pcu$EN_redirect =
	     WILL_FIRE_RL_do_if &&
	     (redirectEx$whas || exmem_w_1$whas || redirectEx$whas) ;
  assign pcu$EN_dbgSet = EN_dbgSetPc ;

  // submodule rf
  assign rf$dbgRead_a = dbgGprRead_r ;
  assign rf$dbgWrite_a = dbgGprWrite_r ;
  assign rf$dbgWrite_d = dbgGprWrite_v ;
  assign rf$read1_a = decode___d467[63:59] ;
  assign rf$read2_a = decode___d467[58:54] ;
  assign rf$write_a = _read_rd__h10243 ;
  assign rf$write_d = memwb[104:73] ;
  assign rf$EN_write =
	     WILL_FIRE_RL_do_wb && memwb[168] && !wbDoneE_r && !memwb[67] &&
	     memwb[114] &&
	     memwb[72:68] != 5'd0 ;
  assign rf$EN_dbgWrite = EN_dbgGprWrite ;

  // remaining internal signals
  module_forward instance_forward_0(.forward_rs1(_read_di_rs1__h2553),
				    .forward_rs2(_read_di_rs2__h2554),
				    .forward_exRd(_read_rd__h4607),
				    .forward_exWr(exmem_r[232] &&
						  exmem_r[178] &&
						  exmem_r[177:175] != 3'd1 &&
						  !exmem_r[67]),
				    .forward_memRd(_read_rd__h10243),
				    .forward_memWr(memwb[168] && memwb[114] &&
						   !memwb[67]),
				    .forward(forward___d382));
  module_alu instance_alu_2(.alu_op(idex_r[162:159]),
			    .alu_a(opA__h13946),
			    .alu_b(opB__h13947),
			    .alu(aluR__h13948));
  module_branchJump instance_branchJump_3(.branchJump_c(idex_r[162:132]),
					  .branchJump_pc(_read_pc__h1985),
					  .branchJump_a(a__h13943),
					  .branchJump_b(b__h13944),
					  .branchJump_imm(_read_di_imm__h2558),
					  .branchJump(branchJump___d449));
  module_decode instance_decode_4(.decode_inst(_read_instr__h1014),
				  .decode(decode___d467));
  module_control instance_control_1(.control_d(decode___d467),
				    .control(control___d468));
  assign IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d154 =
	     (IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 ==
	      2'd1) ?
	       v_aluOut__h5022[0] :
	       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 ==
	       2'd2 &&
	       v_aluOut__h5022[1:0] != 2'd0 ;
  assign IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d258 =
	     (IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178 &&
	      IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30) ?
	       { v_pc__h5020,
		 IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d232,
		 32'd0,
		 v_rd__h5025,
		 1'd1,
		 IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d170 ?
		   3'd4 :
		   3'd3,
		 IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d243 } :
	       IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d257 ;
  assign IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d265 =
	     ((IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 ==
	       2'd1) ?
		!v_aluOut__h5022[0] :
		IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 !=
		2'd2 ||
		v_aluOut__h5022[1:0] == 2'd0) &&
	     dmemP$canReq ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d111 =
	     exmem_w_1$whas ||
	     (idex_w_0$whas ? !exmem_w_0$wget[232] : !exmem_r[232]) ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d119 =
	     exmem_w_1$whas ||
	     (idex_w_0$whas ? !exmem_w_0$wget[183] : !exmem_r[183]) ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d127 =
	     exmem_w_1$whas ||
	     (idex_w_0$whas ? !exmem_w_0$wget[182] : !exmem_r[182]) ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d135 =
	     IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d111 ||
	     IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d119 &&
	     IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d127 ||
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d134 ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d160 =
	     IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d135 ||
	     IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101 ||
	     IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d154 ||
	     !dmemP$canReq ||
	     dmemP$RDY_req ;
  assign IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d177 =
	     exmem_w_1$whas ||
	     (idex_w_0$whas ? !exmem_w_0$wget[67] : !exmem_r[67]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d134 =
	     !exmem_w_1$whas &&
	     (idex_w_0$whas ? exmem_w_0$wget[67] : exmem_r[67]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 =
	     exmem_w_1$whas ?
	       2'b10 :
	       (idex_w_0$whas ? exmem_w_0$wget[181:180] : exmem_r[181:180]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d166 =
	     !exmem_w_1$whas &&
	     (idex_w_0$whas ? exmem_w_0$wget[232] : exmem_r[232]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d168 =
	     !exmem_w_1$whas &&
	     (idex_w_0$whas ? exmem_w_0$wget[183] : exmem_r[183]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d170 =
	     !exmem_w_1$whas &&
	     (idex_w_0$whas ? exmem_w_0$wget[182] : exmem_r[182]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178 =
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d166 &&
	     (IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d168 ||
	      IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d170) &&
	     IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d177 ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d183 =
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178 &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 &&
	     IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d154 ||
	     (IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d135 ||
	      IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101) &&
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d166 &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d232 =
	     exmem_w_1$whas ?
	       31'b0000000000000000001000000000000 :
	       (idex_w_0$whas ? exmem_w_0$wget[199:169] : exmem_r[199:169]) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d243 =
	     exmem_w_1$whas ?
	       64'b0 :
	       (idex_w_0$whas ?
		  { exmem_w_0$wget[231:200], exmem_w_0$wget[168:137] } :
		  { exmem_r[231:200], exmem_r[168:137] }) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d257 =
	     exmem_w_1$whas ?
	       168'h000000000000200000000000010000000000000000 :
	       (idex_w_0$whas ?
		  { exmem_w_0$wget[231:137], exmem_w_0$wget[72:0] } :
		  { exmem_r[231:137], exmem_r[72:0] }) ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d271 =
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178 &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 &&
	     (IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d154 ||
	      dmemP$canReq) ||
	     (IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d135 ||
	      IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101) &&
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d166 &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 ;
  assign IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_EL_ETC___d23 =
	     exmem_w_1$whas ?
	       233'h00000000000002000000000000000000000000000010000000000000000 :
	       (idex_w_0$whas ? exmem_w_0$wget : exmem_r) ;
  assign IF_flushFront_whas__54_AND_flushFront_wget__55_ETC___d515 =
	     (redirectEx$whas || exmem_w_1$whas || redirectEx$whas ||
	      fetchDrop) ?
	       !imemP$instrReady || imemP$RDY_instr :
	       !imemP$instrReady || !ifid_w_0$whas && ifid_r[132] ||
	       imemP$RDY_instr ;
  assign IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d47 =
	     EN_reqHalt ? reqHalt_h : haltReqE_r ;
  assign IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d573 =
	     IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d47 &&
	     (haltedE_w_0$whas || !haltedE_r) &&
	     !fetchPending &&
	     !memPending &&
	     !mdInFlight ;
  assign IF_haltedE_w_0_whas__6_THEN_haltedE_w_0_wget___ETC___d39 =
	     !haltedE_w_0$whas && haltedE_r ;
  assign IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d403 =
	     (idex_r[271] && !idex_r[150] && !exmem_r[232] &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       x__h14637 :
	       32'd0 ;
  assign IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d405 =
	     (idex_r[271] && !idex_r[150] && !exmem_r[232] &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       csr$csrRead :
	       32'd0 ;
  assign IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d421 =
	     (idex_r[271] && !idex_r[150] && !exmem_r[232] &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       { idex_r[137:136] != 2'd0 && !csr$csrLegal || idex_r[67],
		 (!idex_r[67] && idex_r[137:136] != 2'd0 && !csr$csrLegal) ?
		   { 3'd1, idex_r[270:239], 32'd0 } :
		   idex_r[66:0] } :
	       idex_r[67:0] ;
  assign IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d404 =
	     (idex_r[271] && idex_r[150] && !idex_r[67] &&
	      NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       md$result :
	       IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d403 ;
  assign IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d406 =
	     (idex_r[271] && idex_r[150] && !idex_r[67] &&
	      NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       32'd0 :
	       IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d405 ;
  assign IF_idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_ETC___d422 =
	     (idex_r[271] && idex_r[150] && !idex_r[67] &&
	      NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 &&
	      NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337) ?
	       idex_r[67:0] :
	       IF_idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_15_ETC___d421 ;
  assign IF_memPending_9_THEN_IF_wbDoneE_w_0_whas__7_TH_ETC___d161 =
	     memPending ?
	       IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101 ||
	       dmemP$RDY_resp :
	       IF_exmem_w_1_whas__7_THEN_NOT_exmem_w_1_wget___ETC___d160 ;
  assign IF_memPending_9_THEN_memCur_86_BITS_231_TO_169_ETC___d259 =
	     memPending ?
	       { memCur[231:169], x__h13194, memCur[72:0] } :
	       IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d258 ;
  assign IF_stepArmedE_w_0_whas__8_THEN_stepArmedE_w_0__ETC___d61 =
	     stepReqE_w_1$whas || stepArmedE_r ;
  assign IF_stepReqE_w_0_whas__1_THEN_stepReqE_w_0_wget_ETC___d54 =
	     EN_reqStep || stepReqE_r ;
  assign IF_wbDoneE_w_0_whas__7_THEN_NOT_wbDoneE_w_0_wg_ETC___d101 =
	     !wbDoneE_w_0$whas && !wbDoneE_r ;
  assign IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 =
	     wbDoneE_w_0$whas || wbDoneE_r ;
  assign NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 =
	     !exmem_r[232] || !exmem_r[183] || exmem_r[72:68] == 5'd0 ||
	     !exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d307 &&
	     !exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d309 ;
  assign NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d539 =
	     !redirectEx$whas && !exmem_w_1$whas && !redirectEx$whas &&
	     (fetchDrop && imemP$instrReady ||
	      !fetchDrop &&
	      imemP_instrReady__07_AND_IF_ifid_w_0_whas_THEN_ETC___d536) ;
  assign NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d543 =
	     !redirectEx$whas && !exmem_w_1$whas && !redirectEx$whas &&
	     imemP$canFetch ;
  assign NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d555 =
	     !redirectEx$whas && !exmem_w_1$whas && !redirectEx$whas &&
	     !fetchDrop &&
	     imemP_instrReady__07_AND_IF_ifid_w_0_whas_THEN_ETC___d536 ;
  assign NOT_idex_r_2_BIT_271_95_96_OR_NOT_idex_r_2_BIT_ETC___d326 =
	     !idex_r[271] || !idex_r[150] || idex_r[67] ||
	     exmem_r[232] && exmem_r[183] && exmem_r[72:68] != 5'd0 &&
	     (exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d307 ||
	      exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d309) ||
	     memPending && memCur[183] && memCur[72:68] != 5'd0 &&
	     (memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d317 ||
	      memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d318) ||
	     mdInFlight ||
	     md$RDY_start ;
  assign NOT_memPending_9_64_AND_IF_exmem_w_1_whas__7_T_ETC___d267 =
	     !memPending &&
	     IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d178 &&
	     IF_wbDoneE_w_0_whas__7_THEN_wbDoneE_w_0_wget___ETC___d30 &&
	     IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d265 ;
  assign NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 =
	     !memPending || !memCur[183] || memCur[72:68] == 5'd0 ||
	     !memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d317 &&
	     !memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d318 ;
  assign _dfoo1 =
	     IF_haltReqE_w_0_whas__4_THEN_haltReqE_w_0_wget_ETC___d573 ||
	     IF_stepReqE_w_0_whas__1_THEN_stepReqE_w_0_wget_ETC___d54 &&
	     IF_haltedE_w_0_whas__6_THEN_haltedE_w_0_wget___ETC___d39 ;
  assign _read_di_imm__h2558 = idex_r[194:163] ;
  assign _read_di_rs1__h2553 = idex_r[226:222] ;
  assign _read_di_rs2__h2554 = idex_r[221:217] ;
  assign _read_instr__h1014 = ifid_r[99:68] ;
  assign _read_pc__h1985 = idex_r[270:239] ;
  assign _read_rd__h10243 = memwb[72:68] ;
  assign _read_rd__h4607 = exmem_r[72:68] ;
  assign csrSrc__h13950 =
	     idex_r[135] ? { 27'd0, idex_r[226:222] } : a__h13943 ;
  assign d__h12549 = v_rs2v__h5023 << x__h12590 ;
  assign d__h12569 = v_rs2v__h5023 << x__h12632 ;
  assign exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d307 =
	     exmem_r[72:68] == idex_r[226:222] ;
  assign exmem_r_1_BITS_72_TO_68_35_EQ_idex_r_2_BITS_22_ETC___d309 =
	     exmem_r[72:68] == idex_r[221:217] ;
  assign fetchPending_01_AND_flushFront_whas__54_AND_fl_ETC___d545 =
	     fetchPending &&
	     (flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d523 ||
	      NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d539) ||
	     !fetchPending &&
	     NOT_flushFront_whas__54_24_OR_NOT_flushFront_w_ETC___d543 ;
  assign flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d464 =
	     redirectEx$whas || exmem_w_1$whas ||
	     ifid_r[132] && (idex_w_0$whas || !idex_r[271]) ;
  assign flushFront_whas__54_AND_flushFront_wget__55_56_ETC___d523 =
	     (redirectEx$whas || exmem_w_1$whas || redirectEx$whas) &&
	     imemP$instrReady ;
  assign h__h13349 = memCur[138] ? dmemP$resp[31:16] : dmemP$resp[15:0] ;
  assign idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d433 =
	     idex_r[271] && !idex_r[150] && !exmem_r[232] &&
	     NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 &&
	     idex_r[137:136] != 2'd0 &&
	     !idex_r[67] &&
	     csr$csrLegal ;
  assign idex_r_2_BIT_271_95_AND_NOT_idex_r_2_BIT_150_9_ETC___d452 =
	     idex_r[271] && !idex_r[150] && !exmem_r[232] &&
	     NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 &&
	     (idex_r[137:136] == 2'd0 || csr$csrLegal) &&
	     !idex_r[67] &&
	     branchJump___d449[32] ;
  assign idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d342 =
	     idex_r[271] && idex_r[150] && !idex_r[67] &&
	     NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 &&
	     mdInFlight &&
	     md$done &&
	     !exmem_r[232] ;
  assign idex_r_2_BIT_271_95_AND_idex_r_2_BIT_150_97_28_ETC___d428 =
	     idex_r[271] && idex_r[150] && !idex_r[67] &&
	     NOT_exmem_r_1_BIT_232_08_09_OR_NOT_exmem_r_1_B_ETC___d359 &&
	     NOT_memPending_9_64_OR_NOT_memCur_86_BIT_183_8_ETC___d337 &&
	     (md$done && !exmem_r[232] || !mdInFlight) ;
  assign imemP_instrReady__07_AND_IF_ifid_w_0_whas_THEN_ETC___d536 =
	     imemP$instrReady && (ifid_w_0$whas || !ifid_r[132]) ;
  assign memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d317 =
	     memCur[72:68] == idex_r[226:222] ;
  assign memCur_86_BITS_72_TO_68_13_EQ_idex_r_2_BITS_22_ETC___d318 =
	     memCur[72:68] == idex_r[221:217] ;
  assign opB__h13947 = idex_r[156] ? idex_r[194:163] : b__h13944 ;
  assign rf_read1_decode_67_BITS_63_TO_59_69_70_CONCAT__ETC___d497 =
	     { rf$read1,
	       rf$read2,
	       ifid_r[67] ?
		 ifid_r[67:0] :
		 { control___d468[0] || control___d468[2:1] == 2'd1 ||
		   control___d468[2:1] == 2'd2 ||
		   ifid_r[67],
		   control___d468[0] ?
		     3'd1 :
		     CASE_control_68_BITS_2_TO_1_1_5_2_2_ifid_r_BIT_ETC__q1,
		   (control___d468[0] || control___d468[2:1] == 2'd1 ||
		    control___d468[2:1] == 2'd2) ?
		     ifid_r[131:100] :
		     ifid_r[63:32],
		   control___d468[0] ?
		     ifid_r[99:68] :
		     CASE_control_68_BITS_2_TO_1_1_0_2_ifid_r_BITS__ETC__q2 } } ;
  assign s__h12550 = 4'b0001 << v_aluOut__h5022[1:0] ;
  assign s__h12570 = 4'b0011 << x__h12696 ;
  assign v_aluOut__h4813 =
	     idex_w_0$whas ? exmem_w_0$wget[168:137] : exmem_r[168:137] ;
  assign v_aluOut__h5022 = exmem_w_1$whas ? 32'b0 : v_aluOut__h4813 ;
  assign v_pc__h4811 =
	     idex_w_0$whas ? exmem_w_0$wget[231:200] : exmem_r[231:200] ;
  assign v_pc__h5020 = exmem_w_1$whas ? 32'b0 : v_pc__h4811 ;
  assign v_rd__h4816 =
	     idex_w_0$whas ? exmem_w_0$wget[72:68] : exmem_r[72:68] ;
  assign v_rd__h5025 = exmem_w_1$whas ? 5'b0 : v_rd__h4816 ;
  assign v_rs2v__h4814 =
	     idex_w_0$whas ? exmem_w_0$wget[136:105] : exmem_r[136:105] ;
  assign v_rs2v__h5023 = exmem_w_1$whas ? 32'b0 : v_rs2v__h4814 ;
  assign x__h12590 = { v_aluOut__h5022[1:0], 3'b0 } ;
  assign x__h12632 = { v_aluOut__h5022[1], 4'b0 } ;
  assign x__h12696 = { v_aluOut__h5022[1], 1'b0 } ;
  assign x__h13194 =
	     memCur[183] ?
	       IF_memCur_86_BITS_181_TO_180_89_EQ_0_90_THEN_I_ETC___d218 :
	       memCur[168:137] ;
  assign x_wget__h9822 = memwb[67] ? csr$trap : csr$mret ;
  assign y__h14404 = ~csrSrc__h13950 ;
  always@(memCur or dmemP$resp)
  begin
    case (memCur[138:137])
      2'd0: b__h13205 = dmemP$resp[7:0];
      2'd1: b__h13205 = dmemP$resp[15:8];
      2'd2: b__h13205 = dmemP$resp[23:16];
      2'd3: b__h13205 = dmemP$resp[31:24];
    endcase
  end
  always@(forward___d382 or idex_r or exmem_r or memwb)
  begin
    case (forward___d382[1:0])
      2'd1: b__h13944 = exmem_r[168:137];
      2'd2: b__h13944 = memwb[104:73];
      default: b__h13944 = idex_r[99:68];
    endcase
  end
  always@(forward___d382 or idex_r or exmem_r or memwb)
  begin
    case (forward___d382[3:2])
      2'd1: a__h13943 = exmem_r[168:137];
      2'd2: a__h13943 = memwb[104:73];
      default: a__h13943 = idex_r[131:100];
    endcase
  end
  always@(idex_r or a__h13943)
  begin
    case (idex_r[158:157])
      2'd1: opA__h13946 = idex_r[270:239];
      2'd2: opA__h13946 = 32'd0;
      default: opA__h13946 = a__h13943;
    endcase
  end
  always@(idex_r or aluR__h13948 or csr$csrRead)
  begin
    case (idex_r[140:138])
      3'd2: x__h14637 = idex_r[270:239] + 32'd4;
      3'd3: x__h14637 = csr$csrRead;
      default: x__h14637 = aluR__h13948;
    endcase
  end
  always@(memCur or dmemP$resp or b__h13205 or h__h13349)
  begin
    case (memCur[181:180])
      2'd0:
	  IF_memCur_86_BITS_181_TO_180_89_EQ_0_90_THEN_I_ETC___d218 =
	      memCur[179] ?
		{ 24'd0, b__h13205 } :
		{ {24{b__h13205[7]}}, b__h13205 };
      2'd1:
	  IF_memCur_86_BITS_181_TO_180_89_EQ_0_90_THEN_I_ETC___d218 =
	      memCur[179] ?
		{ 16'd0, h__h13349 } :
		{ {16{h__h13349[15]}}, h__h13349 };
      default: IF_memCur_86_BITS_181_TO_180_89_EQ_0_90_THEN_I_ETC___d218 =
		   dmemP$resp;
    endcase
  end
  always@(control___d468 or ifid_r)
  begin
    case (control___d468[2:1])
      2'd1: CASE_control_68_BITS_2_TO_1_1_5_2_2_ifid_r_BIT_ETC__q1 = 3'd5;
      2'd2: CASE_control_68_BITS_2_TO_1_1_5_2_2_ifid_r_BIT_ETC__q1 = 3'd2;
      default: CASE_control_68_BITS_2_TO_1_1_5_2_2_ifid_r_BIT_ETC__q1 =
		   ifid_r[66:64];
    endcase
  end
  always@(control___d468 or ifid_r)
  begin
    case (control___d468[2:1])
      2'd1: CASE_control_68_BITS_2_TO_1_1_0_2_ifid_r_BITS__ETC__q2 = 32'd0;
      2'd2:
	  CASE_control_68_BITS_2_TO_1_1_0_2_ifid_r_BITS__ETC__q2 =
	      ifid_r[131:100];
      default: CASE_control_68_BITS_2_TO_1_1_0_2_ifid_r_BITS__ETC__q2 =
		   ifid_r[31:0];
    endcase
  end
  always@(IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141 or
	  v_rs2v__h5023 or d__h12549 or s__h12550 or d__h12569 or s__h12570)
  begin
    case (IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_BI_ETC___d141)
      2'd0:
	  IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d291 =
	      { d__h12549, s__h12550 };
      2'd1:
	  IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d291 =
	      { d__h12569, s__h12570 };
      default: IF_IF_exmem_w_1_whas__7_THEN_exmem_w_1_wget__8_ETC___d291 =
		   { v_rs2v__h5023, 4'b1111 };
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        exmem_r <= `BSV_ASSIGNMENT_DELAY
	    233'h00000000000002000000000000000000000000000010000000000000000;
	fetchDrop <= `BSV_ASSIGNMENT_DELAY 1'd0;
	fetchPc <= `BSV_ASSIGNMENT_DELAY 32'h0;
	fetchPending <= `BSV_ASSIGNMENT_DELAY 1'd0;
	haltReqE_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	haltedE_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	idex_r <= `BSV_ASSIGNMENT_DELAY
	    272'h00000000000000000000000000000001000000000000000000010000000000000000;
	ifid_r <= `BSV_ASSIGNMENT_DELAY
	    133'h0000000000000000010000000000000000;
	mdInFlight <= `BSV_ASSIGNMENT_DELAY 1'd0;
	memCur <= `BSV_ASSIGNMENT_DELAY
	    233'h00000000000002000000000000000000000000000010000000000000000;
	memPending <= `BSV_ASSIGNMENT_DELAY 1'd0;
	memwb <= `BSV_ASSIGNMENT_DELAY
	    169'h0000000000000200000000000010000000000000000;
	retiredReg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stepArmedE_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	stepReqE_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	wbDoneE_r <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (exmem_r$EN) exmem_r <= `BSV_ASSIGNMENT_DELAY exmem_r$D_IN;
	if (fetchDrop$EN) fetchDrop <= `BSV_ASSIGNMENT_DELAY fetchDrop$D_IN;
	if (fetchPc$EN) fetchPc <= `BSV_ASSIGNMENT_DELAY fetchPc$D_IN;
	if (fetchPending$EN)
	  fetchPending <= `BSV_ASSIGNMENT_DELAY fetchPending$D_IN;
	if (haltReqE_r$EN)
	  haltReqE_r <= `BSV_ASSIGNMENT_DELAY haltReqE_r$D_IN;
	if (haltedE_r$EN) haltedE_r <= `BSV_ASSIGNMENT_DELAY haltedE_r$D_IN;
	if (idex_r$EN) idex_r <= `BSV_ASSIGNMENT_DELAY idex_r$D_IN;
	if (ifid_r$EN) ifid_r <= `BSV_ASSIGNMENT_DELAY ifid_r$D_IN;
	if (mdInFlight$EN)
	  mdInFlight <= `BSV_ASSIGNMENT_DELAY mdInFlight$D_IN;
	if (memCur$EN) memCur <= `BSV_ASSIGNMENT_DELAY memCur$D_IN;
	if (memPending$EN)
	  memPending <= `BSV_ASSIGNMENT_DELAY memPending$D_IN;
	if (memwb$EN) memwb <= `BSV_ASSIGNMENT_DELAY memwb$D_IN;
	if (retiredReg$EN)
	  retiredReg <= `BSV_ASSIGNMENT_DELAY retiredReg$D_IN;
	if (stepArmedE_r$EN)
	  stepArmedE_r <= `BSV_ASSIGNMENT_DELAY stepArmedE_r$D_IN;
	if (stepReqE_r$EN)
	  stepReqE_r <= `BSV_ASSIGNMENT_DELAY stepReqE_r$D_IN;
	if (wbDoneE_r$EN) wbDoneE_r <= `BSV_ASSIGNMENT_DELAY wbDoneE_r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    exmem_r =
	233'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    fetchDrop = 1'h0;
    fetchPc = 32'hAAAAAAAA;
    fetchPending = 1'h0;
    haltReqE_r = 1'h0;
    haltedE_r = 1'h0;
    idex_r =
	272'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    ifid_r = 133'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    mdInFlight = 1'h0;
    memCur = 233'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    memPending = 1'h0;
    memwb = 169'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    retiredReg = 1'h0;
    stepArmedE_r = 1'h0;
    stepReqE_r = 1'h0;
    wbDoneE_r = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCore

