//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// csrRead                        O    32
// RDY_csrRead                    O     1 const
// csrLegal                       O     1
// RDY_csrLegal                   O     1 const
// RDY_csrWrite                   O     1 const
// trap                           O    32
// RDY_trap                       O     1 const
// mret                           O    32
// RDY_mret                       O     1 const
// RDY_tick                       O     1 const
// dbgRead                        O    32
// RDY_dbgRead                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// csrRead_addr                   I    12
// csrLegal_addr                  I    12
// csrWrite_addr                  I    12
// csrWrite_v                     I    32
// trap_cause                     I     3
// trap_epc                       I    32
// trap_tval                      I    32
// tick_retired                   I     1
// dbgRead_addr                   I    12
// EN_csrWrite                    I     1
// EN_tick                        I     1
// EN_trap                        I     1
// EN_mret                        I     1
//
// Combinational paths from inputs to outputs:
//   csrRead_addr -> csrRead
//   csrLegal_addr -> csrLegal
//   dbgRead_addr -> dbgRead
//   (csrWrite_addr, csrWrite_v, EN_csrWrite) -> trap
//   (csrWrite_addr, csrWrite_v, EN_csrWrite) -> mret
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCSRFile(CLK,
		 RST_N,

		 csrRead_addr,
		 csrRead,
		 RDY_csrRead,

		 csrLegal_addr,
		 csrLegal,
		 RDY_csrLegal,

		 csrWrite_addr,
		 csrWrite_v,
		 EN_csrWrite,
		 RDY_csrWrite,

		 trap_cause,
		 trap_epc,
		 trap_tval,
		 EN_trap,
		 trap,
		 RDY_trap,

		 EN_mret,
		 mret,
		 RDY_mret,

		 tick_retired,
		 EN_tick,
		 RDY_tick,

		 dbgRead_addr,
		 dbgRead,
		 RDY_dbgRead);
  input  CLK;
  input  RST_N;

  // value method csrRead
  input  [11 : 0] csrRead_addr;
  output [31 : 0] csrRead;
  output RDY_csrRead;

  // value method csrLegal
  input  [11 : 0] csrLegal_addr;
  output csrLegal;
  output RDY_csrLegal;

  // action method csrWrite
  input  [11 : 0] csrWrite_addr;
  input  [31 : 0] csrWrite_v;
  input  EN_csrWrite;
  output RDY_csrWrite;

  // actionvalue method trap
  input  [2 : 0] trap_cause;
  input  [31 : 0] trap_epc;
  input  [31 : 0] trap_tval;
  input  EN_trap;
  output [31 : 0] trap;
  output RDY_trap;

  // actionvalue method mret
  input  EN_mret;
  output [31 : 0] mret;
  output RDY_mret;

  // action method tick
  input  tick_retired;
  input  EN_tick;
  output RDY_tick;

  // value method dbgRead
  input  [11 : 0] dbgRead_addr;
  output [31 : 0] dbgRead;
  output RDY_dbgRead;

  // signals for module outputs
  reg [31 : 0] csrRead, dbgRead;
  wire [31 : 0] mret, trap;
  wire RDY_csrLegal,
       RDY_csrRead,
       RDY_csrWrite,
       RDY_dbgRead,
       RDY_mret,
       RDY_tick,
       RDY_trap,
       csrLegal;

  // inlined wires
  wire mcause_w_1$whas,
       mcycle_w_1$whas,
       mepc_w_1$whas,
       minstret_w_0$whas,
       minstret_w_1$whas,
       mscratch_w_1$whas,
       mstatus_w_1$whas,
       mstatus_w_2$whas,
       mtval_w_1$whas,
       mtvec_w_1$whas;

  // register mcause_r
  reg [31 : 0] mcause_r;
  wire [31 : 0] mcause_r$D_IN;
  wire mcause_r$EN;

  // register mcycle_r
  reg [63 : 0] mcycle_r;
  wire [63 : 0] mcycle_r$D_IN;
  wire mcycle_r$EN;

  // register mepc_r
  reg [31 : 0] mepc_r;
  wire [31 : 0] mepc_r$D_IN;
  wire mepc_r$EN;

  // register minstret_r
  reg [63 : 0] minstret_r;
  wire [63 : 0] minstret_r$D_IN;
  wire minstret_r$EN;

  // register mscratch_r
  reg [31 : 0] mscratch_r;
  wire [31 : 0] mscratch_r$D_IN;
  wire mscratch_r$EN;

  // register mstatus_r
  reg [31 : 0] mstatus_r;
  wire [31 : 0] mstatus_r$D_IN;
  wire mstatus_r$EN;

  // register mtval_r
  reg [31 : 0] mtval_r;
  wire [31 : 0] mtval_r$D_IN;
  wire mtval_r$EN;

  // register mtvec_r
  reg [31 : 0] mtvec_r;
  wire [31 : 0] mtvec_r$D_IN;
  wire mtvec_r$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_mcause_canonicalize,
       CAN_FIRE_RL_mcycle_canonicalize,
       CAN_FIRE_RL_mepc_canonicalize,
       CAN_FIRE_RL_minstret_canonicalize,
       CAN_FIRE_RL_mscratch_canonicalize,
       CAN_FIRE_RL_mstatus_canonicalize,
       CAN_FIRE_RL_mtval_canonicalize,
       CAN_FIRE_RL_mtvec_canonicalize,
       CAN_FIRE_csrWrite,
       CAN_FIRE_mret,
       CAN_FIRE_tick,
       CAN_FIRE_trap,
       WILL_FIRE_RL_mcause_canonicalize,
       WILL_FIRE_RL_mcycle_canonicalize,
       WILL_FIRE_RL_mepc_canonicalize,
       WILL_FIRE_RL_minstret_canonicalize,
       WILL_FIRE_RL_mscratch_canonicalize,
       WILL_FIRE_RL_mstatus_canonicalize,
       WILL_FIRE_RL_mtval_canonicalize,
       WILL_FIRE_RL_mtvec_canonicalize,
       WILL_FIRE_csrWrite,
       WILL_FIRE_mret,
       WILL_FIRE_tick,
       WILL_FIRE_trap;

  // inputs to muxes for submodule ports
  wire [31 : 0] MUX_mstatus_w_2$wset_1__VAL_1, MUX_mstatus_w_2$wset_1__VAL_2;

  // remaining internal signals
  reg [30 : 0] CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1;
  wire [63 : 0] def__h3849,
		def__h4290,
		x__h5328,
		x__h5351,
		x__h5376,
		x__h5399,
		x_wget__h3735,
		x_wget__h3784,
		x_wget__h4176,
		x_wget__h4225;
  wire [31 : 0] def__h1000,
		def__h1586,
		def__h2172,
		def__h2758,
		def__h3344,
		def__h414,
		x_wget__h2097,
		x_wget__h339;

  // value method csrRead
  always@(csrRead_addr or
	  mstatus_r or
	  mtvec_r or
	  mscratch_r or
	  mepc_r or mcause_r or mtval_r or mcycle_r or minstret_r)
  begin
    case (csrRead_addr)
      12'h300: csrRead = mstatus_r;
      12'h305: csrRead = mtvec_r;
      12'h340: csrRead = mscratch_r;
      12'h341: csrRead = mepc_r;
      12'h342: csrRead = mcause_r;
      12'h343: csrRead = mtval_r;
      12'hB00: csrRead = mcycle_r[31:0];
      12'hB02: csrRead = minstret_r[31:0];
      12'hB80: csrRead = mcycle_r[63:32];
      12'hB82: csrRead = minstret_r[63:32];
      default: csrRead = 32'd0;
    endcase
  end
  assign RDY_csrRead = 1'd1 ;

  // value method csrLegal
  assign csrLegal =
	     csrLegal_addr == 12'h300 || csrLegal_addr == 12'h305 ||
	     csrLegal_addr == 12'h341 ||
	     csrLegal_addr == 12'h342 ||
	     csrLegal_addr == 12'h343 ||
	     csrLegal_addr == 12'h340 ||
	     csrLegal_addr == 12'hB00 ||
	     csrLegal_addr == 12'hB80 ||
	     csrLegal_addr == 12'hB02 ||
	     csrLegal_addr == 12'hB82 ||
	     csrLegal_addr == 12'h301 ||
	     csrLegal_addr == 12'hF11 ||
	     csrLegal_addr == 12'hF12 ||
	     csrLegal_addr == 12'hF13 ||
	     csrLegal_addr == 12'hF14 ;
  assign RDY_csrLegal = 1'd1 ;

  // action method csrWrite
  assign RDY_csrWrite = 1'd1 ;
  assign CAN_FIRE_csrWrite = 1'd1 ;
  assign WILL_FIRE_csrWrite = EN_csrWrite ;

  // actionvalue method trap
  assign trap = mtvec_w_1$whas ? csrWrite_v : mtvec_r ;
  assign RDY_trap = 1'd1 ;
  assign CAN_FIRE_trap = 1'd1 ;
  assign WILL_FIRE_trap = EN_trap ;

  // actionvalue method mret
  assign mret = mepc_w_1$whas ? csrWrite_v : mepc_r ;
  assign RDY_mret = 1'd1 ;
  assign CAN_FIRE_mret = 1'd1 ;
  assign WILL_FIRE_mret = EN_mret ;

  // action method tick
  assign RDY_tick = 1'd1 ;
  assign CAN_FIRE_tick = 1'd1 ;
  assign WILL_FIRE_tick = EN_tick ;

  // value method dbgRead
  always@(dbgRead_addr or
	  mstatus_r or
	  mtvec_r or
	  mscratch_r or
	  mepc_r or mcause_r or mtval_r or mcycle_r or minstret_r)
  begin
    case (dbgRead_addr)
      12'h300: dbgRead = mstatus_r;
      12'h305: dbgRead = mtvec_r;
      12'h340: dbgRead = mscratch_r;
      12'h341: dbgRead = mepc_r;
      12'h342: dbgRead = mcause_r;
      12'h343: dbgRead = mtval_r;
      12'hB00: dbgRead = mcycle_r[31:0];
      12'hB02: dbgRead = minstret_r[31:0];
      12'hB80: dbgRead = mcycle_r[63:32];
      12'hB82: dbgRead = minstret_r[63:32];
      default: dbgRead = 32'd0;
    endcase
  end
  assign RDY_dbgRead = 1'd1 ;

  // rule RL_mstatus_canonicalize
  assign CAN_FIRE_RL_mstatus_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mstatus_canonicalize = 1'd1 ;

  // rule RL_mtvec_canonicalize
  assign CAN_FIRE_RL_mtvec_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mtvec_canonicalize = 1'd1 ;

  // rule RL_mepc_canonicalize
  assign CAN_FIRE_RL_mepc_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mepc_canonicalize = 1'd1 ;

  // rule RL_mcause_canonicalize
  assign CAN_FIRE_RL_mcause_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mcause_canonicalize = 1'd1 ;

  // rule RL_mtval_canonicalize
  assign CAN_FIRE_RL_mtval_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mtval_canonicalize = 1'd1 ;

  // rule RL_mscratch_canonicalize
  assign CAN_FIRE_RL_mscratch_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mscratch_canonicalize = 1'd1 ;

  // rule RL_mcycle_canonicalize
  assign CAN_FIRE_RL_mcycle_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_mcycle_canonicalize = 1'd1 ;

  // rule RL_minstret_canonicalize
  assign CAN_FIRE_RL_minstret_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_minstret_canonicalize = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_mstatus_w_2$wset_1__VAL_1 =
	     { def__h414[31:13],
	       2'd3,
	       def__h414[10:8],
	       def__h414[3],
	       def__h414[6:4],
	       1'd0,
	       def__h414[2:0] } ;
  assign MUX_mstatus_w_2$wset_1__VAL_2 =
	     { def__h414[31:13],
	       2'd3,
	       def__h414[10:8],
	       1'd1,
	       def__h414[6:4],
	       def__h414[7],
	       def__h414[2:0] } ;

  // inlined wires
  assign mstatus_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h300 ;
  assign mstatus_w_2$whas = EN_trap || EN_mret ;
  assign mtvec_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h305 ;
  assign mepc_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h341 ;
  assign mcause_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h342 ;
  assign mtval_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h343 ;
  assign mscratch_w_1$whas = EN_csrWrite && csrWrite_addr == 12'h340 ;
  assign mcycle_w_1$whas =
	     EN_csrWrite &&
	     (csrWrite_addr == 12'hB00 || csrWrite_addr == 12'hB80) ;
  assign minstret_w_0$whas = EN_tick && tick_retired ;
  assign minstret_w_1$whas =
	     EN_csrWrite &&
	     (csrWrite_addr == 12'hB02 || csrWrite_addr == 12'hB82) ;

  // register mcause_r
  assign mcause_r$D_IN = EN_trap ? x_wget__h2097 : def__h2172 ;
  assign mcause_r$EN = 1'd1 ;

  // register mcycle_r
  assign mcycle_r$D_IN = mcycle_w_1$whas ? x_wget__h3784 : def__h3849 ;
  assign mcycle_r$EN = 1'd1 ;

  // register mepc_r
  assign mepc_r$D_IN = EN_trap ? trap_epc : def__h1586 ;
  assign mepc_r$EN = 1'd1 ;

  // register minstret_r
  assign minstret_r$D_IN = minstret_w_1$whas ? x_wget__h4225 : def__h4290 ;
  assign minstret_r$EN = 1'd1 ;

  // register mscratch_r
  assign mscratch_r$D_IN = def__h3344 ;
  assign mscratch_r$EN = 1'd1 ;

  // register mstatus_r
  assign mstatus_r$D_IN = mstatus_w_2$whas ? x_wget__h339 : def__h414 ;
  assign mstatus_r$EN = 1'd1 ;

  // register mtval_r
  assign mtval_r$D_IN = EN_trap ? trap_tval : def__h2758 ;
  assign mtval_r$EN = 1'd1 ;

  // register mtvec_r
  assign mtvec_r$D_IN = def__h1000 ;
  assign mtvec_r$EN = 1'd1 ;

  // remaining internal signals
  assign def__h1000 = mtvec_w_1$whas ? csrWrite_v : mtvec_r ;
  assign def__h1586 = mepc_w_1$whas ? csrWrite_v : mepc_r ;
  assign def__h2172 = mcause_w_1$whas ? csrWrite_v : mcause_r ;
  assign def__h2758 = mtval_w_1$whas ? csrWrite_v : mtval_r ;
  assign def__h3344 = mscratch_w_1$whas ? csrWrite_v : mscratch_r ;
  assign def__h3849 = EN_tick ? x_wget__h3735 : mcycle_r ;
  assign def__h414 = mstatus_w_1$whas ? csrWrite_v : mstatus_r ;
  assign def__h4290 = minstret_w_0$whas ? x_wget__h4176 : minstret_r ;
  assign x__h5328 = { def__h3849[63:32], csrWrite_v } ;
  assign x__h5351 = { csrWrite_v, def__h3849[31:0] } ;
  assign x__h5376 = { def__h4290[63:32], csrWrite_v } ;
  assign x__h5399 = { csrWrite_v, def__h4290[31:0] } ;
  assign x_wget__h2097 =
	     { 1'b0, CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 } ;
  assign x_wget__h339 =
	     EN_trap ?
	       MUX_mstatus_w_2$wset_1__VAL_1 :
	       MUX_mstatus_w_2$wset_1__VAL_2 ;
  assign x_wget__h3735 = mcycle_r + 64'd1 ;
  assign x_wget__h3784 = (csrWrite_addr == 12'hB00) ? x__h5328 : x__h5351 ;
  assign x_wget__h4176 = minstret_r + 64'd1 ;
  assign x_wget__h4225 = (csrWrite_addr == 12'hB02) ? x__h5376 : x__h5399 ;
  always@(trap_cause)
  begin
    case (trap_cause)
      3'd0: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd0;
      3'd1: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd2;
      3'd2: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd3;
      3'd3: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd4;
      3'd4: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd6;
      default: CASE_trap_cause_0_0_1_2_2_3_3_4_4_6_11__q1 = 31'd11;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        mcause_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	mcycle_r <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mepc_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	minstret_r <= `BSV_ASSIGNMENT_DELAY 64'd0;
	mscratch_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	mstatus_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	mtval_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	mtvec_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (mcause_r$EN) mcause_r <= `BSV_ASSIGNMENT_DELAY mcause_r$D_IN;
	if (mcycle_r$EN) mcycle_r <= `BSV_ASSIGNMENT_DELAY mcycle_r$D_IN;
	if (mepc_r$EN) mepc_r <= `BSV_ASSIGNMENT_DELAY mepc_r$D_IN;
	if (minstret_r$EN)
	  minstret_r <= `BSV_ASSIGNMENT_DELAY minstret_r$D_IN;
	if (mscratch_r$EN)
	  mscratch_r <= `BSV_ASSIGNMENT_DELAY mscratch_r$D_IN;
	if (mstatus_r$EN) mstatus_r <= `BSV_ASSIGNMENT_DELAY mstatus_r$D_IN;
	if (mtval_r$EN) mtval_r <= `BSV_ASSIGNMENT_DELAY mtval_r$D_IN;
	if (mtvec_r$EN) mtvec_r <= `BSV_ASSIGNMENT_DELAY mtvec_r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    mcause_r = 32'hAAAAAAAA;
    mcycle_r = 64'hAAAAAAAAAAAAAAAA;
    mepc_r = 32'hAAAAAAAA;
    minstret_r = 64'hAAAAAAAAAAAAAAAA;
    mscratch_r = 32'hAAAAAAAA;
    mstatus_r = 32'hAAAAAAAA;
    mtval_r = 32'hAAAAAAAA;
    mtvec_r = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCSRFile

