//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// RDY_fetch                      O     1
// instr                          O    32 reg
// RDY_instr                      O     1 reg
// canFetch                       O     1
// RDY_canFetch                   O     1 const
// instrReady                     O     1 reg
// RDY_instrReady                 O     1 const
// axi_aw_get                     O    35 reg
// RDY_axi_aw_get                 O     1 reg
// axi_w_get                      O    36 reg
// RDY_axi_w_get                  O     1 reg
// RDY_axi_b_put                  O     1 reg
// axi_ar_get                     O    35 reg
// RDY_axi_ar_get                 O     1 reg
// RDY_axi_r_put                  O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// fetch_pc                       I    32
// axi_b_put                      I     2 reg
// axi_r_put                      I    34 reg
// EN_fetch                       I     1
// EN_axi_b_put                   I     1
// EN_axi_r_put                   I     1
// EN_instr                       I     1
// EN_axi_aw_get                  I     1
// EN_axi_w_get                   I     1
// EN_axi_ar_get                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkInstMem(CLK,
		 RST_N,

		 fetch_pc,
		 EN_fetch,
		 RDY_fetch,

		 EN_instr,
		 instr,
		 RDY_instr,

		 canFetch,
		 RDY_canFetch,

		 instrReady,
		 RDY_instrReady,

		 EN_axi_aw_get,
		 axi_aw_get,
		 RDY_axi_aw_get,

		 EN_axi_w_get,
		 axi_w_get,
		 RDY_axi_w_get,

		 axi_b_put,
		 EN_axi_b_put,
		 RDY_axi_b_put,

		 EN_axi_ar_get,
		 axi_ar_get,
		 RDY_axi_ar_get,

		 axi_r_put,
		 EN_axi_r_put,
		 RDY_axi_r_put);
  input  CLK;
  input  RST_N;

  // action method fetch
  input  [31 : 0] fetch_pc;
  input  EN_fetch;
  output RDY_fetch;

  // actionvalue method instr
  input  EN_instr;
  output [31 : 0] instr;
  output RDY_instr;

  // value method canFetch
  output canFetch;
  output RDY_canFetch;

  // value method instrReady
  output instrReady;
  output RDY_instrReady;

  // actionvalue method axi_aw_get
  input  EN_axi_aw_get;
  output [34 : 0] axi_aw_get;
  output RDY_axi_aw_get;

  // actionvalue method axi_w_get
  input  EN_axi_w_get;
  output [35 : 0] axi_w_get;
  output RDY_axi_w_get;

  // action method axi_b_put
  input  [1 : 0] axi_b_put;
  input  EN_axi_b_put;
  output RDY_axi_b_put;

  // actionvalue method axi_ar_get
  input  EN_axi_ar_get;
  output [34 : 0] axi_ar_get;
  output RDY_axi_ar_get;

  // action method axi_r_put
  input  [33 : 0] axi_r_put;
  input  EN_axi_r_put;
  output RDY_axi_r_put;

  // signals for module outputs
  wire [35 : 0] axi_w_get;
  wire [34 : 0] axi_ar_get, axi_aw_get;
  wire [31 : 0] instr;
  wire RDY_axi_ar_get,
       RDY_axi_aw_get,
       RDY_axi_b_put,
       RDY_axi_r_put,
       RDY_axi_w_get,
       RDY_canFetch,
       RDY_fetch,
       RDY_instr,
       RDY_instrReady,
       canFetch,
       instrReady;

  // ports of submodule p
  wire [68 : 0] p$req_r;
  wire [35 : 0] p$axi_w_get;
  wire [34 : 0] p$axi_ar_get, p$axi_aw_get;
  wire [33 : 0] p$axi_r_put;
  wire [31 : 0] p$resp;
  wire [1 : 0] p$axi_b_put;
  wire p$EN_axi_ar_get,
       p$EN_axi_aw_get,
       p$EN_axi_b_put,
       p$EN_axi_r_put,
       p$EN_axi_w_get,
       p$EN_req,
       p$EN_resp,
       p$RDY_axi_ar_get,
       p$RDY_axi_aw_get,
       p$RDY_axi_b_put,
       p$RDY_axi_r_put,
       p$RDY_axi_w_get,
       p$RDY_req,
       p$RDY_resp,
       p$canReq,
       p$respReady;

  // rule scheduling signals
  wire CAN_FIRE_axi_ar_get,
       CAN_FIRE_axi_aw_get,
       CAN_FIRE_axi_b_put,
       CAN_FIRE_axi_r_put,
       CAN_FIRE_axi_w_get,
       CAN_FIRE_fetch,
       CAN_FIRE_instr,
       WILL_FIRE_axi_ar_get,
       WILL_FIRE_axi_aw_get,
       WILL_FIRE_axi_b_put,
       WILL_FIRE_axi_r_put,
       WILL_FIRE_axi_w_get,
       WILL_FIRE_fetch,
       WILL_FIRE_instr;

  // action method fetch
  assign RDY_fetch = p$RDY_req ;
  assign CAN_FIRE_fetch = p$RDY_req ;
  assign WILL_FIRE_fetch = EN_fetch ;

  // actionvalue method instr
  assign instr = p$resp ;
  assign RDY_instr = p$RDY_resp ;
  assign CAN_FIRE_instr = p$RDY_resp ;
  assign WILL_FIRE_instr = EN_instr ;

  // value method canFetch
  assign canFetch = p$canReq ;
  assign RDY_canFetch = 1'd1 ;

  // value method instrReady
  assign instrReady = p$respReady ;
  assign RDY_instrReady = 1'd1 ;

  // actionvalue method axi_aw_get
  assign axi_aw_get = p$axi_aw_get ;
  assign RDY_axi_aw_get = p$RDY_axi_aw_get ;
  assign CAN_FIRE_axi_aw_get = p$RDY_axi_aw_get ;
  assign WILL_FIRE_axi_aw_get = EN_axi_aw_get ;

  // actionvalue method axi_w_get
  assign axi_w_get = p$axi_w_get ;
  assign RDY_axi_w_get = p$RDY_axi_w_get ;
  assign CAN_FIRE_axi_w_get = p$RDY_axi_w_get ;
  assign WILL_FIRE_axi_w_get = EN_axi_w_get ;

  // action method axi_b_put
  assign RDY_axi_b_put = p$RDY_axi_b_put ;
  assign CAN_FIRE_axi_b_put = p$RDY_axi_b_put ;
  assign WILL_FIRE_axi_b_put = EN_axi_b_put ;

  // actionvalue method axi_ar_get
  assign axi_ar_get = p$axi_ar_get ;
  assign RDY_axi_ar_get = p$RDY_axi_ar_get ;
  assign CAN_FIRE_axi_ar_get = p$RDY_axi_ar_get ;
  assign WILL_FIRE_axi_ar_get = EN_axi_ar_get ;

  // action method axi_r_put
  assign RDY_axi_r_put = p$RDY_axi_r_put ;
  assign CAN_FIRE_axi_r_put = p$RDY_axi_r_put ;
  assign WILL_FIRE_axi_r_put = EN_axi_r_put ;

  // submodule p
  mkMemPort p(.CLK(CLK),
	      .RST_N(RST_N),
	      .axi_b_put(p$axi_b_put),
	      .axi_r_put(p$axi_r_put),
	      .req_r(p$req_r),
	      .EN_req(p$EN_req),
	      .EN_resp(p$EN_resp),
	      .EN_axi_aw_get(p$EN_axi_aw_get),
	      .EN_axi_w_get(p$EN_axi_w_get),
	      .EN_axi_b_put(p$EN_axi_b_put),
	      .EN_axi_ar_get(p$EN_axi_ar_get),
	      .EN_axi_r_put(p$EN_axi_r_put),
	      .RDY_req(p$RDY_req),
	      .resp(p$resp),
	      .RDY_resp(p$RDY_resp),
	      .canReq(p$canReq),
	      .RDY_canReq(),
	      .respReady(p$respReady),
	      .RDY_respReady(),
	      .axi_aw_get(p$axi_aw_get),
	      .RDY_axi_aw_get(p$RDY_axi_aw_get),
	      .axi_w_get(p$axi_w_get),
	      .RDY_axi_w_get(p$RDY_axi_w_get),
	      .RDY_axi_b_put(p$RDY_axi_b_put),
	      .axi_ar_get(p$axi_ar_get),
	      .RDY_axi_ar_get(p$RDY_axi_ar_get),
	      .RDY_axi_r_put(p$RDY_axi_r_put));

  // submodule p
  assign p$axi_b_put = axi_b_put ;
  assign p$axi_r_put = axi_r_put ;
  assign p$req_r = { fetch_pc, 37'd0 } ;
  assign p$EN_req = EN_fetch ;
  assign p$EN_resp = EN_instr ;
  assign p$EN_axi_aw_get = EN_axi_aw_get ;
  assign p$EN_axi_w_get = EN_axi_w_get ;
  assign p$EN_axi_b_put = EN_axi_b_put ;
  assign p$EN_axi_ar_get = EN_axi_ar_get ;
  assign p$EN_axi_r_put = EN_axi_r_put ;
endmodule  // mkInstMem

