//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// RDY_req                        O     1
// resp                           O    32 reg
// RDY_resp                       O     1 reg
// canReq                         O     1
// RDY_canReq                     O     1 const
// respReady                      O     1 reg
// RDY_respReady                  O     1 const
// axi_aw_get                     O    35 reg
// RDY_axi_aw_get                 O     1 reg
// axi_w_get                      O    36 reg
// RDY_axi_w_get                  O     1 reg
// RDY_axi_b_put                  O     1 reg
// axi_ar_get                     O    35 reg
// RDY_axi_ar_get                 O     1 reg
// RDY_axi_r_put                  O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// req_r                          I    69
// axi_b_put                      I     2 reg
// axi_r_put                      I    34 reg
// EN_req                         I     1
// EN_axi_b_put                   I     1
// EN_axi_r_put                   I     1
// EN_resp                        I     1
// EN_axi_aw_get                  I     1
// EN_axi_w_get                   I     1
// EN_axi_ar_get                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMemPort(CLK,
		 RST_N,

		 req_r,
		 EN_req,
		 RDY_req,

		 EN_resp,
		 resp,
		 RDY_resp,

		 canReq,
		 RDY_canReq,

		 respReady,
		 RDY_respReady,

		 EN_axi_aw_get,
		 axi_aw_get,
		 RDY_axi_aw_get,

		 EN_axi_w_get,
		 axi_w_get,
		 RDY_axi_w_get,

		 axi_b_put,
		 EN_axi_b_put,
		 RDY_axi_b_put,

		 EN_axi_ar_get,
		 axi_ar_get,
		 RDY_axi_ar_get,

		 axi_r_put,
		 EN_axi_r_put,
		 RDY_axi_r_put);
  input  CLK;
  input  RST_N;

  // action method req
  input  [68 : 0] req_r;
  input  EN_req;
  output RDY_req;

  // actionvalue method resp
  input  EN_resp;
  output [31 : 0] resp;
  output RDY_resp;

  // value method canReq
  output canReq;
  output RDY_canReq;

  // value method respReady
  output respReady;
  output RDY_respReady;

  // actionvalue method axi_aw_get
  input  EN_axi_aw_get;
  output [34 : 0] axi_aw_get;
  output RDY_axi_aw_get;

  // actionvalue method axi_w_get
  input  EN_axi_w_get;
  output [35 : 0] axi_w_get;
  output RDY_axi_w_get;

  // action method axi_b_put
  input  [1 : 0] axi_b_put;
  input  EN_axi_b_put;
  output RDY_axi_b_put;

  // actionvalue method axi_ar_get
  input  EN_axi_ar_get;
  output [34 : 0] axi_ar_get;
  output RDY_axi_ar_get;

  // action method axi_r_put
  input  [33 : 0] axi_r_put;
  input  EN_axi_r_put;
  output RDY_axi_r_put;

  // signals for module outputs
  wire [35 : 0] axi_w_get;
  wire [34 : 0] axi_ar_get, axi_aw_get;
  wire [31 : 0] resp;
  wire RDY_axi_ar_get,
       RDY_axi_aw_get,
       RDY_axi_b_put,
       RDY_axi_r_put,
       RDY_axi_w_get,
       RDY_canReq,
       RDY_req,
       RDY_resp,
       RDY_respReady,
       canReq,
       respReady;

  // register busy
  reg busy;
  wire busy$D_IN, busy$EN;

  // ports of submodule arf
  wire [34 : 0] arf$D_IN, arf$D_OUT;
  wire arf$CLR, arf$DEQ, arf$EMPTY_N, arf$ENQ, arf$FULL_N;

  // ports of submodule awf
  wire [34 : 0] awf$D_IN, awf$D_OUT;
  wire awf$CLR, awf$DEQ, awf$EMPTY_N, awf$ENQ, awf$FULL_N;

  // ports of submodule bf
  wire [1 : 0] bf$D_IN;
  wire bf$CLR, bf$DEQ, bf$EMPTY_N, bf$ENQ, bf$FULL_N;

  // ports of submodule respF
  wire [31 : 0] respF$D_IN, respF$D_OUT;
  wire respF$CLR, respF$DEQ, respF$EMPTY_N, respF$ENQ, respF$FULL_N;

  // ports of submodule rf
  wire [33 : 0] rf$D_IN, rf$D_OUT;
  wire rf$CLR, rf$DEQ, rf$EMPTY_N, rf$ENQ, rf$FULL_N;

  // ports of submodule wf
  wire [35 : 0] wf$D_IN, wf$D_OUT;
  wire wf$CLR, wf$DEQ, wf$EMPTY_N, wf$ENQ, wf$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_collectB,
       CAN_FIRE_RL_collectR,
       CAN_FIRE_axi_ar_get,
       CAN_FIRE_axi_aw_get,
       CAN_FIRE_axi_b_put,
       CAN_FIRE_axi_r_put,
       CAN_FIRE_axi_w_get,
       CAN_FIRE_req,
       CAN_FIRE_resp,
       WILL_FIRE_RL_collectB,
       WILL_FIRE_RL_collectR,
       WILL_FIRE_axi_ar_get,
       WILL_FIRE_axi_aw_get,
       WILL_FIRE_axi_b_put,
       WILL_FIRE_axi_r_put,
       WILL_FIRE_axi_w_get,
       WILL_FIRE_req,
       WILL_FIRE_resp;

  // action method req
  assign RDY_req = !busy && awf$FULL_N && wf$FULL_N && arf$FULL_N ;
  assign CAN_FIRE_req = !busy && awf$FULL_N && wf$FULL_N && arf$FULL_N ;
  assign WILL_FIRE_req = EN_req ;

  // actionvalue method resp
  assign resp = respF$D_OUT ;
  assign RDY_resp = respF$EMPTY_N ;
  assign CAN_FIRE_resp = respF$EMPTY_N ;
  assign WILL_FIRE_resp = EN_resp ;

  // value method canReq
  assign canReq = !busy ;
  assign RDY_canReq = 1'd1 ;

  // value method respReady
  assign respReady = respF$EMPTY_N ;
  assign RDY_respReady = 1'd1 ;

  // actionvalue method axi_aw_get
  assign axi_aw_get = awf$D_OUT ;
  assign RDY_axi_aw_get = awf$EMPTY_N ;
  assign CAN_FIRE_axi_aw_get = awf$EMPTY_N ;
  assign WILL_FIRE_axi_aw_get = EN_axi_aw_get ;

  // actionvalue method axi_w_get
  assign axi_w_get = wf$D_OUT ;
  assign RDY_axi_w_get = wf$EMPTY_N ;
  assign CAN_FIRE_axi_w_get = wf$EMPTY_N ;
  assign WILL_FIRE_axi_w_get = EN_axi_w_get ;

  // action method axi_b_put
  assign RDY_axi_b_put = bf$FULL_N ;
  assign CAN_FIRE_axi_b_put = bf$FULL_N ;
  assign WILL_FIRE_axi_b_put = EN_axi_b_put ;

  // actionvalue method axi_ar_get
  assign axi_ar_get = arf$D_OUT ;
  assign RDY_axi_ar_get = arf$EMPTY_N ;
  assign CAN_FIRE_axi_ar_get = arf$EMPTY_N ;
  assign WILL_FIRE_axi_ar_get = EN_axi_ar_get ;

  // action method axi_r_put
  assign RDY_axi_r_put = rf$FULL_N ;
  assign CAN_FIRE_axi_r_put = rf$FULL_N ;
  assign WILL_FIRE_axi_r_put = EN_axi_r_put ;

  // submodule arf
  FIFO2 #(.width(32'd35), .guarded(1'd1)) arf(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(arf$D_IN),
					      .ENQ(arf$ENQ),
					      .DEQ(arf$DEQ),
					      .CLR(arf$CLR),
					      .D_OUT(arf$D_OUT),
					      .FULL_N(arf$FULL_N),
					      .EMPTY_N(arf$EMPTY_N));

  // submodule awf
  FIFO2 #(.width(32'd35), .guarded(1'd1)) awf(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(awf$D_IN),
					      .ENQ(awf$ENQ),
					      .DEQ(awf$DEQ),
					      .CLR(awf$CLR),
					      .D_OUT(awf$D_OUT),
					      .FULL_N(awf$FULL_N),
					      .EMPTY_N(awf$EMPTY_N));

  // submodule bf
  FIFO2 #(.width(32'd2), .guarded(1'd1)) bf(.RST(RST_N),
					    .CLK(CLK),
					    .D_IN(bf$D_IN),
					    .ENQ(bf$ENQ),
					    .DEQ(bf$DEQ),
					    .CLR(bf$CLR),
					    .D_OUT(),
					    .FULL_N(bf$FULL_N),
					    .EMPTY_N(bf$EMPTY_N));

  // submodule respF
  FIFO2 #(.width(32'd32), .guarded(1'd1)) respF(.RST(RST_N),
						.CLK(CLK),
						.D_IN(respF$D_IN),
						.ENQ(respF$ENQ),
						.DEQ(respF$DEQ),
						.CLR(respF$CLR),
						.D_OUT(respF$D_OUT),
						.FULL_N(respF$FULL_N),
						.EMPTY_N(respF$EMPTY_N));

  // submodule rf
  FIFO2 #(.width(32'd34), .guarded(1'd1)) rf(.RST(RST_N),
					     .CLK(CLK),
					     .D_IN(rf$D_IN),
					     .ENQ(rf$ENQ),
					     .DEQ(rf$DEQ),
					     .CLR(rf$CLR),
					     .D_OUT(rf$D_OUT),
					     .FULL_N(rf$FULL_N),
					     .EMPTY_N(rf$EMPTY_N));

  // submodule wf
  FIFO2 #(.width(32'd36), .guarded(1'd1)) wf(.RST(RST_N),
					     .CLK(CLK),
					     .D_IN(wf$D_IN),
					     .ENQ(wf$ENQ),
					     .DEQ(wf$DEQ),
					     .CLR(wf$CLR),
					     .D_OUT(wf$D_OUT),
					     .FULL_N(wf$FULL_N),
					     .EMPTY_N(wf$EMPTY_N));

  // rule RL_collectR
  assign CAN_FIRE_RL_collectR = rf$EMPTY_N && respF$FULL_N ;
  assign WILL_FIRE_RL_collectR = CAN_FIRE_RL_collectR ;

  // rule RL_collectB
  assign CAN_FIRE_RL_collectB = respF$FULL_N && bf$EMPTY_N ;
  assign WILL_FIRE_RL_collectB =
	     CAN_FIRE_RL_collectB && !WILL_FIRE_RL_collectR ;

  // register busy
  assign busy$D_IN = !WILL_FIRE_RL_collectB && !WILL_FIRE_RL_collectR ;
  assign busy$EN = WILL_FIRE_RL_collectB || WILL_FIRE_RL_collectR || EN_req ;

  // submodule arf
  assign arf$D_IN = { req_r[68:37], 3'd0 } ;
  assign arf$ENQ = EN_req && !req_r[36] ;
  assign arf$DEQ = EN_axi_ar_get ;
  assign arf$CLR = 1'b0 ;

  // submodule awf
  assign awf$D_IN = { req_r[68:37], 3'd0 } ;
  assign awf$ENQ = EN_req && req_r[36] ;
  assign awf$DEQ = EN_axi_aw_get ;
  assign awf$CLR = 1'b0 ;

  // submodule bf
  assign bf$D_IN = axi_b_put ;
  assign bf$ENQ = EN_axi_b_put ;
  assign bf$DEQ = CAN_FIRE_RL_collectB && !WILL_FIRE_RL_collectR ;
  assign bf$CLR = 1'b0 ;

  // submodule respF
  assign respF$D_IN = WILL_FIRE_RL_collectR ? rf$D_OUT[33:2] : 32'd0 ;
  assign respF$ENQ = WILL_FIRE_RL_collectR || WILL_FIRE_RL_collectB ;
  assign respF$DEQ = EN_resp ;
  assign respF$CLR = 1'b0 ;

  // submodule rf
  assign rf$D_IN = axi_r_put ;
  assign rf$ENQ = EN_axi_r_put ;
  assign rf$DEQ = rf$EMPTY_N && respF$FULL_N ;
  assign rf$CLR = 1'b0 ;

  // submodule wf
  assign wf$D_IN = req_r[35:0] ;
  assign wf$ENQ = EN_req && req_r[36] ;
  assign wf$DEQ = EN_axi_w_get ;
  assign wf$CLR = 1'b0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        busy <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (busy$EN) busy <= `BSV_ASSIGNMENT_DELAY busy$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    busy = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMemPort

