//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// RDY_start                      O     1
// busy                           O     1
// RDY_busy                       O     1 const
// done                           O     1
// RDY_done                       O     1 const
// result                         O    32 reg
// RDY_result                     O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_op                       I     3
// start_a                        I    32
// start_b                        I    32
// EN_start                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMulDiv(CLK,
		RST_N,

		start_op,
		start_a,
		start_b,
		EN_start,
		RDY_start,

		busy,
		RDY_busy,

		done,
		RDY_done,

		result,
		RDY_result);
  input  CLK;
  input  RST_N;

  // action method start
  input  [2 : 0] start_op;
  input  [31 : 0] start_a;
  input  [31 : 0] start_b;
  input  EN_start;
  output RDY_start;

  // value method busy
  output busy;
  output RDY_busy;

  // value method done
  output done;
  output RDY_done;

  // value method result
  output [31 : 0] result;
  output RDY_result;

  // signals for module outputs
  wire [31 : 0] result;
  wire RDY_busy, RDY_done, RDY_result, RDY_start, busy, done;

  // register acc
  reg [63 : 0] acc;
  wire [63 : 0] acc$D_IN;
  wire acc$EN;

  // register cnt
  reg [5 : 0] cnt;
  wire [5 : 0] cnt$D_IN;
  wire cnt$EN;

  // register divisor
  reg [31 : 0] divisor;
  reg [31 : 0] divisor$D_IN;
  wire divisor$EN;

  // register isDiv
  reg isDiv;
  wire isDiv$D_IN, isDiv$EN;

  // register mcand
  reg [63 : 0] mcand;
  wire [63 : 0] mcand$D_IN;
  wire mcand$EN;

  // register mplier
  reg [31 : 0] mplier;
  wire [31 : 0] mplier$D_IN;
  wire mplier$EN;

  // register opR
  reg [2 : 0] opR;
  wire [2 : 0] opR$D_IN;
  wire opR$EN;

  // register pNeg
  reg pNeg;
  wire pNeg$D_IN, pNeg$EN;

  // register qNeg
  reg qNeg;
  wire qNeg$D_IN, qNeg$EN;

  // register quotient
  reg [31 : 0] quotient;
  wire [31 : 0] quotient$D_IN;
  wire quotient$EN;

  // register rNeg
  reg rNeg;
  wire rNeg$D_IN, rNeg$EN;

  // register remainder
  reg [31 : 0] remainder;
  wire [31 : 0] remainder$D_IN;
  wire remainder$EN;

  // register resR
  reg [31 : 0] resR;
  wire [31 : 0] resR$D_IN;
  wire resR$EN;

  // register st
  reg [1 : 0] st;
  reg [1 : 0] st$D_IN;
  wire st$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_divStep,
       CAN_FIRE_RL_finish,
       CAN_FIRE_RL_mulStep,
       CAN_FIRE_start,
       WILL_FIRE_RL_divStep,
       WILL_FIRE_RL_finish,
       WILL_FIRE_RL_mulStep,
       WILL_FIRE_start;

  // inputs to muxes for submodule ports
  reg [31 : 0] MUX_quotient$write_1__VAL_1;
  wire [63 : 0] MUX_acc$write_1__VAL_1,
		MUX_mcand$write_1__VAL_1,
		MUX_mcand$write_1__VAL_2;
  wire [31 : 0] MUX_mplier$write_1__VAL_1,
		MUX_mplier$write_1__VAL_2,
		MUX_quotient$write_1__VAL_2,
		MUX_remainder$write_1__VAL_2,
		MUX_resR$write_1__VAL_1,
		MUX_resR$write_1__VAL_2;
  wire [5 : 0] MUX_cnt$write_1__VAL_1;
  wire [1 : 0] MUX_st$write_1__VAL_2;
  wire MUX_acc$write_1__SEL_1,
       MUX_acc$write_1__SEL_2,
       MUX_quotient$write_1__SEL_1,
       MUX_resR$write_1__SEL_1,
       MUX_st$write_1__PSEL_1,
       MUX_st$write_1__SEL_1;

  // remaining internal signals
  reg [31 : 0] out__h1145, x__h1425;
  wire [63 : 0] IF_pNeg_9_THEN_INV_acc_0_PLUS_1_1_ELSE_acc___d52;
  wire [32 : 0] r__h668,
		remainder_9_CONCAT_quotient_0_BIT_31_1_2_MINUS_ETC___d25;
  wire [31 : 0] IF_start_a_BIT_31_5_THEN_INV_start_a_7_PLUS_1__ETC___d112,
		IF_start_b_BIT_31_1_THEN_INV_start_b_3_PLUS_1__ETC___d110,
		INV_start_a_7_PLUS_1___d88,
		INV_start_b_3_PLUS_1___d94,
		out__h1086,
		q__h1143,
		rem__h1144,
		x__h1459,
		x__h1567,
		x__h1699,
		x__h890;
  wire NOT_start_b_EQ_0_1_02_AND_NOT_start_op_EQ_4_7__ETC___d108,
       start_b_EQ_0_1_OR_start_op_EQ_4_7_OR_start_op__ETC___d77;

  // action method start
  assign RDY_start = st == 2'd0 ;
  assign CAN_FIRE_start = st == 2'd0 ;
  assign WILL_FIRE_start = EN_start ;

  // value method busy
  assign busy = st != 2'd0 ;
  assign RDY_busy = 1'd1 ;

  // value method done
  assign done = st == 2'd0 ;
  assign RDY_done = 1'd1 ;

  // value method result
  assign result = resR ;
  assign RDY_result = 1'd1 ;

  // rule RL_mulStep
  assign CAN_FIRE_RL_mulStep = st == 2'd1 && !isDiv ;
  assign WILL_FIRE_RL_mulStep = CAN_FIRE_RL_mulStep ;

  // rule RL_divStep
  assign CAN_FIRE_RL_divStep = st == 2'd1 && isDiv ;
  assign WILL_FIRE_RL_divStep = CAN_FIRE_RL_divStep ;

  // rule RL_finish
  assign CAN_FIRE_RL_finish = st == 2'd2 ;
  assign WILL_FIRE_RL_finish = CAN_FIRE_RL_finish ;

  // inputs to muxes for submodule ports
  assign MUX_acc$write_1__SEL_1 = WILL_FIRE_RL_mulStep && mplier[0] ;
  assign MUX_acc$write_1__SEL_2 =
	     EN_start && start_op != 3'd4 && start_op != 3'd5 &&
	     start_op != 3'd6 &&
	     start_op != 3'd7 ;
  assign MUX_quotient$write_1__SEL_1 =
	     EN_start &&
	     (start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	      start_op == 3'd7) &&
	     NOT_start_b_EQ_0_1_02_AND_NOT_start_op_EQ_4_7__ETC___d108 ;
  assign MUX_resR$write_1__SEL_1 =
	     EN_start &&
	     (start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	      start_op == 3'd7) &&
	     start_b_EQ_0_1_OR_start_op_EQ_4_7_OR_start_op__ETC___d77 ;
  assign MUX_st$write_1__PSEL_1 =
	     WILL_FIRE_RL_divStep || WILL_FIRE_RL_mulStep ;
  assign MUX_st$write_1__SEL_1 = MUX_st$write_1__PSEL_1 && cnt == 6'd31 ;
  assign MUX_acc$write_1__VAL_1 = acc + mcand ;
  assign MUX_cnt$write_1__VAL_1 = cnt + 6'd1 ;
  assign MUX_mcand$write_1__VAL_1 = { 32'd0, x__h1567 } ;
  assign MUX_mcand$write_1__VAL_2 = { mcand[62:0], 1'd0 } ;
  assign MUX_mplier$write_1__VAL_1 =
	     ((start_op == 3'd0 || start_op == 3'd1) && start_b[31]) ?
	       INV_start_b_3_PLUS_1___d94 :
	       start_b ;
  assign MUX_mplier$write_1__VAL_2 = { 1'd0, mplier[31:1] } ;
  always@(start_op or
	  start_a or
	  IF_start_a_BIT_31_5_THEN_INV_start_a_7_PLUS_1__ETC___d112)
  begin
    case (start_op)
      3'd4, 3'd6:
	  MUX_quotient$write_1__VAL_1 =
	      IF_start_a_BIT_31_5_THEN_INV_start_a_7_PLUS_1__ETC___d112;
      default: MUX_quotient$write_1__VAL_1 = start_a;
    endcase
  end
  assign MUX_quotient$write_1__VAL_2 =
	     { quotient[30:0],
	       !remainder_9_CONCAT_quotient_0_BIT_31_1_2_MINUS_ETC___d25[32] } ;
  assign MUX_remainder$write_1__VAL_2 =
	     remainder_9_CONCAT_quotient_0_BIT_31_1_2_MINUS_ETC___d25[32] ?
	       x__h890 :
	       remainder_9_CONCAT_quotient_0_BIT_31_1_2_MINUS_ETC___d25[31:0] ;
  assign MUX_resR$write_1__VAL_1 = (start_b == 32'd0) ? x__h1425 : x__h1459 ;
  assign MUX_resR$write_1__VAL_2 = isDiv ? out__h1145 : out__h1086 ;
  assign MUX_st$write_1__VAL_2 =
	     (start_op != 3'd4 && start_op != 3'd5 && start_op != 3'd6 &&
	      start_op != 3'd7) ?
	       2'd1 :
	       (start_b_EQ_0_1_OR_start_op_EQ_4_7_OR_start_op__ETC___d77 ?
		  2'd0 :
		  2'd1) ;

  // register acc
  assign acc$D_IN = MUX_acc$write_1__SEL_1 ? MUX_acc$write_1__VAL_1 : 64'd0 ;
  assign acc$EN =
	     WILL_FIRE_RL_mulStep && mplier[0] ||
	     EN_start && start_op != 3'd4 && start_op != 3'd5 &&
	     start_op != 3'd6 &&
	     start_op != 3'd7 ;

  // register cnt
  assign cnt$D_IN = MUX_st$write_1__PSEL_1 ? MUX_cnt$write_1__VAL_1 : 6'd0 ;
  assign cnt$EN = WILL_FIRE_RL_divStep || WILL_FIRE_RL_mulStep || EN_start ;

  // register divisor
  always@(start_op or
	  start_b or
	  IF_start_b_BIT_31_1_THEN_INV_start_b_3_PLUS_1__ETC___d110)
  begin
    case (start_op)
      3'd4, 3'd6:
	  divisor$D_IN =
	      IF_start_b_BIT_31_1_THEN_INV_start_b_3_PLUS_1__ETC___d110;
      default: divisor$D_IN = start_b;
    endcase
  end
  assign divisor$EN = MUX_quotient$write_1__SEL_1 ;

  // register isDiv
  assign isDiv$D_IN =
	     start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	     start_op == 3'd7 ;
  assign isDiv$EN = EN_start ;

  // register mcand
  assign mcand$D_IN =
	     MUX_acc$write_1__SEL_2 ?
	       MUX_mcand$write_1__VAL_1 :
	       MUX_mcand$write_1__VAL_2 ;
  assign mcand$EN =
	     EN_start && start_op != 3'd4 && start_op != 3'd5 &&
	     start_op != 3'd6 &&
	     start_op != 3'd7 ||
	     WILL_FIRE_RL_mulStep ;

  // register mplier
  assign mplier$D_IN =
	     MUX_acc$write_1__SEL_2 ?
	       MUX_mplier$write_1__VAL_1 :
	       MUX_mplier$write_1__VAL_2 ;
  assign mplier$EN =
	     EN_start && start_op != 3'd4 && start_op != 3'd5 &&
	     start_op != 3'd6 &&
	     start_op != 3'd7 ||
	     WILL_FIRE_RL_mulStep ;

  // register opR
  assign opR$D_IN = start_op ;
  assign opR$EN = EN_start ;

  // register pNeg
  assign pNeg$D_IN =
	     ((start_op == 3'd0 || start_op == 3'd1 || start_op == 3'd2) &&
	      start_a[31]) !=
	     ((start_op == 3'd0 || start_op == 3'd1) && start_b[31]) ;
  assign pNeg$EN = MUX_acc$write_1__SEL_2 ;

  // register qNeg
  assign qNeg$D_IN =
	     (start_op == 3'd4 || start_op == 3'd6) &&
	     start_a[31] != start_b[31] ;
  assign qNeg$EN = MUX_quotient$write_1__SEL_1 ;

  // register quotient
  assign quotient$D_IN =
	     MUX_quotient$write_1__SEL_1 ?
	       MUX_quotient$write_1__VAL_1 :
	       MUX_quotient$write_1__VAL_2 ;
  assign quotient$EN =
	     EN_start &&
	     (start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	      start_op == 3'd7) &&
	     NOT_start_b_EQ_0_1_02_AND_NOT_start_op_EQ_4_7__ETC___d108 ||
	     WILL_FIRE_RL_divStep ;

  // register rNeg
  assign rNeg$D_IN = (start_op == 3'd4 || start_op == 3'd6) && start_a[31] ;
  assign rNeg$EN = MUX_quotient$write_1__SEL_1 ;

  // register remainder
  assign remainder$D_IN =
	     MUX_quotient$write_1__SEL_1 ?
	       32'd0 :
	       MUX_remainder$write_1__VAL_2 ;
  assign remainder$EN =
	     EN_start &&
	     (start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	      start_op == 3'd7) &&
	     NOT_start_b_EQ_0_1_02_AND_NOT_start_op_EQ_4_7__ETC___d108 ||
	     WILL_FIRE_RL_divStep ;

  // register resR
  assign resR$D_IN =
	     MUX_resR$write_1__SEL_1 ?
	       MUX_resR$write_1__VAL_1 :
	       MUX_resR$write_1__VAL_2 ;
  assign resR$EN =
	     EN_start &&
	     (start_op == 3'd4 || start_op == 3'd5 || start_op == 3'd6 ||
	      start_op == 3'd7) &&
	     start_b_EQ_0_1_OR_start_op_EQ_4_7_OR_start_op__ETC___d77 ||
	     WILL_FIRE_RL_finish ;

  // register st
  always@(MUX_st$write_1__SEL_1 or
	  EN_start or MUX_st$write_1__VAL_2 or WILL_FIRE_RL_finish)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_st$write_1__SEL_1: st$D_IN = 2'd2;
      EN_start: st$D_IN = MUX_st$write_1__VAL_2;
      WILL_FIRE_RL_finish: st$D_IN = 2'd0;
      default: st$D_IN = 2'b10 /* unspecified value */ ;
    endcase
  end
  assign st$EN =
	     (WILL_FIRE_RL_divStep || WILL_FIRE_RL_mulStep) && cnt == 6'd31 ||
	     EN_start ||
	     WILL_FIRE_RL_finish ;

  // remaining internal signals
  assign IF_pNeg_9_THEN_INV_acc_0_PLUS_1_1_ELSE_acc___d52 =
	     pNeg ? ~acc + 64'd1 : acc ;
  assign IF_start_a_BIT_31_5_THEN_INV_start_a_7_PLUS_1__ETC___d112 =
	     start_a[31] ? INV_start_a_7_PLUS_1___d88 : start_a ;
  assign IF_start_b_BIT_31_1_THEN_INV_start_b_3_PLUS_1__ETC___d110 =
	     start_b[31] ? INV_start_b_3_PLUS_1___d94 : start_b ;
  assign INV_start_a_7_PLUS_1___d88 = ~start_a + 32'd1 ;
  assign INV_start_b_3_PLUS_1___d94 = x__h1699 + 32'd1 ;
  assign NOT_start_b_EQ_0_1_02_AND_NOT_start_op_EQ_4_7__ETC___d108 =
	     start_b != 32'd0 &&
	     (start_op != 3'd4 && start_op != 3'd6 ||
	      start_a != 32'h80000000 ||
	      start_b != 32'hFFFFFFFF) ;
  assign out__h1086 =
	     (opR == 3'd0) ?
	       IF_pNeg_9_THEN_INV_acc_0_PLUS_1_1_ELSE_acc___d52[31:0] :
	       IF_pNeg_9_THEN_INV_acc_0_PLUS_1_1_ELSE_acc___d52[63:32] ;
  assign q__h1143 = qNeg ? ~quotient + 32'd1 : quotient ;
  assign r__h668 = { remainder, quotient[31] } ;
  assign rem__h1144 = rNeg ? ~remainder + 32'd1 : remainder ;
  assign remainder_9_CONCAT_quotient_0_BIT_31_1_2_MINUS_ETC___d25 =
	     r__h668 - { 1'b0, divisor } ;
  assign start_b_EQ_0_1_OR_start_op_EQ_4_7_OR_start_op__ETC___d77 =
	     start_b == 32'd0 ||
	     (start_op == 3'd4 || start_op == 3'd6) &&
	     start_a == 32'h80000000 &&
	     start_b == 32'hFFFFFFFF ;
  assign x__h1459 = (start_op == 3'd4) ? 32'h80000000 : 32'd0 ;
  assign x__h1567 =
	     ((start_op == 3'd0 || start_op == 3'd1 || start_op == 3'd2) &&
	      start_a[31]) ?
	       INV_start_a_7_PLUS_1___d88 :
	       start_a ;
  assign x__h1699 = ~start_b ;
  assign x__h890 = { remainder[30:0], quotient[31] } ;
  always@(opR or rem__h1144 or q__h1143)
  begin
    case (opR)
      3'd4, 3'd5: out__h1145 = q__h1143;
      default: out__h1145 = rem__h1144;
    endcase
  end
  always@(start_op or start_a)
  begin
    case (start_op)
      3'd4, 3'd5: x__h1425 = 32'hFFFFFFFF;
      default: x__h1425 = start_a;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cnt <= `BSV_ASSIGNMENT_DELAY 6'd0;
	st <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (cnt$EN) cnt <= `BSV_ASSIGNMENT_DELAY cnt$D_IN;
	if (st$EN) st <= `BSV_ASSIGNMENT_DELAY st$D_IN;
      end
    if (acc$EN) acc <= `BSV_ASSIGNMENT_DELAY acc$D_IN;
    if (divisor$EN) divisor <= `BSV_ASSIGNMENT_DELAY divisor$D_IN;
    if (isDiv$EN) isDiv <= `BSV_ASSIGNMENT_DELAY isDiv$D_IN;
    if (mcand$EN) mcand <= `BSV_ASSIGNMENT_DELAY mcand$D_IN;
    if (mplier$EN) mplier <= `BSV_ASSIGNMENT_DELAY mplier$D_IN;
    if (opR$EN) opR <= `BSV_ASSIGNMENT_DELAY opR$D_IN;
    if (pNeg$EN) pNeg <= `BSV_ASSIGNMENT_DELAY pNeg$D_IN;
    if (qNeg$EN) qNeg <= `BSV_ASSIGNMENT_DELAY qNeg$D_IN;
    if (quotient$EN) quotient <= `BSV_ASSIGNMENT_DELAY quotient$D_IN;
    if (rNeg$EN) rNeg <= `BSV_ASSIGNMENT_DELAY rNeg$D_IN;
    if (remainder$EN) remainder <= `BSV_ASSIGNMENT_DELAY remainder$D_IN;
    if (resR$EN) resR <= `BSV_ASSIGNMENT_DELAY resR$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    acc = 64'hAAAAAAAAAAAAAAAA;
    cnt = 6'h2A;
    divisor = 32'hAAAAAAAA;
    isDiv = 1'h0;
    mcand = 64'hAAAAAAAAAAAAAAAA;
    mplier = 32'hAAAAAAAA;
    opR = 3'h2;
    pNeg = 1'h0;
    qNeg = 1'h0;
    quotient = 32'hAAAAAAAA;
    rNeg = 1'h0;
    remainder = 32'hAAAAAAAA;
    resR = 32'hAAAAAAAA;
    st = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMulDiv

