//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// pc                             O    32 reg
// RDY_pc                         O     1 const
// RDY_advance                    O     1 const
// RDY_redirect                   O     1 const
// RDY_dbgSet                     O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// advance_nxt                    I    32
// redirect_tgt                   I    32
// dbgSet_v                       I    32
// EN_advance                     I     1
// EN_redirect                    I     1
// EN_dbgSet                      I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkProgramCounter(CLK,
			RST_N,

			pc,
			RDY_pc,

			advance_nxt,
			EN_advance,
			RDY_advance,

			redirect_tgt,
			EN_redirect,
			RDY_redirect,

			dbgSet_v,
			EN_dbgSet,
			RDY_dbgSet);
  input  CLK;
  input  RST_N;

  // value method pc
  output [31 : 0] pc;
  output RDY_pc;

  // action method advance
  input  [31 : 0] advance_nxt;
  input  EN_advance;
  output RDY_advance;

  // action method redirect
  input  [31 : 0] redirect_tgt;
  input  EN_redirect;
  output RDY_redirect;

  // action method dbgSet
  input  [31 : 0] dbgSet_v;
  input  EN_dbgSet;
  output RDY_dbgSet;

  // signals for module outputs
  wire [31 : 0] pc;
  wire RDY_advance, RDY_dbgSet, RDY_pc, RDY_redirect;

  // register r_r
  reg [31 : 0] r_r;
  wire [31 : 0] r_r$D_IN;
  wire r_r$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_r_canonicalize,
       CAN_FIRE_advance,
       CAN_FIRE_dbgSet,
       CAN_FIRE_redirect,
       WILL_FIRE_RL_r_canonicalize,
       WILL_FIRE_advance,
       WILL_FIRE_dbgSet,
       WILL_FIRE_redirect;

  // remaining internal signals
  wire [31 : 0] def__h408, def__h525;

  // value method pc
  assign pc = r_r ;
  assign RDY_pc = 1'd1 ;

  // action method advance
  assign RDY_advance = 1'd1 ;
  assign CAN_FIRE_advance = 1'd1 ;
  assign WILL_FIRE_advance = EN_advance ;

  // action method redirect
  assign RDY_redirect = 1'd1 ;
  assign CAN_FIRE_redirect = 1'd1 ;
  assign WILL_FIRE_redirect = EN_redirect ;

  // action method dbgSet
  assign RDY_dbgSet = 1'd1 ;
  assign CAN_FIRE_dbgSet = 1'd1 ;
  assign WILL_FIRE_dbgSet = EN_dbgSet ;

  // rule RL_r_canonicalize
  assign CAN_FIRE_RL_r_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_r_canonicalize = 1'd1 ;

  // register r_r
  assign r_r$D_IN = EN_dbgSet ? dbgSet_v : def__h408 ;
  assign r_r$EN = 1'd1 ;

  // remaining internal signals
  assign def__h408 = EN_redirect ? redirect_tgt : def__h525 ;
  assign def__h525 = EN_advance ? advance_nxt : r_r ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        r_r <= `BSV_ASSIGNMENT_DELAY 32'h0;
      end
    else
      begin
        if (r_r$EN) r_r <= `BSV_ASSIGNMENT_DELAY r_r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    r_r = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkProgramCounter

