//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// read1                          O    32
// RDY_read1                      O     1 const
// read2                          O    32
// RDY_read2                      O     1 const
// RDY_write                      O     1 const
// dbgRead                        O    32
// RDY_dbgRead                    O     1 const
// RDY_dbgWrite                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// read1_a                        I     5
// read2_a                        I     5
// write_a                        I     5
// write_d                        I    32
// dbgRead_a                      I     5
// dbgWrite_a                     I     5
// dbgWrite_d                     I    32
// EN_write                       I     1
// EN_dbgWrite                    I     1
//
// Combinational paths from inputs to outputs:
//   (read1_a,
//    write_a,
//    write_d,
//    dbgWrite_a,
//    dbgWrite_d,
//    EN_write,
//    EN_dbgWrite) -> read1
//   (read2_a,
//    write_a,
//    write_d,
//    dbgWrite_a,
//    dbgWrite_d,
//    EN_write,
//    EN_dbgWrite) -> read2
//   dbgRead_a -> dbgRead
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRegFile(CLK,
		 RST_N,

		 read1_a,
		 read1,
		 RDY_read1,

		 read2_a,
		 read2,
		 RDY_read2,

		 write_a,
		 write_d,
		 EN_write,
		 RDY_write,

		 dbgRead_a,
		 dbgRead,
		 RDY_dbgRead,

		 dbgWrite_a,
		 dbgWrite_d,
		 EN_dbgWrite,
		 RDY_dbgWrite);
  input  CLK;
  input  RST_N;

  // value method read1
  input  [4 : 0] read1_a;
  output [31 : 0] read1;
  output RDY_read1;

  // value method read2
  input  [4 : 0] read2_a;
  output [31 : 0] read2;
  output RDY_read2;

  // action method write
  input  [4 : 0] write_a;
  input  [31 : 0] write_d;
  input  EN_write;
  output RDY_write;

  // value method dbgRead
  input  [4 : 0] dbgRead_a;
  output [31 : 0] dbgRead;
  output RDY_dbgRead;

  // action method dbgWrite
  input  [4 : 0] dbgWrite_a;
  input  [31 : 0] dbgWrite_d;
  input  EN_dbgWrite;
  output RDY_dbgWrite;

  // signals for module outputs
  reg [31 : 0] dbgRead, read1, read2;
  wire RDY_dbgRead, RDY_dbgWrite, RDY_read1, RDY_read2, RDY_write;

  // inlined wires
  wire rf_10_w_0$whas,
       rf_10_w_1$whas,
       rf_11_w_0$whas,
       rf_11_w_1$whas,
       rf_12_w_0$whas,
       rf_12_w_1$whas,
       rf_13_w_0$whas,
       rf_13_w_1$whas,
       rf_14_w_0$whas,
       rf_14_w_1$whas,
       rf_15_w_0$whas,
       rf_15_w_1$whas,
       rf_16_w_0$whas,
       rf_16_w_1$whas,
       rf_17_w_0$whas,
       rf_17_w_1$whas,
       rf_18_w_0$whas,
       rf_18_w_1$whas,
       rf_19_w_0$whas,
       rf_19_w_1$whas,
       rf_1_w_0$whas,
       rf_1_w_1$whas,
       rf_20_w_0$whas,
       rf_20_w_1$whas,
       rf_21_w_0$whas,
       rf_21_w_1$whas,
       rf_22_w_0$whas,
       rf_22_w_1$whas,
       rf_23_w_0$whas,
       rf_23_w_1$whas,
       rf_24_w_0$whas,
       rf_24_w_1$whas,
       rf_25_w_0$whas,
       rf_25_w_1$whas,
       rf_26_w_0$whas,
       rf_26_w_1$whas,
       rf_27_w_0$whas,
       rf_27_w_1$whas,
       rf_28_w_0$whas,
       rf_28_w_1$whas,
       rf_29_w_0$whas,
       rf_29_w_1$whas,
       rf_2_w_0$whas,
       rf_2_w_1$whas,
       rf_30_w_0$whas,
       rf_30_w_1$whas,
       rf_31_w_0$whas,
       rf_31_w_1$whas,
       rf_3_w_0$whas,
       rf_3_w_1$whas,
       rf_4_w_0$whas,
       rf_4_w_1$whas,
       rf_5_w_0$whas,
       rf_5_w_1$whas,
       rf_6_w_0$whas,
       rf_6_w_1$whas,
       rf_7_w_0$whas,
       rf_7_w_1$whas,
       rf_8_w_0$whas,
       rf_8_w_1$whas,
       rf_9_w_0$whas,
       rf_9_w_1$whas;

  // register rf_0_r
  reg [31 : 0] rf_0_r;
  wire [31 : 0] rf_0_r$D_IN;
  wire rf_0_r$EN;

  // register rf_10_r
  reg [31 : 0] rf_10_r;
  wire [31 : 0] rf_10_r$D_IN;
  wire rf_10_r$EN;

  // register rf_11_r
  reg [31 : 0] rf_11_r;
  wire [31 : 0] rf_11_r$D_IN;
  wire rf_11_r$EN;

  // register rf_12_r
  reg [31 : 0] rf_12_r;
  wire [31 : 0] rf_12_r$D_IN;
  wire rf_12_r$EN;

  // register rf_13_r
  reg [31 : 0] rf_13_r;
  wire [31 : 0] rf_13_r$D_IN;
  wire rf_13_r$EN;

  // register rf_14_r
  reg [31 : 0] rf_14_r;
  wire [31 : 0] rf_14_r$D_IN;
  wire rf_14_r$EN;

  // register rf_15_r
  reg [31 : 0] rf_15_r;
  wire [31 : 0] rf_15_r$D_IN;
  wire rf_15_r$EN;

  // register rf_16_r
  reg [31 : 0] rf_16_r;
  wire [31 : 0] rf_16_r$D_IN;
  wire rf_16_r$EN;

  // register rf_17_r
  reg [31 : 0] rf_17_r;
  wire [31 : 0] rf_17_r$D_IN;
  wire rf_17_r$EN;

  // register rf_18_r
  reg [31 : 0] rf_18_r;
  wire [31 : 0] rf_18_r$D_IN;
  wire rf_18_r$EN;

  // register rf_19_r
  reg [31 : 0] rf_19_r;
  wire [31 : 0] rf_19_r$D_IN;
  wire rf_19_r$EN;

  // register rf_1_r
  reg [31 : 0] rf_1_r;
  wire [31 : 0] rf_1_r$D_IN;
  wire rf_1_r$EN;

  // register rf_20_r
  reg [31 : 0] rf_20_r;
  wire [31 : 0] rf_20_r$D_IN;
  wire rf_20_r$EN;

  // register rf_21_r
  reg [31 : 0] rf_21_r;
  wire [31 : 0] rf_21_r$D_IN;
  wire rf_21_r$EN;

  // register rf_22_r
  reg [31 : 0] rf_22_r;
  wire [31 : 0] rf_22_r$D_IN;
  wire rf_22_r$EN;

  // register rf_23_r
  reg [31 : 0] rf_23_r;
  wire [31 : 0] rf_23_r$D_IN;
  wire rf_23_r$EN;

  // register rf_24_r
  reg [31 : 0] rf_24_r;
  wire [31 : 0] rf_24_r$D_IN;
  wire rf_24_r$EN;

  // register rf_25_r
  reg [31 : 0] rf_25_r;
  wire [31 : 0] rf_25_r$D_IN;
  wire rf_25_r$EN;

  // register rf_26_r
  reg [31 : 0] rf_26_r;
  wire [31 : 0] rf_26_r$D_IN;
  wire rf_26_r$EN;

  // register rf_27_r
  reg [31 : 0] rf_27_r;
  wire [31 : 0] rf_27_r$D_IN;
  wire rf_27_r$EN;

  // register rf_28_r
  reg [31 : 0] rf_28_r;
  wire [31 : 0] rf_28_r$D_IN;
  wire rf_28_r$EN;

  // register rf_29_r
  reg [31 : 0] rf_29_r;
  wire [31 : 0] rf_29_r$D_IN;
  wire rf_29_r$EN;

  // register rf_2_r
  reg [31 : 0] rf_2_r;
  wire [31 : 0] rf_2_r$D_IN;
  wire rf_2_r$EN;

  // register rf_30_r
  reg [31 : 0] rf_30_r;
  wire [31 : 0] rf_30_r$D_IN;
  wire rf_30_r$EN;

  // register rf_31_r
  reg [31 : 0] rf_31_r;
  wire [31 : 0] rf_31_r$D_IN;
  wire rf_31_r$EN;

  // register rf_3_r
  reg [31 : 0] rf_3_r;
  wire [31 : 0] rf_3_r$D_IN;
  wire rf_3_r$EN;

  // register rf_4_r
  reg [31 : 0] rf_4_r;
  wire [31 : 0] rf_4_r$D_IN;
  wire rf_4_r$EN;

  // register rf_5_r
  reg [31 : 0] rf_5_r;
  wire [31 : 0] rf_5_r$D_IN;
  wire rf_5_r$EN;

  // register rf_6_r
  reg [31 : 0] rf_6_r;
  wire [31 : 0] rf_6_r$D_IN;
  wire rf_6_r$EN;

  // register rf_7_r
  reg [31 : 0] rf_7_r;
  wire [31 : 0] rf_7_r$D_IN;
  wire rf_7_r$EN;

  // register rf_8_r
  reg [31 : 0] rf_8_r;
  wire [31 : 0] rf_8_r$D_IN;
  wire rf_8_r$EN;

  // register rf_9_r
  reg [31 : 0] rf_9_r;
  wire [31 : 0] rf_9_r$D_IN;
  wire rf_9_r$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rf_0_canonicalize,
       CAN_FIRE_RL_rf_10_canonicalize,
       CAN_FIRE_RL_rf_11_canonicalize,
       CAN_FIRE_RL_rf_12_canonicalize,
       CAN_FIRE_RL_rf_13_canonicalize,
       CAN_FIRE_RL_rf_14_canonicalize,
       CAN_FIRE_RL_rf_15_canonicalize,
       CAN_FIRE_RL_rf_16_canonicalize,
       CAN_FIRE_RL_rf_17_canonicalize,
       CAN_FIRE_RL_rf_18_canonicalize,
       CAN_FIRE_RL_rf_19_canonicalize,
       CAN_FIRE_RL_rf_1_canonicalize,
       CAN_FIRE_RL_rf_20_canonicalize,
       CAN_FIRE_RL_rf_21_canonicalize,
       CAN_FIRE_RL_rf_22_canonicalize,
       CAN_FIRE_RL_rf_23_canonicalize,
       CAN_FIRE_RL_rf_24_canonicalize,
       CAN_FIRE_RL_rf_25_canonicalize,
       CAN_FIRE_RL_rf_26_canonicalize,
       CAN_FIRE_RL_rf_27_canonicalize,
       CAN_FIRE_RL_rf_28_canonicalize,
       CAN_FIRE_RL_rf_29_canonicalize,
       CAN_FIRE_RL_rf_2_canonicalize,
       CAN_FIRE_RL_rf_30_canonicalize,
       CAN_FIRE_RL_rf_31_canonicalize,
       CAN_FIRE_RL_rf_3_canonicalize,
       CAN_FIRE_RL_rf_4_canonicalize,
       CAN_FIRE_RL_rf_5_canonicalize,
       CAN_FIRE_RL_rf_6_canonicalize,
       CAN_FIRE_RL_rf_7_canonicalize,
       CAN_FIRE_RL_rf_8_canonicalize,
       CAN_FIRE_RL_rf_9_canonicalize,
       CAN_FIRE_dbgWrite,
       CAN_FIRE_write,
       WILL_FIRE_RL_rf_0_canonicalize,
       WILL_FIRE_RL_rf_10_canonicalize,
       WILL_FIRE_RL_rf_11_canonicalize,
       WILL_FIRE_RL_rf_12_canonicalize,
       WILL_FIRE_RL_rf_13_canonicalize,
       WILL_FIRE_RL_rf_14_canonicalize,
       WILL_FIRE_RL_rf_15_canonicalize,
       WILL_FIRE_RL_rf_16_canonicalize,
       WILL_FIRE_RL_rf_17_canonicalize,
       WILL_FIRE_RL_rf_18_canonicalize,
       WILL_FIRE_RL_rf_19_canonicalize,
       WILL_FIRE_RL_rf_1_canonicalize,
       WILL_FIRE_RL_rf_20_canonicalize,
       WILL_FIRE_RL_rf_21_canonicalize,
       WILL_FIRE_RL_rf_22_canonicalize,
       WILL_FIRE_RL_rf_23_canonicalize,
       WILL_FIRE_RL_rf_24_canonicalize,
       WILL_FIRE_RL_rf_25_canonicalize,
       WILL_FIRE_RL_rf_26_canonicalize,
       WILL_FIRE_RL_rf_27_canonicalize,
       WILL_FIRE_RL_rf_28_canonicalize,
       WILL_FIRE_RL_rf_29_canonicalize,
       WILL_FIRE_RL_rf_2_canonicalize,
       WILL_FIRE_RL_rf_30_canonicalize,
       WILL_FIRE_RL_rf_31_canonicalize,
       WILL_FIRE_RL_rf_3_canonicalize,
       WILL_FIRE_RL_rf_4_canonicalize,
       WILL_FIRE_RL_rf_5_canonicalize,
       WILL_FIRE_RL_rf_6_canonicalize,
       WILL_FIRE_RL_rf_7_canonicalize,
       WILL_FIRE_RL_rf_8_canonicalize,
       WILL_FIRE_RL_rf_9_canonicalize,
       WILL_FIRE_dbgWrite,
       WILL_FIRE_write;

  // remaining internal signals
  wire [31 : 0] def__h10095,
		def__h10558,
		def__h10675,
		def__h11138,
		def__h11255,
		def__h11718,
		def__h11835,
		def__h12298,
		def__h12415,
		def__h12878,
		def__h12995,
		def__h13458,
		def__h13575,
		def__h14038,
		def__h14155,
		def__h14618,
		def__h14735,
		def__h15198,
		def__h15315,
		def__h15778,
		def__h15895,
		def__h16358,
		def__h16475,
		def__h16938,
		def__h17055,
		def__h17518,
		def__h17635,
		def__h18098,
		def__h18215,
		def__h1858,
		def__h18678,
		def__h18795,
		def__h19258,
		def__h19375,
		def__h1975,
		def__h2438,
		def__h2555,
		def__h3018,
		def__h3135,
		def__h3598,
		def__h3715,
		def__h4178,
		def__h4295,
		def__h4758,
		def__h4875,
		def__h5338,
		def__h5455,
		def__h5918,
		def__h6035,
		def__h6498,
		def__h6615,
		def__h7078,
		def__h7195,
		def__h7658,
		def__h7775,
		def__h8238,
		def__h8355,
		def__h8818,
		def__h8935,
		def__h9398,
		def__h9515,
		def__h9978;

  // value method read1
  always@(read1_a or
	  def__h1858 or
	  def__h2438 or
	  def__h3018 or
	  def__h3598 or
	  def__h4178 or
	  def__h4758 or
	  def__h5338 or
	  def__h5918 or
	  def__h6498 or
	  def__h7078 or
	  def__h7658 or
	  def__h8238 or
	  def__h8818 or
	  def__h9398 or
	  def__h9978 or
	  def__h10558 or
	  def__h11138 or
	  def__h11718 or
	  def__h12298 or
	  def__h12878 or
	  def__h13458 or
	  def__h14038 or
	  def__h14618 or
	  def__h15198 or
	  def__h15778 or
	  def__h16358 or
	  def__h16938 or
	  def__h17518 or def__h18098 or def__h18678 or def__h19258)
  begin
    case (read1_a)
      5'd0: read1 = 32'd0;
      5'd1: read1 = def__h1858;
      5'd2: read1 = def__h2438;
      5'd3: read1 = def__h3018;
      5'd4: read1 = def__h3598;
      5'd5: read1 = def__h4178;
      5'd6: read1 = def__h4758;
      5'd7: read1 = def__h5338;
      5'd8: read1 = def__h5918;
      5'd9: read1 = def__h6498;
      5'd10: read1 = def__h7078;
      5'd11: read1 = def__h7658;
      5'd12: read1 = def__h8238;
      5'd13: read1 = def__h8818;
      5'd14: read1 = def__h9398;
      5'd15: read1 = def__h9978;
      5'd16: read1 = def__h10558;
      5'd17: read1 = def__h11138;
      5'd18: read1 = def__h11718;
      5'd19: read1 = def__h12298;
      5'd20: read1 = def__h12878;
      5'd21: read1 = def__h13458;
      5'd22: read1 = def__h14038;
      5'd23: read1 = def__h14618;
      5'd24: read1 = def__h15198;
      5'd25: read1 = def__h15778;
      5'd26: read1 = def__h16358;
      5'd27: read1 = def__h16938;
      5'd28: read1 = def__h17518;
      5'd29: read1 = def__h18098;
      5'd30: read1 = def__h18678;
      5'd31: read1 = def__h19258;
    endcase
  end
  assign RDY_read1 = 1'd1 ;

  // value method read2
  always@(read2_a or
	  def__h1858 or
	  def__h2438 or
	  def__h3018 or
	  def__h3598 or
	  def__h4178 or
	  def__h4758 or
	  def__h5338 or
	  def__h5918 or
	  def__h6498 or
	  def__h7078 or
	  def__h7658 or
	  def__h8238 or
	  def__h8818 or
	  def__h9398 or
	  def__h9978 or
	  def__h10558 or
	  def__h11138 or
	  def__h11718 or
	  def__h12298 or
	  def__h12878 or
	  def__h13458 or
	  def__h14038 or
	  def__h14618 or
	  def__h15198 or
	  def__h15778 or
	  def__h16358 or
	  def__h16938 or
	  def__h17518 or def__h18098 or def__h18678 or def__h19258)
  begin
    case (read2_a)
      5'd0: read2 = 32'd0;
      5'd1: read2 = def__h1858;
      5'd2: read2 = def__h2438;
      5'd3: read2 = def__h3018;
      5'd4: read2 = def__h3598;
      5'd5: read2 = def__h4178;
      5'd6: read2 = def__h4758;
      5'd7: read2 = def__h5338;
      5'd8: read2 = def__h5918;
      5'd9: read2 = def__h6498;
      5'd10: read2 = def__h7078;
      5'd11: read2 = def__h7658;
      5'd12: read2 = def__h8238;
      5'd13: read2 = def__h8818;
      5'd14: read2 = def__h9398;
      5'd15: read2 = def__h9978;
      5'd16: read2 = def__h10558;
      5'd17: read2 = def__h11138;
      5'd18: read2 = def__h11718;
      5'd19: read2 = def__h12298;
      5'd20: read2 = def__h12878;
      5'd21: read2 = def__h13458;
      5'd22: read2 = def__h14038;
      5'd23: read2 = def__h14618;
      5'd24: read2 = def__h15198;
      5'd25: read2 = def__h15778;
      5'd26: read2 = def__h16358;
      5'd27: read2 = def__h16938;
      5'd28: read2 = def__h17518;
      5'd29: read2 = def__h18098;
      5'd30: read2 = def__h18678;
      5'd31: read2 = def__h19258;
    endcase
  end
  assign RDY_read2 = 1'd1 ;

  // action method write
  assign RDY_write = 1'd1 ;
  assign CAN_FIRE_write = 1'd1 ;
  assign WILL_FIRE_write = EN_write ;

  // value method dbgRead
  always@(dbgRead_a or
	  rf_1_r or
	  rf_2_r or
	  rf_3_r or
	  rf_4_r or
	  rf_5_r or
	  rf_6_r or
	  rf_7_r or
	  rf_8_r or
	  rf_9_r or
	  rf_10_r or
	  rf_11_r or
	  rf_12_r or
	  rf_13_r or
	  rf_14_r or
	  rf_15_r or
	  rf_16_r or
	  rf_17_r or
	  rf_18_r or
	  rf_19_r or
	  rf_20_r or
	  rf_21_r or
	  rf_22_r or
	  rf_23_r or
	  rf_24_r or
	  rf_25_r or
	  rf_26_r or rf_27_r or rf_28_r or rf_29_r or rf_30_r or rf_31_r)
  begin
    case (dbgRead_a)
      5'd0: dbgRead = 32'd0;
      5'd1: dbgRead = rf_1_r;
      5'd2: dbgRead = rf_2_r;
      5'd3: dbgRead = rf_3_r;
      5'd4: dbgRead = rf_4_r;
      5'd5: dbgRead = rf_5_r;
      5'd6: dbgRead = rf_6_r;
      5'd7: dbgRead = rf_7_r;
      5'd8: dbgRead = rf_8_r;
      5'd9: dbgRead = rf_9_r;
      5'd10: dbgRead = rf_10_r;
      5'd11: dbgRead = rf_11_r;
      5'd12: dbgRead = rf_12_r;
      5'd13: dbgRead = rf_13_r;
      5'd14: dbgRead = rf_14_r;
      5'd15: dbgRead = rf_15_r;
      5'd16: dbgRead = rf_16_r;
      5'd17: dbgRead = rf_17_r;
      5'd18: dbgRead = rf_18_r;
      5'd19: dbgRead = rf_19_r;
      5'd20: dbgRead = rf_20_r;
      5'd21: dbgRead = rf_21_r;
      5'd22: dbgRead = rf_22_r;
      5'd23: dbgRead = rf_23_r;
      5'd24: dbgRead = rf_24_r;
      5'd25: dbgRead = rf_25_r;
      5'd26: dbgRead = rf_26_r;
      5'd27: dbgRead = rf_27_r;
      5'd28: dbgRead = rf_28_r;
      5'd29: dbgRead = rf_29_r;
      5'd30: dbgRead = rf_30_r;
      5'd31: dbgRead = rf_31_r;
    endcase
  end
  assign RDY_dbgRead = 1'd1 ;

  // action method dbgWrite
  assign RDY_dbgWrite = 1'd1 ;
  assign CAN_FIRE_dbgWrite = 1'd1 ;
  assign WILL_FIRE_dbgWrite = EN_dbgWrite ;

  // rule RL_rf_0_canonicalize
  assign CAN_FIRE_RL_rf_0_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_0_canonicalize = 1'd1 ;

  // rule RL_rf_1_canonicalize
  assign CAN_FIRE_RL_rf_1_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_1_canonicalize = 1'd1 ;

  // rule RL_rf_2_canonicalize
  assign CAN_FIRE_RL_rf_2_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_2_canonicalize = 1'd1 ;

  // rule RL_rf_3_canonicalize
  assign CAN_FIRE_RL_rf_3_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_3_canonicalize = 1'd1 ;

  // rule RL_rf_4_canonicalize
  assign CAN_FIRE_RL_rf_4_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_4_canonicalize = 1'd1 ;

  // rule RL_rf_5_canonicalize
  assign CAN_FIRE_RL_rf_5_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_5_canonicalize = 1'd1 ;

  // rule RL_rf_6_canonicalize
  assign CAN_FIRE_RL_rf_6_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_6_canonicalize = 1'd1 ;

  // rule RL_rf_7_canonicalize
  assign CAN_FIRE_RL_rf_7_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_7_canonicalize = 1'd1 ;

  // rule RL_rf_8_canonicalize
  assign CAN_FIRE_RL_rf_8_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_8_canonicalize = 1'd1 ;

  // rule RL_rf_9_canonicalize
  assign CAN_FIRE_RL_rf_9_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_9_canonicalize = 1'd1 ;

  // rule RL_rf_10_canonicalize
  assign CAN_FIRE_RL_rf_10_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_10_canonicalize = 1'd1 ;

  // rule RL_rf_11_canonicalize
  assign CAN_FIRE_RL_rf_11_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_11_canonicalize = 1'd1 ;

  // rule RL_rf_12_canonicalize
  assign CAN_FIRE_RL_rf_12_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_12_canonicalize = 1'd1 ;

  // rule RL_rf_13_canonicalize
  assign CAN_FIRE_RL_rf_13_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_13_canonicalize = 1'd1 ;

  // rule RL_rf_14_canonicalize
  assign CAN_FIRE_RL_rf_14_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_14_canonicalize = 1'd1 ;

  // rule RL_rf_15_canonicalize
  assign CAN_FIRE_RL_rf_15_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_15_canonicalize = 1'd1 ;

  // rule RL_rf_16_canonicalize
  assign CAN_FIRE_RL_rf_16_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_16_canonicalize = 1'd1 ;

  // rule RL_rf_17_canonicalize
  assign CAN_FIRE_RL_rf_17_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_17_canonicalize = 1'd1 ;

  // rule RL_rf_18_canonicalize
  assign CAN_FIRE_RL_rf_18_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_18_canonicalize = 1'd1 ;

  // rule RL_rf_19_canonicalize
  assign CAN_FIRE_RL_rf_19_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_19_canonicalize = 1'd1 ;

  // rule RL_rf_20_canonicalize
  assign CAN_FIRE_RL_rf_20_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_20_canonicalize = 1'd1 ;

  // rule RL_rf_21_canonicalize
  assign CAN_FIRE_RL_rf_21_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_21_canonicalize = 1'd1 ;

  // rule RL_rf_22_canonicalize
  assign CAN_FIRE_RL_rf_22_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_22_canonicalize = 1'd1 ;

  // rule RL_rf_23_canonicalize
  assign CAN_FIRE_RL_rf_23_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_23_canonicalize = 1'd1 ;

  // rule RL_rf_24_canonicalize
  assign CAN_FIRE_RL_rf_24_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_24_canonicalize = 1'd1 ;

  // rule RL_rf_25_canonicalize
  assign CAN_FIRE_RL_rf_25_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_25_canonicalize = 1'd1 ;

  // rule RL_rf_26_canonicalize
  assign CAN_FIRE_RL_rf_26_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_26_canonicalize = 1'd1 ;

  // rule RL_rf_27_canonicalize
  assign CAN_FIRE_RL_rf_27_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_27_canonicalize = 1'd1 ;

  // rule RL_rf_28_canonicalize
  assign CAN_FIRE_RL_rf_28_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_28_canonicalize = 1'd1 ;

  // rule RL_rf_29_canonicalize
  assign CAN_FIRE_RL_rf_29_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_29_canonicalize = 1'd1 ;

  // rule RL_rf_30_canonicalize
  assign CAN_FIRE_RL_rf_30_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_30_canonicalize = 1'd1 ;

  // rule RL_rf_31_canonicalize
  assign CAN_FIRE_RL_rf_31_canonicalize = 1'd1 ;
  assign WILL_FIRE_RL_rf_31_canonicalize = 1'd1 ;

  // inlined wires
  assign rf_1_w_0$whas = EN_write && write_a == 5'd1 ;
  assign rf_1_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd1 ;
  assign rf_2_w_0$whas = EN_write && write_a == 5'd2 ;
  assign rf_2_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd2 ;
  assign rf_3_w_0$whas = EN_write && write_a == 5'd3 ;
  assign rf_3_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd3 ;
  assign rf_4_w_0$whas = EN_write && write_a == 5'd4 ;
  assign rf_4_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd4 ;
  assign rf_5_w_0$whas = EN_write && write_a == 5'd5 ;
  assign rf_5_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd5 ;
  assign rf_6_w_0$whas = EN_write && write_a == 5'd6 ;
  assign rf_6_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd6 ;
  assign rf_7_w_0$whas = EN_write && write_a == 5'd7 ;
  assign rf_7_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd7 ;
  assign rf_8_w_0$whas = EN_write && write_a == 5'd8 ;
  assign rf_8_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd8 ;
  assign rf_9_w_0$whas = EN_write && write_a == 5'd9 ;
  assign rf_9_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd9 ;
  assign rf_10_w_0$whas = EN_write && write_a == 5'd10 ;
  assign rf_10_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd10 ;
  assign rf_11_w_0$whas = EN_write && write_a == 5'd11 ;
  assign rf_11_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd11 ;
  assign rf_12_w_0$whas = EN_write && write_a == 5'd12 ;
  assign rf_12_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd12 ;
  assign rf_13_w_0$whas = EN_write && write_a == 5'd13 ;
  assign rf_13_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd13 ;
  assign rf_14_w_0$whas = EN_write && write_a == 5'd14 ;
  assign rf_14_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd14 ;
  assign rf_15_w_0$whas = EN_write && write_a == 5'd15 ;
  assign rf_15_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd15 ;
  assign rf_16_w_0$whas = EN_write && write_a == 5'd16 ;
  assign rf_16_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd16 ;
  assign rf_17_w_0$whas = EN_write && write_a == 5'd17 ;
  assign rf_17_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd17 ;
  assign rf_18_w_0$whas = EN_write && write_a == 5'd18 ;
  assign rf_18_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd18 ;
  assign rf_19_w_0$whas = EN_write && write_a == 5'd19 ;
  assign rf_19_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd19 ;
  assign rf_20_w_0$whas = EN_write && write_a == 5'd20 ;
  assign rf_20_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd20 ;
  assign rf_21_w_0$whas = EN_write && write_a == 5'd21 ;
  assign rf_21_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd21 ;
  assign rf_22_w_0$whas = EN_write && write_a == 5'd22 ;
  assign rf_22_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd22 ;
  assign rf_23_w_0$whas = EN_write && write_a == 5'd23 ;
  assign rf_23_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd23 ;
  assign rf_24_w_0$whas = EN_write && write_a == 5'd24 ;
  assign rf_24_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd24 ;
  assign rf_25_w_0$whas = EN_write && write_a == 5'd25 ;
  assign rf_25_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd25 ;
  assign rf_26_w_0$whas = EN_write && write_a == 5'd26 ;
  assign rf_26_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd26 ;
  assign rf_27_w_0$whas = EN_write && write_a == 5'd27 ;
  assign rf_27_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd27 ;
  assign rf_28_w_0$whas = EN_write && write_a == 5'd28 ;
  assign rf_28_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd28 ;
  assign rf_29_w_0$whas = EN_write && write_a == 5'd29 ;
  assign rf_29_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd29 ;
  assign rf_30_w_0$whas = EN_write && write_a == 5'd30 ;
  assign rf_30_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd30 ;
  assign rf_31_w_0$whas = EN_write && write_a == 5'd31 ;
  assign rf_31_w_1$whas = EN_dbgWrite && dbgWrite_a == 5'd31 ;

  // register rf_0_r
  assign rf_0_r$D_IN = rf_0_r ;
  assign rf_0_r$EN = 1'd1 ;

  // register rf_10_r
  assign rf_10_r$D_IN = def__h7078 ;
  assign rf_10_r$EN = 1'd1 ;

  // register rf_11_r
  assign rf_11_r$D_IN = def__h7658 ;
  assign rf_11_r$EN = 1'd1 ;

  // register rf_12_r
  assign rf_12_r$D_IN = def__h8238 ;
  assign rf_12_r$EN = 1'd1 ;

  // register rf_13_r
  assign rf_13_r$D_IN = def__h8818 ;
  assign rf_13_r$EN = 1'd1 ;

  // register rf_14_r
  assign rf_14_r$D_IN = def__h9398 ;
  assign rf_14_r$EN = 1'd1 ;

  // register rf_15_r
  assign rf_15_r$D_IN = def__h9978 ;
  assign rf_15_r$EN = 1'd1 ;

  // register rf_16_r
  assign rf_16_r$D_IN = def__h10558 ;
  assign rf_16_r$EN = 1'd1 ;

  // register rf_17_r
  assign rf_17_r$D_IN = def__h11138 ;
  assign rf_17_r$EN = 1'd1 ;

  // register rf_18_r
  assign rf_18_r$D_IN = def__h11718 ;
  assign rf_18_r$EN = 1'd1 ;

  // register rf_19_r
  assign rf_19_r$D_IN = def__h12298 ;
  assign rf_19_r$EN = 1'd1 ;

  // register rf_1_r
  assign rf_1_r$D_IN = def__h1858 ;
  assign rf_1_r$EN = 1'd1 ;

  // register rf_20_r
  assign rf_20_r$D_IN = def__h12878 ;
  assign rf_20_r$EN = 1'd1 ;

  // register rf_21_r
  assign rf_21_r$D_IN = def__h13458 ;
  assign rf_21_r$EN = 1'd1 ;

  // register rf_22_r
  assign rf_22_r$D_IN = def__h14038 ;
  assign rf_22_r$EN = 1'd1 ;

  // register rf_23_r
  assign rf_23_r$D_IN = def__h14618 ;
  assign rf_23_r$EN = 1'd1 ;

  // register rf_24_r
  assign rf_24_r$D_IN = def__h15198 ;
  assign rf_24_r$EN = 1'd1 ;

  // register rf_25_r
  assign rf_25_r$D_IN = def__h15778 ;
  assign rf_25_r$EN = 1'd1 ;

  // register rf_26_r
  assign rf_26_r$D_IN = def__h16358 ;
  assign rf_26_r$EN = 1'd1 ;

  // register rf_27_r
  assign rf_27_r$D_IN = def__h16938 ;
  assign rf_27_r$EN = 1'd1 ;

  // register rf_28_r
  assign rf_28_r$D_IN = def__h17518 ;
  assign rf_28_r$EN = 1'd1 ;

  // register rf_29_r
  assign rf_29_r$D_IN = def__h18098 ;
  assign rf_29_r$EN = 1'd1 ;

  // register rf_2_r
  assign rf_2_r$D_IN = def__h2438 ;
  assign rf_2_r$EN = 1'd1 ;

  // register rf_30_r
  assign rf_30_r$D_IN = def__h18678 ;
  assign rf_30_r$EN = 1'd1 ;

  // register rf_31_r
  assign rf_31_r$D_IN = def__h19258 ;
  assign rf_31_r$EN = 1'd1 ;

  // register rf_3_r
  assign rf_3_r$D_IN = def__h3018 ;
  assign rf_3_r$EN = 1'd1 ;

  // register rf_4_r
  assign rf_4_r$D_IN = def__h3598 ;
  assign rf_4_r$EN = 1'd1 ;

  // register rf_5_r
  assign rf_5_r$D_IN = def__h4178 ;
  assign rf_5_r$EN = 1'd1 ;

  // register rf_6_r
  assign rf_6_r$D_IN = def__h4758 ;
  assign rf_6_r$EN = 1'd1 ;

  // register rf_7_r
  assign rf_7_r$D_IN = def__h5338 ;
  assign rf_7_r$EN = 1'd1 ;

  // register rf_8_r
  assign rf_8_r$D_IN = def__h5918 ;
  assign rf_8_r$EN = 1'd1 ;

  // register rf_9_r
  assign rf_9_r$D_IN = def__h6498 ;
  assign rf_9_r$EN = 1'd1 ;

  // remaining internal signals
  assign def__h10095 = rf_15_w_0$whas ? write_d : rf_15_r ;
  assign def__h10558 = rf_16_w_1$whas ? dbgWrite_d : def__h10675 ;
  assign def__h10675 = rf_16_w_0$whas ? write_d : rf_16_r ;
  assign def__h11138 = rf_17_w_1$whas ? dbgWrite_d : def__h11255 ;
  assign def__h11255 = rf_17_w_0$whas ? write_d : rf_17_r ;
  assign def__h11718 = rf_18_w_1$whas ? dbgWrite_d : def__h11835 ;
  assign def__h11835 = rf_18_w_0$whas ? write_d : rf_18_r ;
  assign def__h12298 = rf_19_w_1$whas ? dbgWrite_d : def__h12415 ;
  assign def__h12415 = rf_19_w_0$whas ? write_d : rf_19_r ;
  assign def__h12878 = rf_20_w_1$whas ? dbgWrite_d : def__h12995 ;
  assign def__h12995 = rf_20_w_0$whas ? write_d : rf_20_r ;
  assign def__h13458 = rf_21_w_1$whas ? dbgWrite_d : def__h13575 ;
  assign def__h13575 = rf_21_w_0$whas ? write_d : rf_21_r ;
  assign def__h14038 = rf_22_w_1$whas ? dbgWrite_d : def__h14155 ;
  assign def__h14155 = rf_22_w_0$whas ? write_d : rf_22_r ;
  assign def__h14618 = rf_23_w_1$whas ? dbgWrite_d : def__h14735 ;
  assign def__h14735 = rf_23_w_0$whas ? write_d : rf_23_r ;
  assign def__h15198 = rf_24_w_1$whas ? dbgWrite_d : def__h15315 ;
  assign def__h15315 = rf_24_w_0$whas ? write_d : rf_24_r ;
  assign def__h15778 = rf_25_w_1$whas ? dbgWrite_d : def__h15895 ;
  assign def__h15895 = rf_25_w_0$whas ? write_d : rf_25_r ;
  assign def__h16358 = rf_26_w_1$whas ? dbgWrite_d : def__h16475 ;
  assign def__h16475 = rf_26_w_0$whas ? write_d : rf_26_r ;
  assign def__h16938 = rf_27_w_1$whas ? dbgWrite_d : def__h17055 ;
  assign def__h17055 = rf_27_w_0$whas ? write_d : rf_27_r ;
  assign def__h17518 = rf_28_w_1$whas ? dbgWrite_d : def__h17635 ;
  assign def__h17635 = rf_28_w_0$whas ? write_d : rf_28_r ;
  assign def__h18098 = rf_29_w_1$whas ? dbgWrite_d : def__h18215 ;
  assign def__h18215 = rf_29_w_0$whas ? write_d : rf_29_r ;
  assign def__h1858 = rf_1_w_1$whas ? dbgWrite_d : def__h1975 ;
  assign def__h18678 = rf_30_w_1$whas ? dbgWrite_d : def__h18795 ;
  assign def__h18795 = rf_30_w_0$whas ? write_d : rf_30_r ;
  assign def__h19258 = rf_31_w_1$whas ? dbgWrite_d : def__h19375 ;
  assign def__h19375 = rf_31_w_0$whas ? write_d : rf_31_r ;
  assign def__h1975 = rf_1_w_0$whas ? write_d : rf_1_r ;
  assign def__h2438 = rf_2_w_1$whas ? dbgWrite_d : def__h2555 ;
  assign def__h2555 = rf_2_w_0$whas ? write_d : rf_2_r ;
  assign def__h3018 = rf_3_w_1$whas ? dbgWrite_d : def__h3135 ;
  assign def__h3135 = rf_3_w_0$whas ? write_d : rf_3_r ;
  assign def__h3598 = rf_4_w_1$whas ? dbgWrite_d : def__h3715 ;
  assign def__h3715 = rf_4_w_0$whas ? write_d : rf_4_r ;
  assign def__h4178 = rf_5_w_1$whas ? dbgWrite_d : def__h4295 ;
  assign def__h4295 = rf_5_w_0$whas ? write_d : rf_5_r ;
  assign def__h4758 = rf_6_w_1$whas ? dbgWrite_d : def__h4875 ;
  assign def__h4875 = rf_6_w_0$whas ? write_d : rf_6_r ;
  assign def__h5338 = rf_7_w_1$whas ? dbgWrite_d : def__h5455 ;
  assign def__h5455 = rf_7_w_0$whas ? write_d : rf_7_r ;
  assign def__h5918 = rf_8_w_1$whas ? dbgWrite_d : def__h6035 ;
  assign def__h6035 = rf_8_w_0$whas ? write_d : rf_8_r ;
  assign def__h6498 = rf_9_w_1$whas ? dbgWrite_d : def__h6615 ;
  assign def__h6615 = rf_9_w_0$whas ? write_d : rf_9_r ;
  assign def__h7078 = rf_10_w_1$whas ? dbgWrite_d : def__h7195 ;
  assign def__h7195 = rf_10_w_0$whas ? write_d : rf_10_r ;
  assign def__h7658 = rf_11_w_1$whas ? dbgWrite_d : def__h7775 ;
  assign def__h7775 = rf_11_w_0$whas ? write_d : rf_11_r ;
  assign def__h8238 = rf_12_w_1$whas ? dbgWrite_d : def__h8355 ;
  assign def__h8355 = rf_12_w_0$whas ? write_d : rf_12_r ;
  assign def__h8818 = rf_13_w_1$whas ? dbgWrite_d : def__h8935 ;
  assign def__h8935 = rf_13_w_0$whas ? write_d : rf_13_r ;
  assign def__h9398 = rf_14_w_1$whas ? dbgWrite_d : def__h9515 ;
  assign def__h9515 = rf_14_w_0$whas ? write_d : rf_14_r ;
  assign def__h9978 = rf_15_w_1$whas ? dbgWrite_d : def__h10095 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rf_0_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_10_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_11_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_12_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_13_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_14_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_15_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_16_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_17_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_18_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_19_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_1_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_20_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_21_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_22_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_23_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_24_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_25_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_26_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_27_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_28_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_29_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_2_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_30_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_31_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_3_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_4_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_5_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_6_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_7_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_8_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rf_9_r <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (rf_0_r$EN) rf_0_r <= `BSV_ASSIGNMENT_DELAY rf_0_r$D_IN;
	if (rf_10_r$EN) rf_10_r <= `BSV_ASSIGNMENT_DELAY rf_10_r$D_IN;
	if (rf_11_r$EN) rf_11_r <= `BSV_ASSIGNMENT_DELAY rf_11_r$D_IN;
	if (rf_12_r$EN) rf_12_r <= `BSV_ASSIGNMENT_DELAY rf_12_r$D_IN;
	if (rf_13_r$EN) rf_13_r <= `BSV_ASSIGNMENT_DELAY rf_13_r$D_IN;
	if (rf_14_r$EN) rf_14_r <= `BSV_ASSIGNMENT_DELAY rf_14_r$D_IN;
	if (rf_15_r$EN) rf_15_r <= `BSV_ASSIGNMENT_DELAY rf_15_r$D_IN;
	if (rf_16_r$EN) rf_16_r <= `BSV_ASSIGNMENT_DELAY rf_16_r$D_IN;
	if (rf_17_r$EN) rf_17_r <= `BSV_ASSIGNMENT_DELAY rf_17_r$D_IN;
	if (rf_18_r$EN) rf_18_r <= `BSV_ASSIGNMENT_DELAY rf_18_r$D_IN;
	if (rf_19_r$EN) rf_19_r <= `BSV_ASSIGNMENT_DELAY rf_19_r$D_IN;
	if (rf_1_r$EN) rf_1_r <= `BSV_ASSIGNMENT_DELAY rf_1_r$D_IN;
	if (rf_20_r$EN) rf_20_r <= `BSV_ASSIGNMENT_DELAY rf_20_r$D_IN;
	if (rf_21_r$EN) rf_21_r <= `BSV_ASSIGNMENT_DELAY rf_21_r$D_IN;
	if (rf_22_r$EN) rf_22_r <= `BSV_ASSIGNMENT_DELAY rf_22_r$D_IN;
	if (rf_23_r$EN) rf_23_r <= `BSV_ASSIGNMENT_DELAY rf_23_r$D_IN;
	if (rf_24_r$EN) rf_24_r <= `BSV_ASSIGNMENT_DELAY rf_24_r$D_IN;
	if (rf_25_r$EN) rf_25_r <= `BSV_ASSIGNMENT_DELAY rf_25_r$D_IN;
	if (rf_26_r$EN) rf_26_r <= `BSV_ASSIGNMENT_DELAY rf_26_r$D_IN;
	if (rf_27_r$EN) rf_27_r <= `BSV_ASSIGNMENT_DELAY rf_27_r$D_IN;
	if (rf_28_r$EN) rf_28_r <= `BSV_ASSIGNMENT_DELAY rf_28_r$D_IN;
	if (rf_29_r$EN) rf_29_r <= `BSV_ASSIGNMENT_DELAY rf_29_r$D_IN;
	if (rf_2_r$EN) rf_2_r <= `BSV_ASSIGNMENT_DELAY rf_2_r$D_IN;
	if (rf_30_r$EN) rf_30_r <= `BSV_ASSIGNMENT_DELAY rf_30_r$D_IN;
	if (rf_31_r$EN) rf_31_r <= `BSV_ASSIGNMENT_DELAY rf_31_r$D_IN;
	if (rf_3_r$EN) rf_3_r <= `BSV_ASSIGNMENT_DELAY rf_3_r$D_IN;
	if (rf_4_r$EN) rf_4_r <= `BSV_ASSIGNMENT_DELAY rf_4_r$D_IN;
	if (rf_5_r$EN) rf_5_r <= `BSV_ASSIGNMENT_DELAY rf_5_r$D_IN;
	if (rf_6_r$EN) rf_6_r <= `BSV_ASSIGNMENT_DELAY rf_6_r$D_IN;
	if (rf_7_r$EN) rf_7_r <= `BSV_ASSIGNMENT_DELAY rf_7_r$D_IN;
	if (rf_8_r$EN) rf_8_r <= `BSV_ASSIGNMENT_DELAY rf_8_r$D_IN;
	if (rf_9_r$EN) rf_9_r <= `BSV_ASSIGNMENT_DELAY rf_9_r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rf_0_r = 32'hAAAAAAAA;
    rf_10_r = 32'hAAAAAAAA;
    rf_11_r = 32'hAAAAAAAA;
    rf_12_r = 32'hAAAAAAAA;
    rf_13_r = 32'hAAAAAAAA;
    rf_14_r = 32'hAAAAAAAA;
    rf_15_r = 32'hAAAAAAAA;
    rf_16_r = 32'hAAAAAAAA;
    rf_17_r = 32'hAAAAAAAA;
    rf_18_r = 32'hAAAAAAAA;
    rf_19_r = 32'hAAAAAAAA;
    rf_1_r = 32'hAAAAAAAA;
    rf_20_r = 32'hAAAAAAAA;
    rf_21_r = 32'hAAAAAAAA;
    rf_22_r = 32'hAAAAAAAA;
    rf_23_r = 32'hAAAAAAAA;
    rf_24_r = 32'hAAAAAAAA;
    rf_25_r = 32'hAAAAAAAA;
    rf_26_r = 32'hAAAAAAAA;
    rf_27_r = 32'hAAAAAAAA;
    rf_28_r = 32'hAAAAAAAA;
    rf_29_r = 32'hAAAAAAAA;
    rf_2_r = 32'hAAAAAAAA;
    rf_30_r = 32'hAAAAAAAA;
    rf_31_r = 32'hAAAAAAAA;
    rf_3_r = 32'hAAAAAAAA;
    rf_4_r = 32'hAAAAAAAA;
    rf_5_r = 32'hAAAAAAAA;
    rf_6_r = 32'hAAAAAAAA;
    rf_7_r = 32'hAAAAAAAA;
    rf_8_r = 32'hAAAAAAAA;
    rf_9_r = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkRegFile

