//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// RDY_debug_enqReq               O     1
// debug_getResp                  O    33
// RDY_debug_getResp              O     1
// debug_respAvail                O     1
// RDY_debug_respAvail            O     1 const
// debug_coreHalted               O     1
// RDY_debug_coreHalted           O     1 const
// RDY_initWord                   O     1 const
// peekWord                       O    32
// RDY_peekWord                   O     1 const
// retired                        O     1 reg
// RDY_retired                    O     1 const
// CLK_dClk                       I     1 clock
// RST_N_dRst                     I     1 reset
// CLK                            I     1 clock
// RST_N                          I     1 reset
// debug_enqReq_r                 I    72
// initWord_wordIdx               I    32
// initWord_v                     I    32
// peekWord_wordIdx               I    32
// EN_debug_enqReq                I     1
// EN_initWord                    I     1
// EN_debug_getResp               I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSoC(CLK_dClk,
	     RST_N_dRst,
	     CLK,
	     RST_N,

	     debug_enqReq_r,
	     EN_debug_enqReq,
	     RDY_debug_enqReq,

	     EN_debug_getResp,
	     debug_getResp,
	     RDY_debug_getResp,

	     debug_respAvail,
	     RDY_debug_respAvail,

	     debug_coreHalted,
	     RDY_debug_coreHalted,

	     initWord_wordIdx,
	     initWord_v,
	     EN_initWord,
	     RDY_initWord,

	     peekWord_wordIdx,
	     peekWord,
	     RDY_peekWord,

	     retired,
	     RDY_retired);
  input  CLK_dClk;
  input  RST_N_dRst;
  input  CLK;
  input  RST_N;

  // action method debug_enqReq
  input  [71 : 0] debug_enqReq_r;
  input  EN_debug_enqReq;
  output RDY_debug_enqReq;

  // actionvalue method debug_getResp
  input  EN_debug_getResp;
  output [32 : 0] debug_getResp;
  output RDY_debug_getResp;

  // value method debug_respAvail
  output debug_respAvail;
  output RDY_debug_respAvail;

  // value method debug_coreHalted
  output debug_coreHalted;
  output RDY_debug_coreHalted;

  // action method initWord
  input  [31 : 0] initWord_wordIdx;
  input  [31 : 0] initWord_v;
  input  EN_initWord;
  output RDY_initWord;

  // value method peekWord
  input  [31 : 0] peekWord_wordIdx;
  output [31 : 0] peekWord;
  output RDY_peekWord;

  // value method retired
  output retired;
  output RDY_retired;

  // signals for module outputs
  wire [32 : 0] debug_getResp;
  wire [31 : 0] peekWord;
  wire RDY_debug_coreHalted,
       RDY_debug_enqReq,
       RDY_debug_getResp,
       RDY_debug_respAvail,
       RDY_initWord,
       RDY_peekWord,
       RDY_retired,
       debug_coreHalted,
       debug_respAvail,
       retired;

  // register dbg_cur
  reg [71 : 0] dbg_cur;
  wire [71 : 0] dbg_cur$D_IN;
  wire dbg_cur$EN;

  // register dbg_st
  reg dbg_st;
  wire dbg_st$D_IN, dbg_st$EN;

  // register rdOwner
  reg [1 : 0] rdOwner;
  reg [1 : 0] rdOwner$D_IN;
  wire rdOwner$EN;

  // register wrOwner
  reg [1 : 0] wrOwner;
  reg [1 : 0] wrOwner$D_IN;
  wire wrOwner$EN;

  // ports of submodule cdc_haltB
  wire cdc_haltB$dD_OUT, cdc_haltB$sD_IN, cdc_haltB$sEN;

  // ports of submodule cdc_reqF
  wire [71 : 0] cdc_reqF$dD_OUT, cdc_reqF$sD_IN;
  wire cdc_reqF$dDEQ, cdc_reqF$dEMPTY_N, cdc_reqF$sENQ, cdc_reqF$sFULL_N;

  // ports of submodule cdc_respF
  wire [32 : 0] cdc_respF$dD_OUT, cdc_respF$sD_IN;
  wire cdc_respF$dDEQ, cdc_respF$dEMPTY_N, cdc_respF$sENQ, cdc_respF$sFULL_N;

  // ports of submodule core
  wire [35 : 0] core$dmem_w_get, core$imem_w_get;
  wire [34 : 0] core$dmem_ar_get,
		core$dmem_aw_get,
		core$imem_ar_get,
		core$imem_aw_get;
  wire [33 : 0] core$dmem_r_put, core$imem_r_put;
  wire [31 : 0] core$dbgGprRead, core$dbgGprWrite_v, core$dbgSetPc_a;
  wire [4 : 0] core$dbgGprRead_r, core$dbgGprWrite_r;
  wire [1 : 0] core$dmem_b_put, core$imem_b_put;
  wire core$EN_dbgGprWrite,
       core$EN_dbgSetPc,
       core$EN_dmem_ar_get,
       core$EN_dmem_aw_get,
       core$EN_dmem_b_put,
       core$EN_dmem_r_put,
       core$EN_dmem_w_get,
       core$EN_imem_ar_get,
       core$EN_imem_aw_get,
       core$EN_imem_b_put,
       core$EN_imem_r_put,
       core$EN_imem_w_get,
       core$EN_reqHalt,
       core$EN_reqStep,
       core$RDY_dmem_ar_get,
       core$RDY_dmem_aw_get,
       core$RDY_dmem_b_put,
       core$RDY_dmem_r_put,
       core$RDY_dmem_w_get,
       core$RDY_imem_ar_get,
       core$RDY_imem_aw_get,
       core$RDY_imem_b_put,
       core$RDY_imem_r_put,
       core$RDY_imem_w_get,
       core$isHalted,
       core$reqHalt_h,
       core$retired;

  // ports of submodule dbg_dmem
  wire [68 : 0] dbg_dmem$req_r;
  wire [35 : 0] dbg_dmem$axi_w_get;
  wire [34 : 0] dbg_dmem$axi_ar_get, dbg_dmem$axi_aw_get;
  wire [33 : 0] dbg_dmem$axi_r_put;
  wire [31 : 0] dbg_dmem$resp;
  wire [1 : 0] dbg_dmem$axi_b_put;
  wire dbg_dmem$EN_axi_ar_get,
       dbg_dmem$EN_axi_aw_get,
       dbg_dmem$EN_axi_b_put,
       dbg_dmem$EN_axi_r_put,
       dbg_dmem$EN_axi_w_get,
       dbg_dmem$EN_req,
       dbg_dmem$EN_resp,
       dbg_dmem$RDY_axi_ar_get,
       dbg_dmem$RDY_axi_aw_get,
       dbg_dmem$RDY_axi_b_put,
       dbg_dmem$RDY_axi_r_put,
       dbg_dmem$RDY_axi_w_get,
       dbg_dmem$RDY_req,
       dbg_dmem$RDY_resp;

  // ports of submodule mem
  reg [35 : 0] mem$slave_w_put;
  reg [34 : 0] mem$slave_ar_put, mem$slave_aw_put;
  wire [33 : 0] mem$slave_r_get;
  wire [31 : 0] mem$initWord_v,
		mem$initWord_wordIdx,
		mem$peekWord,
		mem$peekWord_wordIdx;
  wire [1 : 0] mem$slave_b_get;
  wire mem$EN_initWord,
       mem$EN_slave_ar_put,
       mem$EN_slave_aw_put,
       mem$EN_slave_b_get,
       mem$EN_slave_r_get,
       mem$EN_slave_w_put,
       mem$RDY_slave_ar_put,
       mem$RDY_slave_aw_put,
       mem$RDY_slave_b_get,
       mem$RDY_slave_r_get,
       mem$RDY_slave_w_put;

  // rule scheduling signals
  wire CAN_FIRE_RL_ar_dbg,
       CAN_FIRE_RL_ar_dmem,
       CAN_FIRE_RL_ar_imem,
       CAN_FIRE_RL_aw_dbg,
       CAN_FIRE_RL_aw_dmem,
       CAN_FIRE_RL_aw_imem,
       CAN_FIRE_RL_b_resp,
       CAN_FIRE_RL_dbg_doCmd,
       CAN_FIRE_RL_dbg_memDone,
       CAN_FIRE_RL_dbg_pubHalt,
       CAN_FIRE_RL_r_resp,
       CAN_FIRE_RL_w_dbg,
       CAN_FIRE_RL_w_dmem,
       CAN_FIRE_RL_w_imem,
       CAN_FIRE_debug_enqReq,
       CAN_FIRE_debug_getResp,
       CAN_FIRE_initWord,
       WILL_FIRE_RL_ar_dbg,
       WILL_FIRE_RL_ar_dmem,
       WILL_FIRE_RL_ar_imem,
       WILL_FIRE_RL_aw_dbg,
       WILL_FIRE_RL_aw_dmem,
       WILL_FIRE_RL_aw_imem,
       WILL_FIRE_RL_b_resp,
       WILL_FIRE_RL_dbg_doCmd,
       WILL_FIRE_RL_dbg_memDone,
       WILL_FIRE_RL_dbg_pubHalt,
       WILL_FIRE_RL_r_resp,
       WILL_FIRE_RL_w_dbg,
       WILL_FIRE_RL_w_dmem,
       WILL_FIRE_RL_w_imem,
       WILL_FIRE_debug_enqReq,
       WILL_FIRE_debug_getResp,
       WILL_FIRE_initWord;

  // inputs to muxes for submodule ports
  reg [32 : 0] MUX_cdc_respF$enq_1__VAL_1;
  wire [32 : 0] MUX_cdc_respF$enq_1__VAL_2;
  wire MUX_cdc_respF$enq_1__SEL_1, MUX_dbg_st$write_1__SEL_1;

  // remaining internal signals
  reg CASE_cdc_reqFdD_OUT_BITS_71_TO_69_2_cdc_respF_ETC__q2,
      CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1,
      CASE_rdOwner_1_coreRDY_imem_r_put_2_coreRDY__ETC__q3,
      CASE_wrOwner_1_coreRDY_imem_b_put_2_coreRDY__ETC__q4;
  wire [31 : 0] r_rdata__h1058;
  wire cdc_reqF_RDY_first_AND_IF_cdc_reqF_first_BITS__ETC___d30,
       cdc_reqF_first_BITS_71_TO_69_EQ_2_OR_cdc_reqF__ETC___d28,
       mem_RDY_slave_b_get__38_AND_IF_wrOwner_10_EQ_1_ETC___d146,
       mem_RDY_slave_r_get__2_AND_IF_rdOwner_0_EQ_1_3_ETC___d103;

  // action method debug_enqReq
  assign RDY_debug_enqReq = cdc_reqF$sFULL_N ;
  assign CAN_FIRE_debug_enqReq = cdc_reqF$sFULL_N ;
  assign WILL_FIRE_debug_enqReq = EN_debug_enqReq ;

  // actionvalue method debug_getResp
  assign debug_getResp = cdc_respF$dD_OUT ;
  assign RDY_debug_getResp = cdc_respF$dEMPTY_N ;
  assign CAN_FIRE_debug_getResp = cdc_respF$dEMPTY_N ;
  assign WILL_FIRE_debug_getResp = EN_debug_getResp ;

  // value method debug_respAvail
  assign debug_respAvail = cdc_respF$dEMPTY_N ;
  assign RDY_debug_respAvail = 1'd1 ;

  // value method debug_coreHalted
  assign debug_coreHalted = cdc_haltB$dD_OUT ;
  assign RDY_debug_coreHalted = 1'd1 ;

  // action method initWord
  assign RDY_initWord = 1'd1 ;
  assign CAN_FIRE_initWord = 1'd1 ;
  assign WILL_FIRE_initWord = EN_initWord ;

  // value method peekWord
  assign peekWord = mem$peekWord ;
  assign RDY_peekWord = 1'd1 ;

  // value method retired
  assign retired = core$retired ;
  assign RDY_retired = 1'd1 ;

  // submodule cdc_haltB
  SyncBit #(.init(1'd0)) cdc_haltB(.sCLK(CLK),
				   .dCLK(CLK_dClk),
				   .sRST(RST_N),
				   .sD_IN(cdc_haltB$sD_IN),
				   .sEN(cdc_haltB$sEN),
				   .dD_OUT(cdc_haltB$dD_OUT));

  // submodule cdc_reqF
  SyncFIFO #(.dataWidth(32'd72),
	     .depth(32'd2),
	     .indxWidth(32'd1)) cdc_reqF(.sCLK(CLK_dClk),
					 .dCLK(CLK),
					 .sRST(RST_N_dRst),
					 .sD_IN(cdc_reqF$sD_IN),
					 .sENQ(cdc_reqF$sENQ),
					 .dDEQ(cdc_reqF$dDEQ),
					 .sFULL_N(cdc_reqF$sFULL_N),
					 .dEMPTY_N(cdc_reqF$dEMPTY_N),
					 .dD_OUT(cdc_reqF$dD_OUT));

  // submodule cdc_respF
  SyncFIFO #(.dataWidth(32'd33),
	     .depth(32'd2),
	     .indxWidth(32'd1)) cdc_respF(.sCLK(CLK),
					  .dCLK(CLK_dClk),
					  .sRST(RST_N),
					  .sD_IN(cdc_respF$sD_IN),
					  .sENQ(cdc_respF$sENQ),
					  .dDEQ(cdc_respF$dDEQ),
					  .sFULL_N(cdc_respF$sFULL_N),
					  .dEMPTY_N(cdc_respF$dEMPTY_N),
					  .dD_OUT(cdc_respF$dD_OUT));

  // submodule core
  mkCore core(.CLK(CLK),
	      .RST_N(RST_N),
	      .dbgGprRead_r(core$dbgGprRead_r),
	      .dbgGprWrite_r(core$dbgGprWrite_r),
	      .dbgGprWrite_v(core$dbgGprWrite_v),
	      .dbgSetPc_a(core$dbgSetPc_a),
	      .dmem_b_put(core$dmem_b_put),
	      .dmem_r_put(core$dmem_r_put),
	      .imem_b_put(core$imem_b_put),
	      .imem_r_put(core$imem_r_put),
	      .reqHalt_h(core$reqHalt_h),
	      .EN_imem_aw_get(core$EN_imem_aw_get),
	      .EN_imem_w_get(core$EN_imem_w_get),
	      .EN_imem_b_put(core$EN_imem_b_put),
	      .EN_imem_ar_get(core$EN_imem_ar_get),
	      .EN_imem_r_put(core$EN_imem_r_put),
	      .EN_dmem_aw_get(core$EN_dmem_aw_get),
	      .EN_dmem_w_get(core$EN_dmem_w_get),
	      .EN_dmem_b_put(core$EN_dmem_b_put),
	      .EN_dmem_ar_get(core$EN_dmem_ar_get),
	      .EN_dmem_r_put(core$EN_dmem_r_put),
	      .EN_reqHalt(core$EN_reqHalt),
	      .EN_reqStep(core$EN_reqStep),
	      .EN_dbgGprWrite(core$EN_dbgGprWrite),
	      .EN_dbgSetPc(core$EN_dbgSetPc),
	      .imem_aw_get(core$imem_aw_get),
	      .RDY_imem_aw_get(core$RDY_imem_aw_get),
	      .imem_w_get(core$imem_w_get),
	      .RDY_imem_w_get(core$RDY_imem_w_get),
	      .RDY_imem_b_put(core$RDY_imem_b_put),
	      .imem_ar_get(core$imem_ar_get),
	      .RDY_imem_ar_get(core$RDY_imem_ar_get),
	      .RDY_imem_r_put(core$RDY_imem_r_put),
	      .dmem_aw_get(core$dmem_aw_get),
	      .RDY_dmem_aw_get(core$RDY_dmem_aw_get),
	      .dmem_w_get(core$dmem_w_get),
	      .RDY_dmem_w_get(core$RDY_dmem_w_get),
	      .RDY_dmem_b_put(core$RDY_dmem_b_put),
	      .dmem_ar_get(core$dmem_ar_get),
	      .RDY_dmem_ar_get(core$RDY_dmem_ar_get),
	      .RDY_dmem_r_put(core$RDY_dmem_r_put),
	      .RDY_reqHalt(),
	      .RDY_reqStep(),
	      .isHalted(core$isHalted),
	      .RDY_isHalted(),
	      .dbgGprRead(core$dbgGprRead),
	      .RDY_dbgGprRead(),
	      .RDY_dbgGprWrite(),
	      .dbgPc(),
	      .RDY_dbgPc(),
	      .RDY_dbgSetPc(),
	      .retired(core$retired),
	      .RDY_retired());

  // submodule dbg_dmem
  mkMemPort dbg_dmem(.CLK(CLK),
		     .RST_N(RST_N),
		     .axi_b_put(dbg_dmem$axi_b_put),
		     .axi_r_put(dbg_dmem$axi_r_put),
		     .req_r(dbg_dmem$req_r),
		     .EN_req(dbg_dmem$EN_req),
		     .EN_resp(dbg_dmem$EN_resp),
		     .EN_axi_aw_get(dbg_dmem$EN_axi_aw_get),
		     .EN_axi_w_get(dbg_dmem$EN_axi_w_get),
		     .EN_axi_b_put(dbg_dmem$EN_axi_b_put),
		     .EN_axi_ar_get(dbg_dmem$EN_axi_ar_get),
		     .EN_axi_r_put(dbg_dmem$EN_axi_r_put),
		     .RDY_req(dbg_dmem$RDY_req),
		     .resp(dbg_dmem$resp),
		     .RDY_resp(dbg_dmem$RDY_resp),
		     .canReq(),
		     .RDY_canReq(),
		     .respReady(),
		     .RDY_respReady(),
		     .axi_aw_get(dbg_dmem$axi_aw_get),
		     .RDY_axi_aw_get(dbg_dmem$RDY_axi_aw_get),
		     .axi_w_get(dbg_dmem$axi_w_get),
		     .RDY_axi_w_get(dbg_dmem$RDY_axi_w_get),
		     .RDY_axi_b_put(dbg_dmem$RDY_axi_b_put),
		     .axi_ar_get(dbg_dmem$axi_ar_get),
		     .RDY_axi_ar_get(dbg_dmem$RDY_axi_ar_get),
		     .RDY_axi_r_put(dbg_dmem$RDY_axi_r_put));

  // submodule mem
  mkBramMem mem(.CLK(CLK),
		.RST_N(RST_N),
		.initWord_v(mem$initWord_v),
		.initWord_wordIdx(mem$initWord_wordIdx),
		.peekWord_wordIdx(mem$peekWord_wordIdx),
		.slave_ar_put(mem$slave_ar_put),
		.slave_aw_put(mem$slave_aw_put),
		.slave_w_put(mem$slave_w_put),
		.EN_slave_aw_put(mem$EN_slave_aw_put),
		.EN_slave_w_put(mem$EN_slave_w_put),
		.EN_slave_b_get(mem$EN_slave_b_get),
		.EN_slave_ar_put(mem$EN_slave_ar_put),
		.EN_slave_r_get(mem$EN_slave_r_get),
		.EN_initWord(mem$EN_initWord),
		.RDY_slave_aw_put(mem$RDY_slave_aw_put),
		.RDY_slave_w_put(mem$RDY_slave_w_put),
		.slave_b_get(mem$slave_b_get),
		.RDY_slave_b_get(mem$RDY_slave_b_get),
		.RDY_slave_ar_put(mem$RDY_slave_ar_put),
		.slave_r_get(mem$slave_r_get),
		.RDY_slave_r_get(mem$RDY_slave_r_get),
		.RDY_initWord(),
		.peekWord(mem$peekWord),
		.RDY_peekWord());

  // rule RL_ar_imem
  assign CAN_FIRE_RL_ar_imem =
	     mem$RDY_slave_ar_put && core$RDY_imem_ar_get && rdOwner == 2'd0 ;
  assign WILL_FIRE_RL_ar_imem = CAN_FIRE_RL_ar_imem ;

  // rule RL_ar_dmem
  assign CAN_FIRE_RL_ar_dmem =
	     mem$RDY_slave_ar_put && core$RDY_dmem_ar_get && rdOwner == 2'd0 ;
  assign WILL_FIRE_RL_ar_dmem = CAN_FIRE_RL_ar_dmem && !WILL_FIRE_RL_ar_imem ;

  // rule RL_ar_dbg
  assign CAN_FIRE_RL_ar_dbg =
	     mem$RDY_slave_ar_put && dbg_dmem$RDY_axi_ar_get &&
	     rdOwner == 2'd0 ;
  assign WILL_FIRE_RL_ar_dbg =
	     CAN_FIRE_RL_ar_dbg && !WILL_FIRE_RL_ar_dmem &&
	     !WILL_FIRE_RL_ar_imem ;

  // rule RL_r_resp
  assign CAN_FIRE_RL_r_resp =
	     mem_RDY_slave_r_get__2_AND_IF_rdOwner_0_EQ_1_3_ETC___d103 &&
	     rdOwner != 2'd0 ;
  assign WILL_FIRE_RL_r_resp = CAN_FIRE_RL_r_resp ;

  // rule RL_aw_imem
  assign CAN_FIRE_RL_aw_imem =
	     mem$RDY_slave_aw_put && core$RDY_imem_aw_get && wrOwner == 2'd0 ;
  assign WILL_FIRE_RL_aw_imem = CAN_FIRE_RL_aw_imem ;

  // rule RL_aw_dmem
  assign CAN_FIRE_RL_aw_dmem =
	     mem$RDY_slave_aw_put && core$RDY_dmem_aw_get && wrOwner == 2'd0 ;
  assign WILL_FIRE_RL_aw_dmem = CAN_FIRE_RL_aw_dmem && !WILL_FIRE_RL_aw_imem ;

  // rule RL_aw_dbg
  assign CAN_FIRE_RL_aw_dbg =
	     mem$RDY_slave_aw_put && dbg_dmem$RDY_axi_aw_get &&
	     wrOwner == 2'd0 ;
  assign WILL_FIRE_RL_aw_dbg =
	     CAN_FIRE_RL_aw_dbg && !WILL_FIRE_RL_aw_dmem &&
	     !WILL_FIRE_RL_aw_imem ;

  // rule RL_w_imem
  assign CAN_FIRE_RL_w_imem =
	     mem$RDY_slave_w_put && core$RDY_imem_w_get && wrOwner == 2'd1 ;
  assign WILL_FIRE_RL_w_imem = CAN_FIRE_RL_w_imem ;

  // rule RL_w_dmem
  assign CAN_FIRE_RL_w_dmem =
	     mem$RDY_slave_w_put && core$RDY_dmem_w_get && wrOwner == 2'd2 ;
  assign WILL_FIRE_RL_w_dmem = CAN_FIRE_RL_w_dmem ;

  // rule RL_w_dbg
  assign CAN_FIRE_RL_w_dbg =
	     mem$RDY_slave_w_put && dbg_dmem$RDY_axi_w_get &&
	     wrOwner == 2'd3 ;
  assign WILL_FIRE_RL_w_dbg = CAN_FIRE_RL_w_dbg ;

  // rule RL_b_resp
  assign CAN_FIRE_RL_b_resp =
	     mem_RDY_slave_b_get__38_AND_IF_wrOwner_10_EQ_1_ETC___d146 &&
	     wrOwner != 2'd0 ;
  assign WILL_FIRE_RL_b_resp = CAN_FIRE_RL_b_resp ;

  // rule RL_dbg_pubHalt
  assign CAN_FIRE_RL_dbg_pubHalt = 1'd1 ;
  assign WILL_FIRE_RL_dbg_pubHalt = 1'd1 ;

  // rule RL_dbg_doCmd
  assign CAN_FIRE_RL_dbg_doCmd =
	     cdc_reqF$dEMPTY_N &&
	     cdc_reqF_RDY_first_AND_IF_cdc_reqF_first_BITS__ETC___d30 &&
	     !dbg_st ;
  assign WILL_FIRE_RL_dbg_doCmd = CAN_FIRE_RL_dbg_doCmd ;

  // rule RL_dbg_memDone
  assign CAN_FIRE_RL_dbg_memDone =
	     cdc_respF$sFULL_N && dbg_dmem$RDY_resp && dbg_st ;
  assign WILL_FIRE_RL_dbg_memDone = CAN_FIRE_RL_dbg_memDone ;

  // inputs to muxes for submodule ports
  assign MUX_cdc_respF$enq_1__SEL_1 =
	     WILL_FIRE_RL_dbg_doCmd && cdc_reqF$dD_OUT[71:69] != 3'd6 &&
	     cdc_reqF$dD_OUT[71:69] != 3'd7 ;
  assign MUX_dbg_st$write_1__SEL_1 =
	     WILL_FIRE_RL_dbg_doCmd &&
	     (cdc_reqF$dD_OUT[71:69] == 3'd6 ||
	      cdc_reqF$dD_OUT[71:69] == 3'd7) ;
  always@(cdc_reqF$dD_OUT or core$isHalted or core$dbgGprRead)
  begin
    case (cdc_reqF$dD_OUT[71:69])
      3'd1, 3'd3: MUX_cdc_respF$enq_1__VAL_1 = 33'h100000000;
      3'd2: MUX_cdc_respF$enq_1__VAL_1 = 33'd0;
      default: MUX_cdc_respF$enq_1__VAL_1 =
		   { core$isHalted,
		     (cdc_reqF$dD_OUT[71:69] == 3'd4) ?
		       core$dbgGprRead :
		       32'd0 };
    endcase
  end
  assign MUX_cdc_respF$enq_1__VAL_2 = { core$isHalted, r_rdata__h1058 } ;

  // register dbg_cur
  assign dbg_cur$D_IN = cdc_reqF$dD_OUT ;
  assign dbg_cur$EN = CAN_FIRE_RL_dbg_doCmd ;

  // register dbg_st
  assign dbg_st$D_IN = MUX_dbg_st$write_1__SEL_1 ;
  assign dbg_st$EN =
	     WILL_FIRE_RL_dbg_doCmd &&
	     (cdc_reqF$dD_OUT[71:69] == 3'd6 ||
	      cdc_reqF$dD_OUT[71:69] == 3'd7) ||
	     WILL_FIRE_RL_dbg_memDone ;

  // register rdOwner
  always@(WILL_FIRE_RL_r_resp or
	  WILL_FIRE_RL_ar_imem or WILL_FIRE_RL_ar_dmem or WILL_FIRE_RL_ar_dbg)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_r_resp: rdOwner$D_IN = 2'd0;
      WILL_FIRE_RL_ar_imem: rdOwner$D_IN = 2'd1;
      WILL_FIRE_RL_ar_dmem: rdOwner$D_IN = 2'd2;
      WILL_FIRE_RL_ar_dbg: rdOwner$D_IN = 2'd3;
      default: rdOwner$D_IN = 2'b10 /* unspecified value */ ;
    endcase
  end
  assign rdOwner$EN =
	     WILL_FIRE_RL_r_resp || WILL_FIRE_RL_ar_imem ||
	     WILL_FIRE_RL_ar_dmem ||
	     WILL_FIRE_RL_ar_dbg ;

  // register wrOwner
  always@(WILL_FIRE_RL_b_resp or
	  WILL_FIRE_RL_aw_imem or WILL_FIRE_RL_aw_dmem or WILL_FIRE_RL_aw_dbg)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_b_resp: wrOwner$D_IN = 2'd0;
      WILL_FIRE_RL_aw_imem: wrOwner$D_IN = 2'd1;
      WILL_FIRE_RL_aw_dmem: wrOwner$D_IN = 2'd2;
      WILL_FIRE_RL_aw_dbg: wrOwner$D_IN = 2'd3;
      default: wrOwner$D_IN = 2'b10 /* unspecified value */ ;
    endcase
  end
  assign wrOwner$EN =
	     WILL_FIRE_RL_b_resp || WILL_FIRE_RL_aw_imem ||
	     WILL_FIRE_RL_aw_dmem ||
	     WILL_FIRE_RL_aw_dbg ;

  // submodule cdc_haltB
  assign cdc_haltB$sD_IN = core$isHalted ;
  assign cdc_haltB$sEN = 1'd1 ;

  // submodule cdc_reqF
  assign cdc_reqF$sD_IN = debug_enqReq_r ;
  assign cdc_reqF$sENQ = EN_debug_enqReq ;
  assign cdc_reqF$dDEQ = CAN_FIRE_RL_dbg_doCmd ;

  // submodule cdc_respF
  assign cdc_respF$sD_IN =
	     MUX_cdc_respF$enq_1__SEL_1 ?
	       MUX_cdc_respF$enq_1__VAL_1 :
	       MUX_cdc_respF$enq_1__VAL_2 ;
  assign cdc_respF$sENQ =
	     WILL_FIRE_RL_dbg_doCmd && cdc_reqF$dD_OUT[71:69] != 3'd6 &&
	     cdc_reqF$dD_OUT[71:69] != 3'd7 ||
	     WILL_FIRE_RL_dbg_memDone ;
  assign cdc_respF$dDEQ = EN_debug_getResp ;

  // submodule core
  assign core$dbgGprRead_r = cdc_reqF$dD_OUT[68:64] ;
  assign core$dbgGprWrite_r = cdc_reqF$dD_OUT[68:64] ;
  assign core$dbgGprWrite_v = cdc_reqF$dD_OUT[31:0] ;
  assign core$dbgSetPc_a = 32'h0 ;
  assign core$dmem_b_put = mem$slave_b_get ;
  assign core$dmem_r_put = mem$slave_r_get ;
  assign core$imem_b_put = mem$slave_b_get ;
  assign core$imem_r_put = mem$slave_r_get ;
  assign core$reqHalt_h = cdc_reqF$dD_OUT[71:69] == 3'd1 ;
  assign core$EN_imem_aw_get = CAN_FIRE_RL_aw_imem ;
  assign core$EN_imem_w_get = CAN_FIRE_RL_w_imem ;
  assign core$EN_imem_b_put = WILL_FIRE_RL_b_resp && wrOwner == 2'd1 ;
  assign core$EN_imem_ar_get = CAN_FIRE_RL_ar_imem ;
  assign core$EN_imem_r_put = WILL_FIRE_RL_r_resp && rdOwner == 2'd1 ;
  assign core$EN_dmem_aw_get = WILL_FIRE_RL_aw_dmem ;
  assign core$EN_dmem_w_get = CAN_FIRE_RL_w_dmem ;
  assign core$EN_dmem_b_put = WILL_FIRE_RL_b_resp && wrOwner == 2'd2 ;
  assign core$EN_dmem_ar_get = WILL_FIRE_RL_ar_dmem ;
  assign core$EN_dmem_r_put = WILL_FIRE_RL_r_resp && rdOwner == 2'd2 ;
  assign core$EN_reqHalt =
	     WILL_FIRE_RL_dbg_doCmd &&
	     (cdc_reqF$dD_OUT[71:69] == 3'd1 ||
	      cdc_reqF$dD_OUT[71:69] == 3'd2) ;
  assign core$EN_reqStep =
	     WILL_FIRE_RL_dbg_doCmd && cdc_reqF$dD_OUT[71:69] == 3'd3 ;
  assign core$EN_dbgGprWrite =
	     WILL_FIRE_RL_dbg_doCmd && cdc_reqF$dD_OUT[71:69] == 3'd5 ;
  assign core$EN_dbgSetPc = 1'b0 ;

  // submodule dbg_dmem
  assign dbg_dmem$axi_b_put = mem$slave_b_get ;
  assign dbg_dmem$axi_r_put = mem$slave_r_get ;
  assign dbg_dmem$req_r =
	     { cdc_reqF$dD_OUT[63:32],
	       (cdc_reqF$dD_OUT[71:69] == 3'd6) ?
		 37'd0 :
		 { 1'd1, cdc_reqF$dD_OUT[31:0], 4'b1111 } } ;
  assign dbg_dmem$EN_req = MUX_dbg_st$write_1__SEL_1 ;
  assign dbg_dmem$EN_resp = CAN_FIRE_RL_dbg_memDone ;
  assign dbg_dmem$EN_axi_aw_get = WILL_FIRE_RL_aw_dbg ;
  assign dbg_dmem$EN_axi_w_get = CAN_FIRE_RL_w_dbg ;
  assign dbg_dmem$EN_axi_b_put = WILL_FIRE_RL_b_resp && wrOwner == 2'd3 ;
  assign dbg_dmem$EN_axi_ar_get = WILL_FIRE_RL_ar_dbg ;
  assign dbg_dmem$EN_axi_r_put = WILL_FIRE_RL_r_resp && rdOwner == 2'd3 ;

  // submodule mem
  assign mem$initWord_v = initWord_v ;
  assign mem$initWord_wordIdx = initWord_wordIdx ;
  assign mem$peekWord_wordIdx = peekWord_wordIdx ;
  always@(WILL_FIRE_RL_ar_imem or
	  core$imem_ar_get or
	  WILL_FIRE_RL_ar_dmem or
	  core$dmem_ar_get or WILL_FIRE_RL_ar_dbg or dbg_dmem$axi_ar_get)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_ar_imem: mem$slave_ar_put = core$imem_ar_get;
      WILL_FIRE_RL_ar_dmem: mem$slave_ar_put = core$dmem_ar_get;
      WILL_FIRE_RL_ar_dbg: mem$slave_ar_put = dbg_dmem$axi_ar_get;
      default: mem$slave_ar_put = 35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_aw_imem or
	  core$imem_aw_get or
	  WILL_FIRE_RL_aw_dmem or
	  core$dmem_aw_get or WILL_FIRE_RL_aw_dbg or dbg_dmem$axi_aw_get)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_aw_imem: mem$slave_aw_put = core$imem_aw_get;
      WILL_FIRE_RL_aw_dmem: mem$slave_aw_put = core$dmem_aw_get;
      WILL_FIRE_RL_aw_dbg: mem$slave_aw_put = dbg_dmem$axi_aw_get;
      default: mem$slave_aw_put = 35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_w_imem or
	  core$imem_w_get or
	  WILL_FIRE_RL_w_dmem or
	  core$dmem_w_get or WILL_FIRE_RL_w_dbg or dbg_dmem$axi_w_get)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_w_imem: mem$slave_w_put = core$imem_w_get;
      WILL_FIRE_RL_w_dmem: mem$slave_w_put = core$dmem_w_get;
      WILL_FIRE_RL_w_dbg: mem$slave_w_put = dbg_dmem$axi_w_get;
      default: mem$slave_w_put = 36'hAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign mem$EN_slave_aw_put =
	     WILL_FIRE_RL_aw_imem || WILL_FIRE_RL_aw_dmem ||
	     WILL_FIRE_RL_aw_dbg ;
  assign mem$EN_slave_w_put =
	     WILL_FIRE_RL_w_imem || WILL_FIRE_RL_w_dmem ||
	     WILL_FIRE_RL_w_dbg ;
  assign mem$EN_slave_b_get = CAN_FIRE_RL_b_resp ;
  assign mem$EN_slave_ar_put =
	     WILL_FIRE_RL_ar_imem || WILL_FIRE_RL_ar_dmem ||
	     WILL_FIRE_RL_ar_dbg ;
  assign mem$EN_slave_r_get = CAN_FIRE_RL_r_resp ;
  assign mem$EN_initWord = EN_initWord ;

  // remaining internal signals
  assign cdc_reqF_RDY_first_AND_IF_cdc_reqF_first_BITS__ETC___d30 =
	     cdc_reqF$dEMPTY_N &&
	     ((cdc_reqF$dD_OUT[71:69] == 3'd1) ?
		cdc_respF$sFULL_N :
		cdc_reqF_first_BITS_71_TO_69_EQ_2_OR_cdc_reqF__ETC___d28) ;
  assign cdc_reqF_first_BITS_71_TO_69_EQ_2_OR_cdc_reqF__ETC___d28 =
	     (cdc_reqF$dD_OUT[71:69] == 3'd2 ||
	      cdc_reqF$dD_OUT[71:69] == 3'd3 ||
	      ((cdc_reqF$dD_OUT[71:69] == 3'd4) ?
		 cdc_respF$sFULL_N :
		 cdc_reqF$dD_OUT[71:69] == 3'd5 ||
		 cdc_reqF$dD_OUT[71:69] == 3'd6 ||
		 cdc_reqF$dD_OUT[71:69] == 3'd7 ||
		 cdc_respF$sFULL_N)) &&
	     CASE_cdc_reqFdD_OUT_BITS_71_TO_69_2_cdc_respF_ETC__q2 ;
  assign mem_RDY_slave_b_get__38_AND_IF_wrOwner_10_EQ_1_ETC___d146 =
	     mem$RDY_slave_b_get &&
	     CASE_wrOwner_1_coreRDY_imem_b_put_2_coreRDY__ETC__q4 ;
  assign mem_RDY_slave_r_get__2_AND_IF_rdOwner_0_EQ_1_3_ETC___d103 =
	     mem$RDY_slave_r_get &&
	     CASE_rdOwner_1_coreRDY_imem_r_put_2_coreRDY__ETC__q3 ;
  assign r_rdata__h1058 = (dbg_cur[71:69] == 3'd6) ? dbg_dmem$resp : 32'd0 ;
  always@(cdc_reqF$dD_OUT or dbg_dmem$RDY_req or cdc_respF$sFULL_N)
  begin
    case (cdc_reqF$dD_OUT[71:69])
      3'd5:
	  CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1 =
	      cdc_respF$sFULL_N;
      3'd6:
	  CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1 =
	      dbg_dmem$RDY_req;
      default: CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1 =
		   cdc_reqF$dD_OUT[71:69] != 3'd7 || dbg_dmem$RDY_req;
    endcase
  end
  always@(cdc_reqF$dD_OUT or
	  CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1 or
	  cdc_respF$sFULL_N)
  begin
    case (cdc_reqF$dD_OUT[71:69])
      3'd2, 3'd3:
	  CASE_cdc_reqFdD_OUT_BITS_71_TO_69_2_cdc_respF_ETC__q2 =
	      cdc_respF$sFULL_N;
      default: CASE_cdc_reqFdD_OUT_BITS_71_TO_69_2_cdc_respF_ETC__q2 =
		   CASE_cdc_reqFdD_OUT_BITS_71_TO_69_5_cdc_respF_ETC__q1;
    endcase
  end
  always@(rdOwner or
	  dbg_dmem$RDY_axi_r_put or
	  core$RDY_imem_r_put or core$RDY_dmem_r_put)
  begin
    case (rdOwner)
      2'd1:
	  CASE_rdOwner_1_coreRDY_imem_r_put_2_coreRDY__ETC__q3 =
	      core$RDY_imem_r_put;
      2'd2:
	  CASE_rdOwner_1_coreRDY_imem_r_put_2_coreRDY__ETC__q3 =
	      core$RDY_dmem_r_put;
      default: CASE_rdOwner_1_coreRDY_imem_r_put_2_coreRDY__ETC__q3 =
		   rdOwner != 2'd3 || dbg_dmem$RDY_axi_r_put;
    endcase
  end
  always@(wrOwner or
	  dbg_dmem$RDY_axi_b_put or
	  core$RDY_imem_b_put or core$RDY_dmem_b_put)
  begin
    case (wrOwner)
      2'd1:
	  CASE_wrOwner_1_coreRDY_imem_b_put_2_coreRDY__ETC__q4 =
	      core$RDY_imem_b_put;
      2'd2:
	  CASE_wrOwner_1_coreRDY_imem_b_put_2_coreRDY__ETC__q4 =
	      core$RDY_dmem_b_put;
      default: CASE_wrOwner_1_coreRDY_imem_b_put_2_coreRDY__ETC__q4 =
		   wrOwner != 2'd3 || dbg_dmem$RDY_axi_b_put;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dbg_st <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rdOwner <= `BSV_ASSIGNMENT_DELAY 2'd0;
	wrOwner <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (dbg_st$EN) dbg_st <= `BSV_ASSIGNMENT_DELAY dbg_st$D_IN;
	if (rdOwner$EN) rdOwner <= `BSV_ASSIGNMENT_DELAY rdOwner$D_IN;
	if (wrOwner$EN) wrOwner <= `BSV_ASSIGNMENT_DELAY wrOwner$D_IN;
      end
    if (dbg_cur$EN) dbg_cur <= `BSV_ASSIGNMENT_DELAY dbg_cur$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dbg_cur = 72'hAAAAAAAAAAAAAAAAAA;
    dbg_st = 1'h0;
    rdOwner = 2'h2;
    wrOwner = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSoC

