//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// forward                        O     4
// forward_rs1                    I     5
// forward_rs2                    I     5
// forward_exRd                   I     5
// forward_exWr                   I     1
// forward_memRd                  I     5
// forward_memWr                  I     1
//
// Combinational paths from inputs to outputs:
//   (forward_rs1,
//    forward_rs2,
//    forward_exRd,
//    forward_exWr,
//    forward_memRd,
//    forward_memWr) -> forward
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_forward(forward_rs1,
		      forward_rs2,
		      forward_exRd,
		      forward_exWr,
		      forward_memRd,
		      forward_memWr,
		      forward);
  // value method forward
  input  [4 : 0] forward_rs1;
  input  [4 : 0] forward_rs2;
  input  [4 : 0] forward_exRd;
  input  forward_exWr;
  input  [4 : 0] forward_memRd;
  input  forward_memWr;
  output [3 : 0] forward;

  // signals for module outputs
  wire [3 : 0] forward;

  // remaining internal signals
  wire [1 : 0] IF_NOT_forward_rs1_EQ_0_AND_forward_exWr_AND_f_ETC___d10,
	       IF_NOT_forward_rs1_EQ_0_AND_forward_memWr_AND__ETC___d9,
	       IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_exWr_3_ETC___d20,
	       IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_memWr__ETC___d19;

  // value method forward
  assign forward =
	     { IF_NOT_forward_rs1_EQ_0_AND_forward_exWr_AND_f_ETC___d10,
	       IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_exWr_3_ETC___d20 } ;

  // remaining internal signals
  assign IF_NOT_forward_rs1_EQ_0_AND_forward_exWr_AND_f_ETC___d10 =
	     (forward_rs1 != 5'd0 && forward_exWr &&
	      forward_exRd == forward_rs1) ?
	       2'd1 :
	       IF_NOT_forward_rs1_EQ_0_AND_forward_memWr_AND__ETC___d9 ;
  assign IF_NOT_forward_rs1_EQ_0_AND_forward_memWr_AND__ETC___d9 =
	     (forward_rs1 != 5'd0 && forward_memWr &&
	      forward_memRd == forward_rs1) ?
	       2'd2 :
	       2'd0 ;
  assign IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_exWr_3_ETC___d20 =
	     (forward_rs2 != 5'd0 && forward_exWr &&
	      forward_exRd == forward_rs2) ?
	       2'd1 :
	       IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_memWr__ETC___d19 ;
  assign IF_NOT_forward_rs2_EQ_0_1_2_AND_forward_memWr__ETC___d19 =
	     (forward_rs2 != 5'd0 && forward_memWr &&
	      forward_memRd == forward_rs2) ?
	       2'd2 :
	       2'd0 ;
endmodule  // module_forward

