//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// control                        O    31
// control_d                      I    76
//
// Combinational paths from inputs to outputs:
//   control_d -> control
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_control(control_d,
		      control);
  // value method control
  input  [75 : 0] control_d;
  output [30 : 0] control;

  // signals for module outputs
  wire [30 : 0] control;

  // remaining internal signals
  reg [3 : 0] CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1,
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2,
	      CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3,
	      IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29,
	      IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54;
  reg [2 : 0] CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5,
	      CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12,
	      CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q7,
	      CASE_control_d_BITS_75_TO_69_0b10111_0_0b11011_ETC__q6,
	      CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q8,
	      CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13;
  reg [1 : 0] CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16,
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14,
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9,
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10,
	      CASE_control_d_BITS_75_TO_69_0b10111_1_0b11011_ETC__q4,
	      CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q15,
	      CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q17,
	      CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11;
  reg CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18,
      CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19;
  wire [3 : 0] IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25;

  // value method control
  assign control =
	     { CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3,
	       CASE_control_d_BITS_75_TO_69_0b10111_1_0b11011_ETC__q4,
	       control_d[75:69] == 7'b0110111 ||
	       control_d[75:69] == 7'b0010111 ||
	       control_d[75:69] == 7'b0000011 ||
	       control_d[75:69] == 7'b0100011 ||
	       control_d[75:69] == 7'b0010011,
	       CASE_control_d_BITS_75_TO_69_0b10111_0_0b11011_ETC__q6,
	       control_d[75:69] == 7'b1101111 ||
	       control_d[75:69] == 7'b1100111 && control_d[53:51] == 3'b0,
	       control_d[75:69] == 7'b1100111 && control_d[53:51] == 3'b0,
	       control_d[75:69] == 7'b0110011 &&
	       control_d[50:44] == 7'b0000001,
	       CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q8,
	       control_d[75:69] == 7'b0000011,
	       control_d[75:69] == 7'b0100011,
	       CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11,
	       control_d[75:69] == 7'b0000011 &&
	       (control_d[53:51] == 3'b100 || control_d[53:51] == 3'b101),
	       control_d[75:69] == 7'b0110111 ||
	       control_d[75:69] == 7'b0010111 ||
	       control_d[75:69] == 7'b1101111 ||
	       ((control_d[75:69] == 7'b1100111) ?
		  control_d[53:51] == 3'b0 :
		  control_d[75:69] == 7'b0000011 ||
		  control_d[75:69] == 7'b0010011 ||
		  control_d[75:69] == 7'b0110011 ||
		  control_d[75:69] == 7'b1110011 &&
		  (control_d[53:51] == 3'b001 || control_d[53:51] == 3'b010 ||
		   control_d[53:51] == 3'b011 ||
		   control_d[53:51] == 3'b101 ||
		   control_d[53:51] == 3'b110 ||
		   control_d[53:51] == 3'b111)),
	       CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13,
	       CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q15,
	       control_d[75:69] == 7'b1110011 &&
	       (control_d[53:51] == 3'b101 || control_d[53:51] == 3'b110 ||
		control_d[53:51] == 3'b111),
	       CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q17,
	       control_d[75:69] != 7'b0110111 &&
	       control_d[75:69] != 7'b0010111 &&
	       control_d[75:69] != 7'b1101111 &&
	       CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 } ;

  // remaining internal signals
  assign IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25 =
	     (control_d[50:44] == 7'b0) ? 4'd2 : 4'd0 ;
  always@(control_d)
  begin
    case (control_d[50:44])
      7'b0: IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29 = 4'd6;
      7'b0100000:
	  IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29 = 4'd7;
      default: IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29 =
		   4'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[50:44])
      7'b0: CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1 = 4'd0;
      7'b0100000: CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1 = 4'd1;
      default: CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1 = 4'd0;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1 or
	  IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25 or
	  IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29)
  begin
    case (control_d[53:51])
      3'b0:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      CASE_control_d_BITS_50_TO_44_0b0_0_0b100000_1_0__q1;
      3'b001:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25;
      3'b010:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      (control_d[50:44] == 7'b0) ? 4'd3 : 4'd0;
      3'b011:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      (control_d[50:44] == 7'b0) ? 4'd4 : 4'd0;
      3'b100:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      (control_d[50:44] == 7'b0) ? 4'd5 : 4'd0;
      3'b101:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29;
      3'b110:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      (control_d[50:44] == 7'b0) ? 4'd8 : 4'd0;
      3'b111:
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54 =
	      (control_d[50:44] == 7'b0) ? 4'd9 : 4'd0;
    endcase
  end
  always@(control_d or
	  IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25 or
	  IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29)
  begin
    case (control_d[53:51])
      3'b0: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd0;
      3'b001:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 =
	      IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_2_E_ETC___d25;
      3'b010: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd3;
      3'b011: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd4;
      3'b100: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd5;
      3'b101:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 =
	      IF_control_d_BITS_50_TO_44_3_EQ_0b0_4_THEN_6_E_ETC___d29;
      3'b110: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd8;
      3'b111: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 = 4'd9;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2 or
	  IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54)
  begin
    case (control_d[75:69])
      7'b0000011, 7'b0010111, 7'b0100011, 7'b1100011, 7'b1100111, 7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3 = 4'd0;
      7'b0010011:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3 =
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_IF_cont_ETC__q2;
      7'b0110011:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3 =
	      (control_d[50:44] == 7'b0000001) ?
		4'd0 :
		IF_control_d_BITS_53_TO_51_5_EQ_0b0_6_THEN_IF__ETC___d54;
      7'b0110111:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3 = 4'd10;
      default: CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_CA_ETC__q3 = 4'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[75:69])
      7'b0010111:
	  CASE_control_d_BITS_75_TO_69_0b10111_1_0b11011_ETC__q4 = 2'd1;
      7'b0110111:
	  CASE_control_d_BITS_75_TO_69_0b10111_1_0b11011_ETC__q4 = 2'd2;
      default: CASE_control_d_BITS_75_TO_69_0b10111_1_0b11011_ETC__q4 = 2'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd1;
      3'b001: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd2;
      3'b100: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd3;
      3'b101: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd4;
      3'b110: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd5;
      3'b111: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd6;
      default: CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5 = 3'd0;
    endcase
  end
  always@(control_d or CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5)
  begin
    case (control_d[75:69])
      7'b0010111, 7'b0110111, 7'b1100111, 7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b10111_0_0b11011_ETC__q6 = 3'd0;
      7'b1100011:
	  CASE_control_d_BITS_75_TO_69_0b10111_0_0b11011_ETC__q6 =
	      CASE_control_d_BITS_53_TO_51_0b0_1_0b1_2_0b100_ETC__q5;
      default: CASE_control_d_BITS_75_TO_69_0b10111_0_0b11011_ETC__q6 = 3'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0, 3'b001, 3'b010, 3'b011, 3'b100, 3'b101, 3'b110, 3'b111:
	  CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q7 =
	      control_d[53:51];
    endcase
  end
  always@(control_d or CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q7)
  begin
    case (control_d[75:69])
      7'b0000011,
      7'b0010011,
      7'b0010111,
      7'b0100011,
      7'b0110111,
      7'b1100011,
      7'b1100111,
      7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q8 = 3'd0;
      7'b0110011:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q8 =
	      (control_d[50:44] == 7'b0000001) ?
		CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q7 :
		3'd0;
      default: CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q8 = 3'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0, 3'b100:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9 = 2'd0;
      3'b001, 3'b101:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9 = 2'd1;
      3'b010: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9 = 2'd2;
      default: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9 = 2'd2;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10 = 2'd0;
      3'b001: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10 = 2'd1;
      default: CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10 = 2'd2;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9 or
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10)
  begin
    case (control_d[75:69])
      7'b0000011:
	  CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11 =
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q9;
      7'b0010111, 7'b0110111, 7'b1100011, 7'b1100111, 7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11 = 2'd2;
      7'b0100011:
	  CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11 =
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_2__q10;
      default: CASE_control_d_BITS_75_TO_69_0b11_CASE_control_ETC__q11 = 2'd2;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0:
	  CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12 =
	      control_d[53:51];
      3'b001, 3'b010, 3'b011, 3'b101, 3'b110, 3'b111:
	  CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12 = 3'd3;
      3'd4: CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12 = 3'd0;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12)
  begin
    case (control_d[75:69])
      7'b0000011:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 = 3'd1;
      7'b0010011, 7'b0010111, 7'b0100011, 7'b0110111, 7'b1100011:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 = 3'd0;
      7'b0110011:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 =
	      (control_d[50:44] == 7'b0000001) ? 3'd4 : 3'd0;
      7'b1100111:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 =
	      (control_d[53:51] == 3'b0) ? 3'd2 : 3'd0;
      7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 = 3'd2;
      7'b1110011:
	  CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 =
	      CASE_control_d_BITS_53_TO_51_0b0_control_d_BIT_ETC__q12;
      default: CASE_control_d_BITS_75_TO_69_0b11_1_0b10011_0__ETC__q13 = 3'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0, 3'd4:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14 = 2'd0;
      3'b001, 3'b101:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14 = 2'd1;
      3'b010, 3'b110:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14 = 2'd2;
      3'b011, 3'b111:
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14 = 2'd3;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14)
  begin
    case (control_d[75:69])
      7'b0000011,
      7'b0010011,
      7'b0010111,
      7'b0100011,
      7'b0110011,
      7'b0110111,
      7'b1100011,
      7'b1100111,
      7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q15 = 2'd0;
      7'b1110011:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q15 =
	      CASE_control_d_BITS_53_TO_51_0b0_0_0b1_1_0b10__ETC__q14;
      default: CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q15 = 2'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[43:32])
      12'h0: CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16 = 2'd1;
      12'h001: CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16 = 2'd2;
      12'h302: CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16 = 2'd3;
      default: CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16 = 2'd0;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16)
  begin
    case (control_d[75:69])
      7'b0000011,
      7'b0010011,
      7'b0010111,
      7'b0100011,
      7'b0110011,
      7'b0110111,
      7'b1100011,
      7'b1100111,
      7'b1101111:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q17 = 2'd0;
      7'b1110011:
	  CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q17 =
	      (control_d[53:51] == 3'b0) ?
		CASE_control_d_BITS_43_TO_32_0x0_1_0x1_2_0x302_ETC__q16 :
		2'd0;
      default: CASE_control_d_BITS_75_TO_69_0b11_0_0b10011_0__ETC__q17 = 2'd0;
    endcase
  end
  always@(control_d)
  begin
    case (control_d[53:51])
      3'b0, 3'b101:
	  CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18 =
	      control_d[50:44] != 7'b0 && control_d[50:44] != 7'b0100000;
      3'b001, 3'b010, 3'b011, 3'b100, 3'b110:
	  CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18 =
	      control_d[50:44] != 7'b0;
      3'd7:
	  CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18 =
	      control_d[53:51] == 3'b111 && control_d[50:44] != 7'b0;
    endcase
  end
  always@(control_d or
	  CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18)
  begin
    case (control_d[75:69])
      7'b0000011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[53:51] != 3'b0 && control_d[53:51] != 3'b001 &&
	      control_d[53:51] != 3'b010 &&
	      control_d[53:51] != 3'b100 &&
	      control_d[53:51] != 3'b101;
      7'b0010011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[53:51] != 3'b0 && control_d[53:51] != 3'b010 &&
	      control_d[53:51] != 3'b011 &&
	      control_d[53:51] != 3'b100 &&
	      control_d[53:51] != 3'b110 &&
	      control_d[53:51] != 3'b111 &&
	      ((control_d[53:51] == 3'b001) ?
		 control_d[50:44] != 7'b0 :
		 control_d[53:51] != 3'b101 ||
		 control_d[50:44] != 7'b0 && control_d[50:44] != 7'b0100000);
      7'b0100011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[53:51] != 3'b0 && control_d[53:51] != 3'b001 &&
	      control_d[53:51] != 3'b010;
      7'b0110011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[50:44] != 7'b0000001 &&
	      CASE_control_d_BITS_53_TO_51_0b0_NOT_control_d_ETC__q18;
      7'b1100011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[53:51] != 3'b0 && control_d[53:51] != 3'b001 &&
	      control_d[53:51] != 3'b100 &&
	      control_d[53:51] != 3'b101 &&
	      control_d[53:51] != 3'b110 &&
	      control_d[53:51] != 3'b111;
      7'b1100111:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      control_d[53:51] != 3'b0;
      7'b1110011:
	  CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
	      (control_d[53:51] == 3'b0) ?
		control_d[43:32] != 12'h0 && control_d[43:32] != 12'h001 &&
		control_d[43:32] != 12'h302 &&
		control_d[43:32] != 12'h105 :
		control_d[53:51] != 3'b001 && control_d[53:51] != 3'b010 &&
		control_d[53:51] != 3'b011 &&
		control_d[53:51] != 3'b101 &&
		control_d[53:51] != 3'b110 &&
		control_d[53:51] != 3'b111;
      default: CASE_control_d_BITS_75_TO_69_0b11_NOT_control__ETC__q19 =
		   control_d[75:69] != 7'b0001111;
    endcase
  end
endmodule  // module_control

