//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// immGen                         O    32
// immGen_inst                    I    32
//
// Combinational paths from inputs to outputs:
//   immGen_inst -> immGen
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_immGen(immGen_inst,
		     immGen);
  // value method immGen
  input  [31 : 0] immGen_inst;
  output [31 : 0] immGen;

  // signals for module outputs
  reg [31 : 0] immGen;

  // remaining internal signals
  wire [31 : 0] SEXT_immGen_inst_BITS_31_TO_20____d8;
  wire [20 : 0] x__h263;
  wire [12 : 0] x__h143;
  wire [11 : 0] immGen_inst_BITS_31_TO_20__q1, x__h95;

  // value method immGen
  always@(immGen_inst or
	  SEXT_immGen_inst_BITS_31_TO_20____d8 or
	  x__h95 or x__h143 or x__h263)
  begin
    case (immGen_inst[6:0])
      7'b0000011, 7'b0010011, 7'b1100111, 7'b1110011:
	  immGen = SEXT_immGen_inst_BITS_31_TO_20____d8;
      7'b0010111, 7'b0110111: immGen = { immGen_inst[31:12], 12'b0 };
      7'b0100011: immGen = { {20{x__h95[11]}}, x__h95 };
      7'b1100011: immGen = { {19{x__h143[12]}}, x__h143 };
      7'b1101111: immGen = { {11{x__h263[20]}}, x__h263 };
      default: immGen = 32'd0;
    endcase
  end

  // remaining internal signals
  assign SEXT_immGen_inst_BITS_31_TO_20____d8 =
	     { {20{immGen_inst_BITS_31_TO_20__q1[11]}},
	       immGen_inst_BITS_31_TO_20__q1 } ;
  assign immGen_inst_BITS_31_TO_20__q1 = immGen_inst[31:20] ;
  assign x__h143 =
	     { immGen_inst[31],
	       immGen_inst[7],
	       immGen_inst[30:25],
	       immGen_inst[11:8],
	       1'b0 } ;
  assign x__h263 =
	     { immGen_inst[31],
	       immGen_inst[19:12],
	       immGen_inst[20],
	       immGen_inst[30:21],
	       1'b0 } ;
  assign x__h95 = { immGen_inst[31:25], immGen_inst[11:7] } ;
endmodule  // module_immGen

