//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// decode                         O    76
// decode_inst                    I    32
//
// Combinational paths from inputs to outputs:
//   decode_inst -> decode
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decode(decode_inst,
		     decode);
  // value method decode
  input  [31 : 0] decode_inst;
  output [75 : 0] decode;

  // signals for module outputs
  wire [75 : 0] decode;

  // remaining internal signals
  wire [31 : 0] immGen___d10;

  // value method decode
  assign decode =
	     { decode_inst[6:0],
	       decode_inst[11:7],
	       decode_inst[19:15],
	       decode_inst[24:20],
	       decode_inst[14:12],
	       decode_inst[31:25],
	       decode_inst[31:20],
	       immGen___d10 } ;

  // remaining internal signals
  module_immGen instance_immGen_0(.immGen_inst(decode_inst),
				  .immGen(immGen___d10));
endmodule  // module_decode

