//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// alu                            O    32
// alu_op                         I     4
// alu_a                          I    32
// alu_b                          I    32
//
// Combinational paths from inputs to outputs:
//   (alu_op, alu_a, alu_b) -> alu
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_alu(alu_op,
		  alu_a,
		  alu_b,
		  alu);
  // value method alu
  input  [3 : 0] alu_op;
  input  [31 : 0] alu_a;
  input  [31 : 0] alu_b;
  output [31 : 0] alu;

  // signals for module outputs
  reg [31 : 0] alu;

  // remaining internal signals
  wire [31 : 0] alu_a_PLUS_alu_b___d2;

  // value method alu
  always@(alu_op or alu_a_PLUS_alu_b___d2 or alu_a or alu_b)
  begin
    case (alu_op)
      4'd0: alu = alu_a_PLUS_alu_b___d2;
      4'd1: alu = alu_a - alu_b;
      4'd2: alu = alu_a << alu_b[4:0];
      4'd3:
	  alu =
	      ((alu_a ^ 32'h80000000) < (alu_b ^ 32'h80000000)) ?
		32'd1 :
		32'd0;
      4'd4: alu = (alu_a < alu_b) ? 32'd1 : 32'd0;
      4'd5: alu = alu_a ^ alu_b;
      4'd6: alu = alu_a >> alu_b[4:0];
      4'd7:
	  alu =
	      alu_a >> alu_b[4:0] |
	      ~(32'hFFFFFFFF >> alu_b[4:0]) & {32{alu_a[31]}};
      4'd8: alu = alu_a | alu_b;
      4'd9: alu = alu_a & alu_b;
      4'd10: alu = alu_b;
      default: alu = alu_a_PLUS_alu_b___d2;
    endcase
  end

  // remaining internal signals
  assign alu_a_PLUS_alu_b___d2 = alu_a + alu_b ;
endmodule  // module_alu

