//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// branchJump                     O    33
// branchJump_c                   I    31
// branchJump_pc                  I    32
// branchJump_a                   I    32
// branchJump_b                   I    32
// branchJump_imm                 I    32
//
// Combinational paths from inputs to outputs:
//   (branchJump_c,
//    branchJump_pc,
//    branchJump_a,
//    branchJump_b,
//    branchJump_imm) -> branchJump
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_branchJump(branchJump_c,
			 branchJump_pc,
			 branchJump_a,
			 branchJump_b,
			 branchJump_imm,
			 branchJump);
  // value method branchJump
  input  [30 : 0] branchJump_c;
  input  [31 : 0] branchJump_pc;
  input  [31 : 0] branchJump_a;
  input  [31 : 0] branchJump_b;
  input  [31 : 0] branchJump_imm;
  output [32 : 0] branchJump;

  // signals for module outputs
  wire [32 : 0] branchJump;

  // remaining internal signals
  reg IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22;
  wire [31 : 0] _theResult___snd__h100,
		_theResult___snd__h83,
		branchJump_a_PLUS_branchJump_imm__q1,
		branchJump_pc_PLUS_4___d31,
		branchJump_pc_PLUS_branchJump_imm___d29,
		target___1__h102,
		target___1__h178;
  wire branchJump_a_EQ_branchJump_b___d6,
       branchJump_a_SLT_branchJump_b___d10,
       branchJump_a_ULT_branchJump_b___d14;

  // value method branchJump
  assign branchJump =
	     { branchJump_c[20] ||
	       branchJump_c[23:21] != 3'd0 &&
	       IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22,
	       branchJump_c[20] ?
		 _theResult___snd__h83 :
		 _theResult___snd__h100 } ;

  // remaining internal signals
  assign _theResult___snd__h100 =
	     (branchJump_c[23:21] == 3'd0) ?
	       branchJump_pc_PLUS_4___d31 :
	       target___1__h102 ;
  assign _theResult___snd__h83 =
	     branchJump_c[19] ?
	       target___1__h178 :
	       branchJump_pc_PLUS_branchJump_imm___d29 ;
  assign branchJump_a_EQ_branchJump_b___d6 = branchJump_a == branchJump_b ;
  assign branchJump_a_PLUS_branchJump_imm__q1 =
	     branchJump_a + branchJump_imm ;
  assign branchJump_a_SLT_branchJump_b___d10 =
	     (branchJump_a ^ 32'h80000000) < (branchJump_b ^ 32'h80000000) ;
  assign branchJump_a_ULT_branchJump_b___d14 = branchJump_a < branchJump_b ;
  assign branchJump_pc_PLUS_4___d31 = branchJump_pc + 32'd4 ;
  assign branchJump_pc_PLUS_branchJump_imm___d29 =
	     branchJump_pc + branchJump_imm ;
  assign target___1__h102 =
	     IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 ?
	       branchJump_pc_PLUS_branchJump_imm___d29 :
	       branchJump_pc_PLUS_4___d31 ;
  assign target___1__h178 =
	     { branchJump_a_PLUS_branchJump_imm__q1[31:1], 1'd0 } ;
  always@(branchJump_c or
	  branchJump_a_ULT_branchJump_b___d14 or
	  branchJump_a_EQ_branchJump_b___d6 or
	  branchJump_a_SLT_branchJump_b___d10)
  begin
    case (branchJump_c[23:21])
      3'd1:
	  IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
	      branchJump_a_EQ_branchJump_b___d6;
      3'd2:
	  IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
	      !branchJump_a_EQ_branchJump_b___d6;
      3'd3:
	  IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
	      branchJump_a_SLT_branchJump_b___d10;
      3'd4:
	  IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
	      !branchJump_a_SLT_branchJump_b___d10;
      3'd5:
	  IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
	      branchJump_a_ULT_branchJump_b___d14;
      default: IF_branchJump_c_BITS_23_TO_21_EQ_1_THEN_branch_ETC___d22 =
		   branchJump_c[23:21] == 3'd6 &&
		   !branchJump_a_ULT_branchJump_b___d14;
    endcase
  end
endmodule  // module_branchJump

