//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//

//
//
// Ports:
// Name                         I/O  size props
// hazard                         O     3
// hazard_exMemRead               I     1
// hazard_exRd                    I     5
// hazard_rs1                     I     5
// hazard_rs2                     I     5
//
// Combinational paths from inputs to outputs:
//   (hazard_exMemRead, hazard_exRd, hazard_rs1, hazard_rs2) -> hazard
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_hazard(hazard_exMemRead,
		     hazard_exRd,
		     hazard_rs1,
		     hazard_rs2,
		     hazard);
  // value method hazard
  input  hazard_exMemRead;
  input  [4 : 0] hazard_exRd;
  input  [4 : 0] hazard_rs1;
  input  [4 : 0] hazard_rs2;
  output [2 : 0] hazard;

  // signals for module outputs
  wire [2 : 0] hazard;

  // remaining internal signals
  wire hazard_exMemRead_AND_NOT_hazard_exRd_EQ_0_AND__ETC___d7;

  // value method hazard
  assign hazard =
	     {3{hazard_exMemRead_AND_NOT_hazard_exRd_EQ_0_AND__ETC___d7}} ;

  // remaining internal signals
  assign hazard_exMemRead_AND_NOT_hazard_exRd_EQ_0_AND__ETC___d7 =
	     hazard_exMemRead && hazard_exRd != 5'd0 &&
	     (hazard_exRd == hazard_rs1 || hazard_exRd == hazard_rs2) ;
endmodule  // module_hazard

